### ISSUE TITLE
REUSE Tool does not ignore files beginning with LICENSE

### ISSUE THREAD

**Issue by AliSajid** [fsfe/reuse-tool#1032]
I'm working on a project that was up until recently REUSE compliant. I had two files, `LICENSE-MIT` and `LICENSE-APACHE` in the repository to have GitHub license recognition work as well as a `.reuse/dep5` and the `LICENSES` directory.

Today as I upgraded to `reuse` tool 4.0.2 from 3.0.2, I see a non-compliance warning with the above 2 license files being marked as not containing a license. As I understand from #881 that the tool ignores the files that start with `LICENSE`. Please advise on how to proceed here.

Repository: [CogDisResLab/Kaleidoscope](https://github.com/CogDisResLab/Kaleidoscope)

**Comment by carmenbianca** [comment]
Hi @AliSajid. Copying from the change log:

```markdown
- Previously, any file that begins with `COPYING` or `LICENSE` was ignored. This
  has been changed. Now, files like `COPYING_README` are no longer ignored, but
  `COPYING` and `COPYING.txt` are still ignored (in other words: exact matches,
  or `COPYING` + a file extension). Idem ditto for `LICENSE`. (#886)
```

It should suffice to rename to `LICENSE.MIT`.

**Comment by sorairolake** [comment]
`LICENSE.APACHE` may not be recognized correctly on <https://pkg.go.dev/> (see [License Disclaimer](https://pkg.go.dev/license-policy)). However, this may be something the other side should fix.

**Comment by carmenbianca** [comment]
This is possibly also an issue that could be solved here, although it would annoyingly require a spec bump, which is not ideal at all. I'll get back on this.

**Comment by sorairolake** [comment]
> `LICENSE.APACHE` may not be recognized correctly on https://pkg.go.dev/ (see [License Disclaimer](https://pkg.go.dev/license-policy)). However, this may be something the other side should fix.

This may be solved by merging `LICENSE-MIT` and `LICENSE-APACHE` into a single file (`LICENSE`):

```text
Apache License 2.0 text

---

MIT License text
```

**Comment by AliSajid** [comment]
Thank you for this detailed response and I appreciate you helping me out. REUSE is a great project and I'm indebted to your team for it. Thank you.

**Comment by carmenbianca** [comment]
You're welcome @AliSajid ! I will re-open this issue because I am discussing it tomorrow with the team.
