### ISSUE TITLE
reuse 4.0.2 version specifier for `attrs` too relaxed

### ISSUE THREAD

**Issue by MarkCallow** [fsfe/reuse-tool#1039]
reuse 4.0.2 specifies `attrs>=21.1`. When I `pip install reuse` on a Travis-CI Ubuntu Jammy (22.04) runner `pip` tells me "already satisfied by `attrs` version 21.2 in `/usr/lib/python3/dist-packages`". But when I run `reuse` it errors out with ModuleNotFound for `attrs`.

When I run on my local Ubuntu Jammy, `attrs` 23.2 is installed and `reuse` works. So I added `pip3 install --upgrade attrs` to our Travis-CI script. `attrs` is upgraded to 23.2 and reuse works.

Conclusion: reuse 4.0.2 needs a newer version of attrs than 21.2; its version specifier is wrong.

**Comment by carmenbianca** [comment]
Released as v4.0.3

**Comment by MarkCallow** [comment]
Thanks for the quick fix.
