### ISSUE TITLE
Complete 0.5.2 release

### ISSUE THREAD

**Issue by davidak** [fsfe/reuse-tool#104]
A new tag was pushed to GitHub and a release was published on PyPI.

https://pypi.org/project/fsfe-reuse/

Missing is:

- GitHub release https://github.com/fsfe/reuse-tool/releases
- Changelog https://reuse.readthedocs.io/en/stable/history.html

**Comment by carmenbianca** [comment]
I've updated readthedocs.

I've also removed the github releases. I don't really see the point of manually maintaining them when they only contain the changelogs that are in the body text of the version tags, anyway.

Thank you @davidak :)
