### ISSUE TITLE
Please allow for a hidden REUSE.toml file

### ISSUE THREAD

**Issue by mlramd** [fsfe/reuse-tool#1054]
I like the idea of using reuse to check my projects, but I don't want the REUSE.toml file in the root directory. It seems like an advertisement for the reuse project. For now I'm just going to keep local copies of the file instead of committing it to the repo.

Could you make reuse work with .REUSE.toml or .reuse/REUSE.toml please? Even giving reuse an option for a config file name, rather than having it hardcoded would work.

Thanks.

**Comment by carmenbianca** [comment]
Hi @mlramd, I am closing this WONTFIX. From #779:

> I intend to support exclusively `REUSE.toml`, and NOT `.REUSE.toml`. People will be peeved by this choice (they don't like random tools littering their clean workspace), but I propose that we stand by this choice. By allowing dotfiles, we would run the risk that the licensing information is hidden on some computers. Licensing information should not be hidden, ergo let's not do dotfiles.

The importance here is the visibility of licensing.

We could have gone with an 'unbranded' `LICENSING.toml`, but the whole REUSE endeavour is non-profit run by a charity, so the self-propagation via the name of the file is fine to me.

**Comment by seabass-labrax** [comment]
In my experience, a sizeable proportion of those who do FOSS licence compliance have a legal background, and not always a technical one. Having the files hidden by default would add an impediment (admittedly, a small one) to their task. Given that the primary reason for REUSE is to make licence compliance easier, I don't personally think it's the right trade-off to make.

**Comment by mlramd** [comment]
If you want to force this on people, I can understand that, but I'm not going to be checking the REUSE.toml file into my projects, and I imagine that there will be others that agree.

In my mind, reuse is a tool to make sure that we have the licensing in the project correct, and honestly that's all it is. If the licensing isn't correct unless there's an advertisement for your tool in the root of the project, *I* think that's a problem.

Regardless, your projects choices are up to you - All I can say is that I'm not going to be forced into having the file at the root of my projects.

Take care.
Martin
