### ISSUE TITLE
Problem with website - service down

### ISSUE THREAD

**Issue by RobPasMue** [fsfe/reuse-tool#1064]
I'm sure you are already aware but the current website is down, I didn't know how else to report it.

Free Software Foundation Europe
Webservice currently unavailable 502
We've got some trouble with our backend upstream cluster.
Our system administrators have been dispatched to bring it back online.

![image](https://github.com/user-attachments/assets/cdf43a26-7383-4719-b303-af5819a109ea)

**Comment by carmenbianca** [comment]
Yes, this was between Sunday evening and today in the morning. I fixed it in https://github.com/fsfe/reuse-website/pull/91 just now, with major help from @tobiasd

Thanks for the issue!

**Comment by RobPasMue** [comment]
Awesome, thanks a lot!!
