### ISSUE TITLE
Wrong anchor links in readthedocs

### ISSUE THREAD

**Issue by DerMolly** [fsfe/reuse-tool#1065]
I just noticed that on https://reuse.readthedocs.io/en/stable/history.html the anchor links for the releases seem to be iterating, so currently https://reuse.readthedocs.io/en/stable/history.html#id6 links to the 4.0.0 release, but it probably will change with the next release. This is rather unfortunate, especially if people want to reference specific change log entries in e.g commit messages.

**Comment by carmenbianca** [comment]
This is an interesting bug, thank you @DerMolly ! I suspect that Sphinx doesn't generate a usable anchor because the section is exclusively numbers? I can play with that a little.
