### ISSUE TITLE
markupsafe dependency is missing

### ISSUE THREAD

**Issue by matkoniecz** [fsfe/reuse-tool#109]
After install: `reuse --help` triggers

`ModuleNotFoundError: No module named 'markupsafe'` (full log in https://gist.github.com/matkoniecz/a20d59353b63ce7af9749fd99458400c )

After manual `pip3.6 install --user markupsafe` command  `reuse --help` works

```
usage: reuse [-h] [--debug] [--version]
             {addheader,download,init,lint,spdx} ...

reuse is a tool for compliance with the REUSE recommendations. See
<https://reuse.software/> for more information, and
<https://reuse.readthedocs.io/> for the online documentation.

This version of reuse is compatible with version 3.0 of the REUSE
Specification.

Support the FSFE's work:

  Donations are critical to our strength and autonomy. They enable us to
  continue working for Free Software wherever necessary. Please consider
  making a donation at <https://fsfe.org/donate/>.

optional arguments:
  -h, --help            show this help message and exit
  --debug               enable debug statements
  --version             show program's version number and exit

subcommands:
  {addheader,download,init,lint,spdx}
    addheader           add copyright and licensing into the header of files
    download            download a license and place it in the LICENSES/ directory
    init                initialize REUSE project
    lint                list all non-compliant files
    spdx                print the project's bill of materials in SPDX format
```

**Comment by carmenbianca** [comment]
I'm fairly certain this is an upstream issue with Jinja2.

… I checked Jinja's [setup.py](https://github.com/pallets/jinja/blob/master/setup.py), though, and it does explicitly declare MarkupSafe as dependency.

Not sure what's going on here.

**Comment by matkoniecz** [comment]
https://github.com/pallets/jinja/blob/master/setup.py#L51 has it as `install_requires` and `reuse` needs it on runtime. Note entirely sure what happens here.

But it needs either replacement by other tool without this issue, maybe new Jinja2 version or a workround.

**Comment by carmenbianca** [comment]
`install_requires` is a runtime requirement, as far as I know.

**Comment by matkoniecz** [comment]
yes, it should be installed. Either pip in general, or my pip specifically is broken. Or `install_requires` is somehow mangled in their `setup.py`

> install_requires is a setuptools setup.py keyword that should be used to specify what a project minimally needs to run correctly. When the project is installed by pip, this is the specification that is used to install its dependencies.

https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by akx** [comment]
Based on the details in https://github.com/pallets/jinja/issues/1103 this is not a Reuse bug nor a Jinja2 bug, but a classic case of a mix between Ubuntu/Debian distribution-provided packages and user packages. 

Maybe the installation instructions should be amended to recommend a virtualenv be used?

**Comment by carmenbianca** [comment]
> Maybe the installation instructions should be amended to recommend a virtualenv be used?

This is a good recommendation to people who know what they are doing and are familiar with Python, but this project doesn't really target the latter group. `pip3 install --user $package` hasn't given me a lot of grief so far. I'm assuming that maybe @matkoniecz is using some esoteric Python setup with `pip3.6`?

Making distribution packages for reuse would make it even easier, but my word do I not know how Debian packaging works.

**Comment by akx** [comment]
Yeah, I meant to say virtualenvs aren't for the casual user though.

The underlying problem here, I think, is that @matkoniecz's distribution has some version of Jinja2 in `dist-packages`, and `pip` is satisfied with it even if everything else would be freshly installed into the user path thanks to `--user`.

**Comment by carmenbianca** [comment]
Closing PEBCAK :x Or some upstream Debian bug
