### ISSUE TITLE
lint: Directories ignored by default?

### ISSUE THREAD

**Issue by buhtz** [fsfe/reuse-tool#1095]
It seems to me that the folder `.git` is ignored by default when using `$ reuse lint`.

That make sense of course. But the "bug" is that it seems not to be documented anywhere.

The next point is a feature request to add more dirs to ignore (e.g. `.github`) or a switch to ignore all folders beginning with dot.

**Comment by carmenbianca** [comment]
Hi @buhtz  This is documented [here](https://reuse.software/spec-3.2/#covered-and-ignored-files), which `reuse lint --help` links to.

There [are no plans](https://reuse.software/faq/#exclude-file) to allow custom directories/files to be ignored.

I hope this helps!
