### ISSUE TITLE
 java files are not supported (.java)

### ISSUE THREAD

**Issue by matkoniecz** [fsfe/reuse-tool#111]
manual override with `--style c` appears to work, autodetection would be nice

I can open several issues like this (based on a real project where due to NGI0 I am now testing applying this comments).

Or maybe make a PRs - it should be added to https://github.com/fsfe/reuse-tool/blob/caa802a52ff45add6175cf23b8db0951fb9c3a54/src/reuse/_comment.py#L328 , right?

**Comment by matkoniecz** [comment]
But https://github.com/fsfe/reuse-tool/blob/caa802a52ff45add6175cf23b8db0951fb9c3a54/src/reuse/_comment.py#L345 already has `.java` and `reuse 0.5.2` is not detecting it.

`0.5.2` was released 17 days ago per https://github.com/fsfe/reuse-tool/releases and .java was added apparently earlier https://github.com/fsfe/reuse-tool/commits/caa802a52ff45add6175cf23b8db0951fb9c3a54/src/reuse/_comment.py

But `touch test.java` + `reuse addheader --copyright TEST --license PD test.java` works.

**Comment by matkoniecz** [comment]
closing for now as a hallucination

**Comment by carmenbianca** [comment]
It might've been that you did something like:

`reuse addheader --copyright="whatever" example.unsupported example.java`

and the tool complained.
