### ISSUE TITLE
problem with --explicit-license for unrecognised files

### ISSUE THREAD

**Issue by matkoniecz** [fsfe/reuse-tool#113]
`.txt` files have no ability to handle comments, so I want to store license metadata in separate files.

But
```
touch test.txt
reuse addheader --copyright TEST --license PD --explicit-license test.txt
```
fails with `reuse addheader: error: 'test.txt' does not have a recognised file extension, please use --style`

note that `reuse addheader --help` has 

```
If a binary file is detected, or if --explicit-license is specified, the
header is placed in a .license file. IMPORTANT: This is currently
EXPERIMENTAL!
```

I am guessing that check for recognised file extensions is run unnecessarily in case of explicit request to put metada into a separate file (`--explicit-license`)

I hit the same with `.json` and `.svg` files.

**Comment by carmenbianca** [comment]
> I am guessing that check for recognised file extensions is run unnecessarily in case of explicit request to put metada into a separate file (--explicit-license)

That does appear to be the case. I'll have some time to take a look at this soon.

**Comment by matkoniecz** [comment]
oo, great! Thanks for a quick reaction!
