### ISSUE TITLE
add support for comments in .bat files (new comment style)

### ISSUE THREAD

**Issue by matkoniecz** [fsfe/reuse-tool#118]
According to https://stackoverflow.com/questions/11269338/how-to-comment-out-add-comment-in-a-batch-cmd this has a new separate syntax, with `REM comment text`

**Comment by matkoniecz** [comment]
BTW, https://en.wikipedia.org/wiki/Comment_(computer_programming)#Examples has some futher examples

**Comment by mxmehl** [comment]
Just noting that this is already done:

https://github.com/fsfe/reuse-tool/blob/master/src/reuse/_comment.py#L263
https://github.com/fsfe/reuse-tool/blob/master/src/reuse/_comment.py#L452
