### ISSUE TITLE
How should `reuse addheader` deal with existing headers?

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#12]
This is related to #11.

This issue proposes several design challenges for the behaviour of `reuse addheader`. I'm not really sure how to introduce them other than to simply expose them.

Just assume that we call `reuse addheader` on all files.

# 1. How to deal with existing header

Given a file

```python
# This is my first program

print("Hello, world")
```

What should be done with the existing header?

1. It should be removed and replaced
2. It should be combined with the new header
3. It should be shifted downwards so that it is the second comment block

# 2. How to deal with existing SPDX Info in the header

Given a file

```python
# This file is copyrighted by:
#
# SPDX-Copyright: Mary Sue
#
# This file is licensed under:
#
# SPDX-License-Identifier: 0BSD

print("Hello, world!")
```

What should be done with the existing header?

1. It should be removed and replaced
2. It should be combined with the new header
3. It should be shifted downwards so that it is the second comment block

# 3. How to deal with existing SPDX Info _outside_ of the header

Given a file

```python
# This is my first program

# SPDX-Copyright: Mary Sue

print("Hello, world!")
```

What should be done with the SPDX info?

1. Remove it and put it in the new header
2. Ignore it

**Comment by carmenbianca** [comment]
#4. How to deal with shebang
Given a file

```python
#!/usr/bin/env python3

print("Hello, world!")
```

What should be done with the existing header?

1. It should be removed and replaced
2. It should be combined with the new header
3. It should be shifted downwards so that it is the second comment block

**Comment by mxmehl** [comment]
Good questions! My suggestions:

> 1. How to deal with existing header

Shift downwards. I guess that's a common place for many projects. But it could also well be below the existing header or combined, I don't have a strong opinion.

> 2. How to deal with existing SPDX Info in the header

IMHO we cannot make a decision here. The tool should warn, and offer a `--force` option to replace it, or at least remove the conflicting Copyright and License information.

> 3. How to deal with existing SPDX Info outside of the header

Same as 2. Warn and allow a forced replacement

> 4. How to deal with shebang

Shebang should always be on top, then directly afterwards the license info.

**Comment by carmenbianca** [comment]
Agree on 1.

Slight disagree on 2. But maybe that's because I'm missing an additional case. I'll introduce case 5 in an additional post. Basically, I don't want to remove existing SPDX Info, but I am not certain what to do with the custom formatting around the original header. But will elaborate in case 5.

I am ambivalent on 3. I agree with a warning ("hey, you have SPDX tags outside of the comment header"), but I'm really not sure what to do with it. Also as addendum: If the SPDX tag is explicitly and consciously outside of the header (ex., if they're clarifying the copyright and licensing of a code snippet), then that warning may be really annoying for the user. I am not sure I want to remove that comment, though. I can currently easily extract the header comment, but I cannot easily extract other comments.

Agree on 4.

**Comment by carmenbianca** [comment]
# 5. How to deal with SPDX Info in header that is correctly formatted

Given a file

```python
# SPDX-Copyright: Mary Sue
#
# SPDX-License-Identifier: 0BSD

print("Hello, world!")
```

What should be done with this header?

My opinion is that the tool should just add additional entries to the header (i.e., combine the information). We could potentially add a `--replace` flag that deletes existing entries. The reason I want to combine is because I imagine that the use case "add my name to existing entries" is more common than "this header is wrong; please replace it entirely".

Maybe it would also be nice to have a programatic `reuse removefromheader` or something, but that seems very low priority to me.

**Comment by mxmehl** [comment]
Oh true, I didn't think of the case of someone who want to add herself to the header. But is addheader the right tool for that? I would assume that if a person edits a file significantly, she also adds herself. I don't see a tool doing that decision as soon as a project is REUSE compliant. What do you think?

**Comment by carmenbianca** [comment]
Currently, the following happens:

1. Move the original header downwards
2. Entire header replaced with template
3. Not dealt with at all
4. Shebang is preserved

Closing this because #67 fixed this.
