### ISSUE TITLE
TypeError: 'PosixPath' object is not subscriptable

### ISSUE THREAD

**Issue by Vinnl** [fsfe/reuse-tool#128]
I'm pulling the latest Docker images in my CI, and while a run from November 17 was still completing successfully, the next run from November 24th, and all runs after that, fail with the following error message:

> Traceback (most recent call last):
>   File "/usr/bin/reuse", line 11, in <module>
>     load_entry_point('fsfe-reuse==0.6.0', 'console_scripts', 'reuse')()
>   File "/usr/lib/python3.7/site-packages/fsfe_reuse-0.6.0-py3.7.egg/reuse/_main.py", line 245, in main
>     return parsed_args.func(parsed_args, project, out)
>   File "/usr/lib/python3.7/site-packages/fsfe_reuse-0.6.0-py3.7.egg/reuse/lint.py", line 336, in run
>     report = ProjectReport.generate(project, do_checksum=False)
>   File "/usr/lib/python3.7/site-packages/fsfe_reuse-0.6.0-py3.7.egg/reuse/report.py", line 187, in generate
>     elif project.license_map[name]["isDeprecatedLicenseId"]:
> TypeError: 'PosixPath' object is not subscriptable

See also:

- [Output of the latest successful run](https://gitlab.com/Flockademic/plaudit/-/jobs/353038138)
- [Output of the first failing run](https://gitlab.com/Flockademic/plaudit/-/jobs/359659111)

Looking at [the Docker tags](https://hub.docker.com/r/fsfe/reuse/tags), it looks like version 0.6 (and later 0.7) was released in between, so I'm guessing an error was introduced there?

**Comment by Vinnl** [comment]
Just reran it with v0.5.2, and [it succeeded](https://gitlab.com/Flockademic/plaudit/-/jobs/364453054).

**Comment by carmenbianca** [comment]
This was a bit confusing for me to debug. I found the problem: `latest` on Docker points to the master branch, not the latest stable version. This is *not ideal*, but it did unveil an issue I was not aware of.

@mxmehl Is it possible to point `latest` on Docker to the latest stable release instead?

I'll have a patch for this in a few minutes hopefully.
