### ISSUE TITLE
Docker latest points to master branch

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#130]
See #128 

@mxmehl

**Comment by mxmehl** [comment]
Well, `latest` has to point to a specific tag or branch. What we could to is having the `master` branch holiding experimental stuff which creates the `dev` Docker image, and a `stable` branch or tag which resolves to the latest release that we consider to be stable.

This solution would allow for automated build. Otherwise, I would have to build each tag manually which is rather painful and error-prone. @carmenbianca, what do you think about a stable branch or moving tag?

**Comment by carmenbianca** [comment]
My understanding of Docker conventions is that `latest` points to the latest stable release, like an alias. What you're proposing would be the `stable` branch. I don't know the DockerHub admin UI at all, however. Is there no button that basically just "does that"?

`dev` or `master` could point to the master branch, sure.

**Comment by mxmehl** [comment]
> My understanding of Docker conventions is that `latest` points to the latest stable release, like an alias. What you're proposing would be the `stable` branch. I don't know the DockerHub admin UI at all, however. Is there no button that basically just "does that"?

Unfortunately there is no option to make `latest` a pointer to the last tagged release. I need either a tag or branch to refer to, unless I make everything manually, and that's not really my goal to be honest...

**Comment by carmenbianca** [comment]
OK, I created a DockerHub account to see what the UI looks like. Would it help if I created a `latest` branch on GitHub that always points to the latest tagged release? It's a little bit more busywork, but a lot less busywork than messing around with the DockerHub admin UI every release.

**Comment by mxmehl** [comment]
Yes, that's possible! For Docker Hub it does not seem to matter whether it's a branch or tag, so feel free to choose :)

**Comment by carmenbianca** [comment]
Ah, a `latest` tag would be even easier.

I'll create the `latest` tag, and we'll end up with this:

latest tag (GitHub) -> latest (Docker)
master branch (GitHub) -> dev (Docker)

**Comment by mxmehl** [comment]
Ah thanks. I've set the auto-build rules like this. Is there any way to verify that we are on the correct commit and/or version, i.e. to find out whether `latest` is on 0.7.0 or master?

**Comment by carmenbianca** [comment]
> Is there any way to verify that we are on the correct commit and/or version, i.e. to find out whether latest is on 0.7.0 or master?

Where would you like to check this? On DockerHub—probably not. On GitHub—maybe? There's probably a bash one-liner I can run in the CI that checks "does `latest` point to the highest version tag?" . But I'm not sure when that should be run. On every commit? Probably not. Every time a tag is pushed?

Currently don't have time so will tinker later.

**Comment by carmenbianca** [comment]
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule

Posting because I found a thing but don't have time to implement it.

**Comment by mxmehl** [comment]
Ah sorry, I meant something much simpler: A possibility within the tool (e.g. as part of `--version`) to check the commit it was built from so I can verify whether Docker's latest tag actually matched 0.7.0. Right now, the image sizes vary from each other which confuses me a bit...

**Comment by carmenbianca** [comment]
> A possibility within the tool (e.g. as part of --version) to check the commit it was built from

I can't retroactively add this to 0.7.0. The best way to check this right now is to check whether any of the unreleased features in the CHANGELOG are present in `latest`.

It would be possible to add such functionality in later versions, but it is moderately non-trivial for Python programs unlike C programs, because Python programs are not typically compiled.

**Comment by carmenbianca** [comment]
Reopening until it has been verified that latest is actually 0.7.0.

**Comment by carmenbianca** [comment]
Manually confirmed by reviewing bits of source code in the container.

Also `dev` appears to point to the master branch, which is cool.
