### ISSUE TITLE
support .gitignore and other git config files in reuse addheader

### ISSUE THREAD

**Issue by matkoniecz** [fsfe/reuse-tool#135]
`reuse addheader .gitignore --copyright TEST --license "CC0-1.0"` now gives 

> reuse addheader: error: '.gitignore' does not have a recognised file extension, please use --style

See https://stackoverflow.com/questions/8865848/comments-in-gitignore

> Yes, you may put comments in there. They however must start at the beginning of a line.

**Comment by matkoniecz** [comment]
Similarly https://stackoverflow.com/questions/40847893/add-comments-remarks-to-gitattributes `.gitattributes`

**Comment by carmenbianca** [comment]
The way I have currently written the thing, it only deals with file extensions. I'm not certain whether ".gitconfig" is a file extension exactly. I've been meaning to add support for specific files such as "Makefile", so I'll use this issue to track that. It should be fairly trivial.
