### ISSUE TITLE
Add option to set the specification version for reuse lint

### ISSUE THREAD

**Issue by robinkrahl** [fsfe/reuse-tool#144]
I use the `reuse` tool in my CI setup to ensure that my code complies with version 3.0 of the REUSE specification.  I’d like to have an option to set the specification version for `reuse lint` so that the builds don’t fail if you release a new version of the specification that I don’t comply with (yet).

**Comment by carmenbianca** [comment]
The tool currently doesn't support multiple specifications simultaneously, and it is unlikely that it ever will. Instead, when a new version of the specification is released, a new version of the tool will be released. If you then want to check against the old specification, you have to use an older version of the tool.

I *could* add a simple check along the lines of `reuse --spec-version=3.0 lint`. If the tool then detects that it supports a different spec, it simply aborts with:

```
Sorry, this version of the tool does not support version 3.0 of the REUSE Specification. It only supports version X.Y. See <https://pypi.org/project/reuse/#history> for prior and future versions of this tool.
```

This still results in failed CI checks, however. A better approach might be to lock the version of `reuse` in your CI. So for instance, do `pip install reuse==0.7.0`, or the equivalent for Docker, or the equivalent in your CI's configuration files. I personally do this for all direct dependencies inside of this repository. See <https://github.com/fsfe/reuse-tool/blob/master/requirements.txt>. Every once in a while I bump the dependencies and see if anything went wrong. Usually `pylint` has a tiny little complaint.

**Comment by robinkrahl** [comment]
Okay, thanks for your answer! Then I’ll use a fixed version instead.
