### ISSUE TITLE
Copyright symbols other than `SPDX-Copyright: ` aren't yet supported

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#15]
Still need to do this... Also not sure whether `reuse addheader` should support using something other than `SPDX-Copyright`. Maybe that's a job for templates?

e.g., someone could have a template along the lines of:

```
SPDX-License-Identifier: {spdx_license_expression}

Copyright © {year} {copyright_holder} {copyright_contact}
```

instead of the default

```
SPDX-License-Identifier: {spdx_license_expression}

SPDX-Copyright: {year} {copyright_holder} {copyright_contact}
```

(Super rough sketch, that isn't an actual proposal)

**Comment by mxmehl** [comment]
Sounds good. I would suggest to start with the easy default (SPDX-Copyright/License-Identifier), and allow for adventurous customisations with the templates in an subsequent step.
