### ISSUE TITLE
addheader removes newline at end of file

### ISSUE THREAD

**Issue by marcusmueller** [fsfe/reuse-tool#153]
Since it's generally undesirable to *remove* anything when adding a license header and also clutters git diffs, I'd consider this a bug.

#Reproduction

* install reuse 0.8.0 via pip3
* Apply to bunch of C++ files ending in a newline: `reuse addheader --license "AGPL-3.0-or-later" FILENAMES.?pp`
* git diff excerpt:

```diff
diff --git a/include/FILENAME.hpp b/include/FILENAME.hpp
index 8afac27..a2f27de 100644
--- a/include/FILENAME.hpp
+++ b/include/FILENAME.hpp
@@ -0,0 +1,2 @@
+// SPDX-License-Identifier: AGPL-3.0-or-later
+
@@ -7 +9 @@ //some code here
-#endif
+#endif
\ No newline at end of file
```

#Expected Result

only the header being added, no other source code changes

**Comment by carmenbianca** [comment]
Hi @marcusmueller I will be able to review this issue after one or two weeks. Currently having a very hectic-but-good week :)

**Comment by carmenbianca** [comment]
Oh, by the way, can you send me an example header file? That would help a lot!

**Comment by marcusmueller** [comment]
@carmenbianca I can, but really, empty file, just a newline character, suffices to demonstrate the bug.

[newlineonlyheader.zip](https://github.com/fsfe/reuse-tool/files/4127233/newlineonlyheader.zip)

**Comment by mxmehl** [comment]
I can confirm that this really happens with every file, also the .license files do not seem to have a newline at the end.

**Comment by marcusmueller** [comment]
Thanks for this swift fix.
