### ISSUE TITLE
`reuse lint` does not identify full text agpl-3.0.txt file

### ISSUE THREAD

**Issue by fwolfst** [fsfe/reuse-tool#157]
Without knowing much about the `reuse` tool, I fired it up in a repository of mine in which the AGPLv3.0 is found in full text in a file `agpl-3.0.txt` (which I usually fetch via `wget https://www.gnu.org/licenses/agpl-3.0.txt` and then either symlink or move to `LICENSE`).

I find the output of `reuse lint` somewhat disturbing and amusing:
```
[...]
The following files have no licensing information:
* agpl-3.0.txt
[...]
```

Note that it won't "complain" about the file if moved to `LICENSE`.

**Comment by mxmehl** [comment]
Without having insight in your device tree, it seems to me that both location and name of the file are wrong.

Regarding the name, "AGPL-3.0" is a [deprecated SPDX ID](https://spdx.org/licenses/). It should either be "AGPL-3.0-or-later" or "AGPL-3.0-only". So the license text file should be called "AGPL-3.0-or-later.txt". Notice that we recommend the file name to be upper-case.

For the location, REUSE expects the license text files to be inside of the `LICENSES/` directory at the root level. So in your case it could be:

```
|– LICENSES/
|––– AGPL-3.0-ot-later.txt
|––– Apache-2.0.txt
|–src/
|––– agpl-licensed-file.py
|––– apache-licensed-file.py
```

**Comment by carmenbianca** [comment]
> Notice that we recommend the file name to be upper-case.

Not just recommend; it's necessary ;)

This isn't a bug, though, so closing.
