### ISSUE TITLE
Feature: make `reuse addheader` able to work on multiple files/directories (--recursive?)

### ISSUE THREAD

**Issue by fwolfst** [fsfe/reuse-tool#158]
In my (ruby on rails) code, I know that all code under  `app/` is mine and can be licensed and copyrighted accordingly. Ideally instead of writing bash loops or using a similar approach, `reuse addheader` would implement a `--recursive` option to add headers to all files under a given path, or allow for globbing (`reuse addheader "app/*.rb"` or even `reuse addheader "app/**/*rb"`).

**Comment by carmenbianca** [comment]
Hi @fwolfst 

> or allow for globbing (`reuse addheader "app/*.rb"` or even `reuse addheader "app/**/*rb"`).

You'll be delighted to know this is a feature of your shell :) If you do `reuse addheader "app/*.rb"`, the shell automagically expands it and the command becomes `reuse addheader "app/foo.rb" "app/bar.rb"`.

A recursive flag shouldn't be difficult to implement, though. @mxmehl Do you have any thoughts on whether `addheader` should have a recursive flag?

**Comment by fwolfst** [comment]
Yes thanks for pointing out. I know that and I tried it before (and that is
why I had put the glob-expressions in quotes, to prevent my shell doing
that).
Because - I don't know what happened, but reuse failed at me when provided
multiple files while I was doing my test. It works now, so although
delighted I am a bit confused :) - must have been a mistake on my part.

**Comment by carmenbianca** [comment]
> and that is why I had put the glob-expressions in quotes, to prevent my shell doing that

Ah, I always forget how that works.

Happy that it works now, though!

**Comment by mxmehl** [comment]
Great that it worked out in the end. I also just tested the glob without any quotes here, but it's probably a question of the used shell.

Regarding a --recursive flag, I'm split. On the one hand people can use globs and a combination with tools like `find` + `xargs`. On the other hand, it would reduce the threshold for adopters. But I don't see any strong contra against this option.

**Comment by davidag** [comment]
I wonder if it might be related to allowing directories as path arguments. How would `reuse addheader dir` behave in that case? Would it be recursive by default or perhaps when the `-r/--recursive` flag was used?

Even if constructions like `git ls-files dir | xargs reuse` or `find dir -exec reuse` are an option, allowing recursion and folders seems like an improvement to me.

**Comment by carmenbianca** [comment]
@davidag I'll look into this some time in the coming weeks. A bit low-priority but I agree that it'd be nice.

**Comment by neslihanturan** [comment]
Hi all, yesterday while I was trying to make my project REUSE-compliant, I was thinking the same that it would be nice to have a "-r" parameter. Even if this can be done with some bash tricks, still sounds like an improvement to me (especially when you have multiple different folders with different levels and different file extension in them). I am up to implement this feature if you all agree. In my opinion:

-  ```reuse addheader dir``` should say please either use -r parameter or give a path for a file not a directory.
- Likewise ```reuse -r addheader``` shouldn't assume cwd to be used. It should warn the user as please give a path for directory.
- ```reuse -r addheader a_file_path``` should be allowed, header for a single file can be added for sure. 
- ```reuse -r addheader a_directory_path another_directory_path``` should be allowed.

What do you think?

**Comment by nicorikken** [comment]
I am considering working on this for my own usability. It seems easy enough with [pathlib.glob](https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob) from the standard library. One thing to consider is ignoring magical directories like `.git`. Perhaps all private directories starting with a dot `.` should be ignored by default? Any reference material would be nice to get some ideas on best-practices for dealing with edge-cases. I did find [this](https://stackoverflow.com/a/68251099/12013233) StackOverflow post discussing the ignore-all-hidden-directories use-case. There might be better options for performance than globbing all files and then filtering it afterwards.

**Comment by nicorikken** [comment]
I've been experimenting a bit. Performance isn't so bad, so a general glob to get files would be good. It is worth considering that there are different approaches, options rather, for finding the actual files that need to be modified:

- All files in a certain directory (perhaps including symlinks and temporary files)
- All files excluding hidden directories (starting with a dot `.`)
- All files included in the Version Control System like `git ls-files` for Git

Trying it out locally, I had the unfortunate setup that I named my virtualenv directory `venv` rather than `.venv`, so it all got considered as a non-hidden file, resulting in hundreds of additional files.

**Comment by mxmehl** [comment]
Thanks for digging into this!

Don't we already have a command/function that lists all files that are to be considered for REUSE, especially for the lint? This should also be the "parent population" for this function IMHO, to avoid accidents like your venv. Only a few files must be left out: `/LICENSES/*` and `.reuse/*` come to mind.

Then, a parameter could be used to limit it to a specific directory, or another expression like `*.py` or so. Does that make sense?

**Comment by mxmehl** [comment]
Let's say a user enters the command `reuse addheader --recursive -c "me" -l "MIT" .`, but not all files in `.` are properly detected by reuse in terms of comment style.

I see a number of options here:
1. Collect all errors and print them after the run, but do not abort the run.
2. Call `--skip-unrecognised` automatically and just do not inform the user.
