### ISSUE TITLE
Enable Autotests for the Docker image

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#171]
See #167 for some background.

**Comment by carmenbianca** [comment]
@mxmehl Can I assign this to you? I don't have access to the admin panel on Docker Hub.

I envision that these steps needs to be translated to script:

- Use the image that has reuse installed.
- Change the working directory to the *source repository* of reuse-tool. The source repo is not in the image, so you'll probably need to copy it into the image somehow.
- `pip3 install -r requirements-dev.txt`.
- `py.test`.

**Comment by mxmehl** [comment]
Yes sure. Instead of using Docker Hub I'm rather thinking along the lines of creating a CI step in which the Dockerfile is built and then run against the own source.
