### ISSUE TITLE
Reuse 3.0 allows copyright notice to start with "Copyright" instead of "SPDX-FileCopyrightText" tag

### ISSUE THREAD

**Issue by DerAndere1** [fsfe/reuse-tool#174]
From Reuse 3.0:

> Instead of the SPDX-FileCopyrightText tag, the symbol ©, or the word Copyright MAY be used, in which case a colon is not needed.

This tool should cope with it and it should be mentioned in the README.

Currently the README says that only SPDX-FileCopyrightText tag is recognized

**Comment by mxmehl** [comment]
Thanks for the feedback.

> Currently the README says that only SPDX-FileCopyrightText tag is recognized

I cannot seem to find that we say this about the tool. Yes, the recommendation are that the SPDX tag is to be used, but the tool support all what's written in the spec.

Also, with #248, we also support adding comment headers with these formats.

I'll close this for now, but if you think this is still an issue (e.g. if I didn't find the problematic statement in the README), please feel to repoen.
