### ISSUE TITLE
KeyError exception while parsing 4-line shell script

### ISSUE THREAD

**Issue by pspacek** [fsfe/reuse-tool#179]
Steps to reproduce:
- create a shell script with following content:
```
#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
printf -- "--[[ Automatically generated file, do not modify by hand! ]]"
printf -- "-- SPDX-License-Identifier: GPL-3.0-or-later\n\n"
```
- run `reuse spdx -o reuse.spdx` in directory with the script
- error:
```
$ reuse spdx -o reuse.spdx
reuse._util - ERROR - Could not parse 'GPL-3.0-or-later\n\n"'
reuse.report - ERROR - Unexpected error occurred while parsing '/tmp/break/test.sh'
KeyError: 'path'
```

Purpose of the script is to generate new files so skipping SPDX tag is not an option (for this use-case).

**Comment by carmenbianca** [comment]
This is kind of unavoidable. I'm a little surprised that it aborts, though, which is definitely a bug that needs to be fixed.

A simple fix might be to do string concatenation. It's been a while since I last did shell script, but something like:

`printf -- "-- SPDX" + "-License-Identifier: GPL-3.0-or-later\n\n"`

or other.

**Comment by mxmehl** [comment]
The `+` isn't even necessary in bash, you could just do `printf -- "-- SPDX""-License-Identifier: GPL-3.0-or-later\n\n"`.

The below file would be REUSE compliant and understood by the tool:

```
#!/bin/bash
# SPDX-FileCopyrightText: Tester Testerson
# SPDX-License-Identifier: GPL-3.0-or-later
printf -- "--[[ Automatically generated file, do not modify by hand! ]]\n"
printf -- "-- SPDX""-FileCopyrightText: Tester Testerson\n"
printf -- "-- SPDX""-License-Identifier: GPL-3.0-or-later\n\n"
```
