### ISSUE TITLE
cc:license tags in SVG images are not recognized?

### ISSUE THREAD

**Issue by pspacek** [fsfe/reuse-tool#181]
Steps to reproduce:
- Create a minimal SVG image with license URL in `cc:license` tag:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xml:space="preserve"
   version="1.2"><metadata
   id="metadata691"><rdf:RDF><cc:Work
       rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type
         rdf:resource="http://purl.org/dc/dcmitype/StillImage" /><dc:title></dc:title><cc:license
         rdf:resource="https://github.com/spdx/license-list-data/blob/master/rdfxml/GPL-3.0-or-later.rdf" /></cc:Work></rdf:RDF></metadata>
</svg>
```

- Run reuse on it: `reuse spdx`
- Output does not have specified license:
```
FileName: ./url.svg
SPDXID: SPDXRef-8de195e6242088e801e0a75a6cbc6721
FileChecksum: SHA1: a55ad7c1d3feddd8c88b1a77a2ae0c4fd7afde4f
LicenseConcluded: NOASSERTION
FileCopyrightText: NONE
```

**Comment by mxmehl** [comment]
Well, the specification supports either the "traditional" Copyright lines or SPDX-FileCopyrightText. What SVG does here with xmlns:cc is specific to their format.

I don't see how REUSE can support meta fields of all kinds of formats, e.g. audio or image files, which are also more likely to be misunderstood, overwritten by other tools etc.

@carmenbianca @silverhook, what do you think?

**Comment by silverhook** [comment]
I would also say that CC-specific metadata in SVG is both too license- and metadata/filetype-specific and therefore outside the scope of the REUSE Spec.

Already if we just tried to support all kinds of metadata this would be a herculean undertaking, but here we are also talking about CC-specific RDF tags.

A CC RDF to REUSE converter might be interesting as a helper tool though.
