### ISSUE TITLE
addheader requires manual typing of `SPDX-FileCopyrightText`

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#188]
This is not very preferable. It should be SPDX-by-default. Add a flag instead that prevents the tool from adding the SPDX tag.

**Comment by mxmehl** [comment]
For completeness: addheader does not require me to define the tag here:

```
$ reuse addheader --copyright "Free Software Foundation Europe <https://fsfe.org/contact>" --license "GPL-3.0-or-later" --style="python" bla.txt
$ cat bla.txt
# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe <https://fsfe.org/contact>
#
# SPDX-License-Identifier: GPL-3.0-or-later⏎
```

**Comment by carmenbianca** [comment]
I think I found the culprit.

```
$ touch bla.py                                                                                                                                 
$ reuse addheader --copyright "© Free Software Foundation Europe" bla.py                                                                       
Successfully changed header of bla.py
$ cat bla.py                                                                                                                                   
# © Free Software Foundation Europe
```

Implicit behaviour. No idea why I wrote it that way. This isn't very desireable.

**Comment by carmenbianca** [comment]
Additionally: Even weirder, it didn't put the date anywhere in there.

**Comment by nicorikken** [comment]
So if I understand it correctly it fails for cases where there is a copyright sign, as it is treated as something that shouldn't be changed into SPDX? In that case the creation of a copyright header should operate differently on an existing header and when invoked using the `addheader` command. Right?

**Comment by carmenbianca** [comment]
I think this was fixed at some point.
