### ISSUE TITLE
addheader should recognise file extensions that *require* .license files

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#189]
e.g., .json.

**Comment by nicorikken** [comment]
What would be a neat way to achieve this? Can there be a similar map like `EXTENSION_COMMENT_STYLE_MAP` in `src/reuse_comment.py` to check against? I notice that currently `.sqlite` and `.whl` files are already handled in a different way, but I'm not able to find out how that works.

**Comment by mxmehl** [comment]
Regarding your last question, this happens via `is_binary` from the `binaryornot.check` module.

I am not sure whether we would come around adding file extensions manually. I am not aware of a list for such files.

**Comment by nicorikken** [comment]
Alright, looking at the code, it makes sense to have an additional comment style which equates to `NoCommentStyle` possible. This can be the result of `_get_comment_style(path)`, as is being called in `_add_header_to_file()` in `header.py`. So following the execution flow of `run()` in `header.py` first the binary files are handled differently, and then plaintext files are handled. And in the process of plaintext files the `NoCommentStyle` files are then dealt with. Similar to the shortcut in `run()` in `header.py` the `path` variable can be replaced to represent the `<filename>.license` path, and the execution can then be followed. In this case the style also has to be changed to an `EmptyCommentStyle` so the correct details are added in the new `.license` file.

I hope my worded PR is clear enough :smile:  Either way I now have an idea how to implement this.

**Comment by mxmehl** [comment]
A better Python programmer than I am would probably understand this better, but I think I can follow your argumentation well enough, thanks :)

**Comment by mxmehl** [comment]
Closed with #298, thanks @oxzi!
