### ISSUE TITLE
[Question]How to import reuse from python script and use reuse lint?

### ISSUE THREAD

**Issue by soimsoim** [fsfe/reuse-tool#190]
How to import reuse from python script and use reuse lint?

After importing reuse from a Python script, the main function cannot be called.
Is there a way to run reuse lint other than by creating a separate process and calling it from the command line?

**Comment by soimsoim** [comment]
Oh I found the way to call reuse lint on files in test directory. 
This question has been resolved and I will close this issue.

Thank you.

**Comment by carmenbianca** [comment]
This could maybe help you out:

```python
from reuse import _main, lint, report, project

proj = project.Project("path/to/project")

# Option 1
lint.run([list, of, args, here], proj, out=sys.stdout)

# Option 2
_main.main(["lint", list, of, args, here], out.sys.stdout)

# Option 3
report = report.ProjectReport.generate(proj)
# ... and then do manual inspection. This gives the most programming access.
```

Mind that the programming API is *totally unstable*, and a new version of reuse could contain breaking changes. If you want to do it totally reliably, try this:

```python
import subprocess

output = subprocess.run(["reuse", "lint", list, of, args, here])
# ... and inspect the output here.
```

Read <https://docs.python.org/3/library/subprocess.html> to learn how `subprocess` works.
