### ISSUE TITLE
OFL-1.1-RFN claimed "bad license"

### ISSUE THREAD

**Issue by rpavlik** [fsfe/reuse-tool#194]
This is the SIL OFL version 1.1 with a "reserved font name", the license for the ["Source Code Pro" font](https://github.com/adobe-fonts/source-code-pro). It's on the SPDX list https://spdx.org/licenses/ but when I added a `.license` file corresponding to the Source Code Pro OTF file, `reuse lint` warns "* Bad licenses: OFL-1.1-RFN"

**Comment by carmenbianca** [comment]
This should be fixed since 0a15fa2f3af923a89ec55bd967b80e11ff541f77

Thanks for reporting!
