### ISSUE TITLE
Create a GitHub action from reuse

### ISSUE THREAD

**Issue by jeremiah** [fsfe/reuse-tool#199]
I've looked for a SPDX GitHub action: https://github.com/marketplace?type=actions&query=spdx
But not found one. I'm thinking of creating one but I think that reuse might be closer.

**Comment by carmenbianca** [comment]
@mxmehl I believe that you were on this not very long ago.

**Comment by jeremiah** [comment]
FWIW I've tried one there that gave a ton of false positives and quickly looked at the code of another action written in JS that looked suboptimal. GitHub actions are just code run in a container at GitHub and I think reuse should fit perfectly in that scenario. Crafting the YAML file for the action to work right is a little fussy but far from impossible. I'm happy to send a patch with a first attempt or so if interested but don't want to interfere if the work is already under way.

**Comment by mxmehl** [comment]
@jeremiah I've created a beta action here: https://github.com/marketplace/actions/reuse-compliance-check

There are a few issues that would require some attention before releasing it officially, but AFAIK the behaviour/reporting should be identical to a local install of the REUSE tool.

**Comment by jeremiah** [comment]
Awesome - I'll test.

**Comment by jeremiah** [comment]
I think we can close this. (I would close it myself but I don't know your policy.)

**Comment by carmenbianca** [comment]
Let's keep the issue open until the action is out of beta :)

**Comment by mxmehl** [comment]
Good to know that it worked fine for you!

I think we can move the action out of beta as soon as we've figured out whether and how to support (multiple) arguments to a subcommand. This could be a breaking change that we want to avoid.

**Comment by mxmehl** [comment]
The action is out of beta and actually used in quite some projects already. So I'll close this :)
