### ISSUE TITLE
Ignore relative symlinks contained inside the repo

### ISSUE THREAD

**Issue by amerlyq** [fsfe/reuse-tool#202]
External file license is useful for binary files (because there is no way to add header to them) and auto-generated config files which strip-out any added comments (like linux-kernel "make savedefconfig").
In the latter case it's often useful to have relative symlink to default config to achive explicit transparecy inside project.
But it requires symlinking both file and its license for `reuse lint` to ignore that file.
Example:
```bash
mkdir relsymlink
cd relsymlink
git init
touch blob
reuse addheader -c user -l GPL-3.0-only --explicit-license -- ./blob
reuse download GPL-3.0-only
reuse lint  #1
ln -srT blob symlink
reuse lint  #2
ln -srT blob.license symlink.license
reuse lint  #3
```
In the case `#2` above license of `symlink` file won't be found.
And for `#3` to work you must symlink license to every place you symlinked the config (yes, it's rare but I already had necessity to do it thrice in last 6 months).

Possible solutions (limited only to relative symlinks fully contained inside the repo):
1) dereference symlink and require to have .license file only beside the original file.
2) (better) ignore all relative symlins (because they aren't subject to licensing anyway, and their original file will be checked for license anyway.

**Comment by mxmehl** [comment]
Since symlinks could be rather understood as text files just containing a file path, I guess it could be ignored by REUSE. On the other hand, REUSE mandates to provide copyright/licensing information for *every* file, including the most irrelevant ones.

Not sure how symlinks would interact with this principle.

**Comment by carmenbianca** [comment]
Ignoring symlinks is probably fine.

**Comment by amerlyq** [comment]
I'm sure copyright and licensing laws can't be applied to symlinks at all.
There is no intellectual property to defend. So I don't see the point of
being pedantic to the bones on this matter.

Especially when enforcing it has the significant limiting drawback of
preventing people using symlinks inside their repo at all and creating ugly
workarounds on their place only to be pedantically compliant at all costs.

**Comment by silverhook** [comment]
I would agree that symlinks, similarly as zero-size files (see https://github.com/fsfe/reuse-tool/issues/208#issuecomment-630220745) are safe to be ignored by the tool and spec.
