### ISSUE TITLE
Separate license for repo file structure

### ISSUE THREAD

**Issue by amerlyq** [fsfe/reuse-tool#206]
### Problem
Using license per each file is not enough.
We may need *one more* license bound to the project itself instead of any other file -- to protect (or liberate) project composition.

### Background
Result of concious selection for the set of files is also intellectual property by itself.

Resulting collection of GPL files (e.g. one-file header libraries) may still be distributed under MIT to acknowledge collector and allow private proprietary modifications to the set of libraries (but not libraries themself).

And vise versa -- you may distribute MIT/CC0 libs in repo under GPL as whole collection to enforce contribution to the collection, despite allowing free copy and edit the individual files for everyone.

### Precendents:
* Database has separate licenses for its *schema* and its *data* (e.g. scientific data measured and analyzed by different groups).
* Collections of songs/etc. are acknowledged as separate IP (e.g. Top-100 best hits of 1960-1970).
* Filesystem is database by itself

Before `reuse-tool` problem didn't exist, because file LICENSE or COPYING inside the repo root signified default license to be used for everything w/o explicit license in header.
And now it was obliterated.

### Proposed Solutions
* add some explicit field for repo-structure license into `.reuse5/` dir (BUT: it has bad visibility for users)
* treat LICENSE in the root of repo as license only for repo structure (BUT: confusing for everybody living long enough in the FOSS world)
* make-up some new filename like `{DEFAULT,REPO,STRUCTURE}.license` to be explicit and novel (BUT: conflicting extension `.license` with current `reuse-tool` usage -- requires for file `DEFAULT` to be present) 
* create new `LICENSES/{DEFAULT,REPO,STRUCT}` identifier or symlink which can be used in this case (BUT: not the best visibility; NICE: special managed location and prevents littering project root by more files)
* BAD: every solution above is a bad compromise -- must think out of the box to find elegant solution. Need more opinions and options.

**Comment by carmenbianca** [comment]
@silverhook Would you be able to take a look at this issue at your own convenience?

**Comment by silverhook** [comment]
I see no reason why to include license info specific for the codebase’s file structure/layout.

It is true than in US copyright they have a test called [Structure, Sequence and Organisation](https://en.wikipedia.org/wiki/Structure,_sequence_and_organization), but that is used to compare two codebases, not as a test if something is copyrighable. I know of no case law where the mere layout of a program would be deemed copyrightable, nor can I see theory backing that up.

Unless you can provide some evidence, I consider this as a non-bug.
