### ISSUE TITLE
reuse 0.8.1 can't download licenses

### ISSUE THREAD

**Issue by jeremiah** [fsfe/reuse-tool#207]
Version 0.8.1 of reuse-tool fails when I issue this command;

```reuse download --all```

Instead of downloading all licenses it found it issues these messages;

```
Error: Failed to download license. Is your internet connection working?
Successfully downloaded LICENSES/CC-BY-4.0.txt.
```

Given that the second license in the message above was successfully downloaded (the CC-BY-4.0 license), perhaps the error message should be changed? 

Also, digging a little more shows that the license at issue (GPL-3.0) is deprecated in SPDX v3.0 (https://spdx.org/licenses/GPL-3.0). This means that when reuse-tool went to download the GPL 3.0 license, it couldn't find it and issued the spurious message about a broken internet. I assume these issues will be solved for free when the reuse-tool moves to SPDX 3.0.

**Comment by carmenbianca** [comment]
Hi Jeremiah, I think you made a mistake with the formatting. I can't see the error.

**Comment by Flameeyes** [comment]
Possibly #186? (If it was one of the aliases ending in `+`)?

**Comment by jeremiah** [comment]
> Hi Jeremiah, I think you made a mistake with the formatting. I can't see the error.

Let me fix that, the formatting of my issue is terrible.

**Comment by jeremiah** [comment]
> Possibly #186? (If it was one of the aliases ending in `+`)?

I think so! Thanks, I'll consolidate the two.
