### ISSUE TITLE
0-sized files

### ISSUE THREAD

**Issue by Flameeyes** [fsfe/reuse-tool#208]
Hi folks, it seems like `reuse` is expecting copyright information for 0-sized files. These are intentionally-left-blank files that are used for instance in Python to declare packages and to declare them as "typed". They are, by definition, empty, and thus I guess they fall into the [non-copyrightable](https://reuse.software/faq/#what-is-copyrightable) definition.

While it _could_ be possible to provide them with CC-0 licenses, some of the tools expect them _stay_ 0-sized (namely, `__init__.py` files are treated differently if they are not 0-sized). So the alternative would be adding the `.license` files for all of them, but… well it sounds a bit counterproductive.

Maybe having a simple automatic ignore of 0-sized files would be suitable and within the purpose of the tool?

**Comment by mxmehl** [comment]
Perhaps related to #202 which is also about files that are only relevant for technical purposes and do not contain "relevant" information. I start to think about whether this becomes relevant enough to be mentioned in the spec.

@carmenbianca @silverhook, WDYT?

**Comment by carmenbianca** [comment]
> (namely, __init__.py files are treated differently if they are not 0-sized)

I am not sure if this holds. At least, I don't know of any differences—you can just put a header in those files.

Same with ordinarily empty files such as `.gitkeep`.

But I'll concede that it's kind of weird to put headers in 0-sized files. I don't see a compelling reason not to implement a skip for 0-sized files. But same as with #202, that would *probably* merit a slight update to the spec. It's the reason I haven't merged #205 yet.

And at that point: Is it worth adding complexity to the spec for these two edge cases? I don't know.

**Comment by Flameeyes** [comment]
> And at that point: Is it worth adding complexity to the spec for these two edge cases? I don't know.

Let me provide an outside view: tools are only useful if they don't cause extra busywork. Is it worth to adopt a tool adding complexity (the `.license` file¹) where it provides no positive outcome? My impression is that for the sake of adoption, it would be worth to amend the spec.

¹ It's a minor complexity _in the repository_ but when it comes to distribution it really isn't that minor. Take a `make dist` managed autotools project: if you care enough about licensing to use the tool, you care enough to make sure that those files are correctly packaged. And that means having to make sure they are included in the final tarball.

**Comment by carmenbianca** [comment]
@Flameeyes Makes sense!

@silverhook I would love your input on this.

**Comment by silverhook** [comment]
Hmmm, the content of a zero-size file is obviously not copyrightable, as there is none (there might be some corner cases where you wrote a haiku in the filename, but let’s ignore that)

If there is *any* file that could safely be ignored by the tool, a zero-size would be it. Similarly with symlinks (as in #202 )
