### ISSUE TITLE
addheader --style c is more C++ style (or C99)

### ISSUE THREAD

**Issue by Flameeyes** [fsfe/reuse-tool#209]
This is minor for most people _but_ some projects still support per-C99 compilers that don't allow `//` comments (or that warn on them).

I would suggest renaming the style to `c++` at the very least.

**Comment by carmenbianca** [comment]
I'd been meaning to implement a `--multi-line` and a `--single-line` flag that would allow the user to explicitly choose between `/* */` and `//` (and other such things). I'll use this issue to track that.
