### ISSUE TITLE
`addheader --style python` can remove important directives from comment header if "blocked" with other SPDX directives

### ISSUE THREAD

**Issue by Flameeyes** [fsfe/reuse-tool#211]
I noticed this while trying to use the tool on [cython-sgio](https://github.com/python-scsi/cython-sgio).

The `.pyx` file has a first line directive that is important for the processing of the file, and then followed with the existing SPDX headers:

```
# cython: language_level=3
#
# SPDX-FileCopyrightText: © 2014 The cython-sgio Authors
# SPDX-License-Identifier: LGPL-2.1+
```

When running `reuse addheader --copyright 'The cython-sgio Authors' --year 2020 --license LGPL-2.1-or-later src/linux_sgio.pyx` the result is quite a bit confusing (not least because the previous lines were not updated, even though the LGPL-2.1+ is a deprecated alias):

```
# SPDX-FileCopyrightText: 2020 The cython-sgio Authors
# SPDX-FileCopyrightText: © 2014 The cython-sgio Authors
#
# SPDX-License-Identifier: LGPL-2.1+
# SPDX-License-Identifier: LGPL-2.1-or-later
```

The duplicate SPDX lines are understandable, it's not like the tool can understand this semantics in this case, but the deletion of `cython:` directives is a real problem.

Note that if there is no license information on the file at all, the comment gets pushed _below_ the SPDX lines — and I'm not sure if that's meant to work with Cython.

**Comment by carmenbianca** [comment]
Apologies for the late response on this. I've been idly pondering this, and I'm not really sure what an appropriate solution here is.

The tool already recognises shebangs (`#!/path/to/executable`) and tries to preserve those at the tops of files. I could try to expand that functionality and introduce more of those types of things. For instance, many Python files have this on the first or second line:

```python
# -*- coding: utf-8 -*-
```

This is not preserved. The same syntax is also used by Emacs.

Vim uses this:

```python
# vim:fileencoding=utf-8
```

which is also not preserved.

Problem is, I don't really want to spend my time chasing down these non-comment comments. It's possible, of course, but it's a lot of effort and introduces a good bit of complexity.

A simple workaround is to use `addheader`'s templating. For instance, this template would work for the given example:

```jinja
# cython: language_level=3
# 
{% for copyright_line in copyright_lines %}
# {{ copyright_line }}
{% endfor %}
#
{% for expression in spdx_expressions %}
# SPDX-License-Identifier: {{ expression }}
{% endfor %}
```

Of course, this is a workaround that puts some burden on the user. In an ideal world, computers would automagically handle all of the boring stuff, but :ok_person:

I hope that helps. I'm going to close wontfix, unless there's a better workaround that can be implemented tool-side.

**Comment by Flameeyes** [comment]
I have not spent much time to look how the deletion of the comment works right now. But the best guess I would have at first is erring on the side of not removing comments if it's not understood?

I understand removing the license header -- but that's only if the license header is matched. Why removing anything else at all? (Maybe I'm missing something obvious here.)

**Comment by carmenbianca** [comment]
Ah, `addheader` currently works by replacing the header entirely. There is a simple reason for this, which is that I simply don't know how to deal with selectively replacing parts of the header. Example:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright © 2020 Carmen Bianca Bakker
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
```

I'm not really sure what `reuse addheader` is supposed to do when run on this file. Intuitively it makes sense that licenses be added at the bottom—near the existing tag—and copyright statements be added in the middle—near the copyright statement. But that's human intelligence, not artificial intelligence 1.0.

You can also imagine a scenario in which there is no `SPDX-License-Identifier` yet, and the program has to figure out somewhere to put it. And you can probably imagine some more complex scenarios—`SPDX-License-Identifier` tags scattered all over the header.

Because I didn't want to deal with that complexity, it just harvests the header for the tags, and replaces it completely.
