### ISSUE TITLE
Feature Request: run as pre-commit integration

### ISSUE THREAD

**Issue by Flameeyes** [fsfe/reuse-tool#212]
[pre-commit](https://pre-commit.com/) would be a very good way to make sure that all files (particularly, new files) in the repository are given a license. In particular it would reduce the risk that an explicit `.license` file is created locally (`reuse lint` passes) but not added to the right commit.

**Comment by mxmehl** [comment]
I agree, that's a good mechanism. Do you think that adding this to https://reuse.software/dev, where we list integration possibilities, would suffice?
