### ISSUE TITLE
Dep5 should use OS-independent dir separators

### ISSUE THREAD

**Issue by grv87** [fsfe/reuse-tool#22]
Given `.reuse/dep5` file
```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

Files: gradle/*.lockfile
Copyright: ©  Basil Peace
License: Apache-2.0
```
`reuse lint` (`master` branch) correctly recognizes license on `gradle/main.lockfile` file under Debian, but not under Windows.
Under Windows this works:
```
Files: gradle\\*.lockfile
```
which is somewhat strange.
Format should be OS-independent otherwise cross-platform development and build is not feasible.

**Comment by carmenbianca** [comment]
That is somewhat strange. It's an upstream bug/feature in `python-debian`, though. The tool isn't really supported under Windows because I don't have a single Windows machine, but this should be trivially easy to fix upstream. Will look at it in a minute.
