### ISSUE TITLE
Vendored subtrees and lint

### ISSUE THREAD

**Issue by lukegb** [fsfe/reuse-tool#236]
I have some repos vendored - notably NixOS/nixpkgs, which happens to include a patch to the Linux kernel where the context includes the SPDX license identifier: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/randstruct-provide-seed.patch

This is unfortunate, because it means that the entire file is parsed as being licensed under GPL-2.0 (which is a deprecated license identifier for GPL-2.0-only, so fails lint).

Given that this is a vendored subtree, I can't easily manually add a .license file alongside it, but also my dep5 definition doesn't override the "explicit" license definition there.

Since this is a Mercurial repo, I've worked around this by just touching .git as a file inside the vendored paths to force `reuse lint` to ignore it by treating it as a submodule instead, but this is a bit of a hack.

What _should_ I be doing here? There's understandably deliberately no ignore machinery in reuse.

**Comment by mxmehl** [comment]
Does it work if you add a .license file for this file? We discussed the order of precedence in #229 where we drafted `.license > dep5 > file content`. However, AFAIK @carmenbianca did not have time to implement that yet properly.

**Comment by mxmehl** [comment]
I'll close this in favour of fsfe/reuse-docs#70 where we work on defining the precendence of REUSE information. As the spec changes, it will be worked in the helper tool at the same time.
