### ISSUE TITLE
Please allow to create debian/copyright files

### ISSUE THREAD

**Issue by agx** [fsfe/reuse-tool#244]
It seems reuse has all the knowledge to create `debian/copright` (https://dep-team.pages.debian.net/deps/dep5/) - it would be great if reuse-tool would support generating these.

**Comment by mxmehl** [comment]
I am not sure whether reuse-tool is the best place to do that.

Background: we strive to soft-deprecate the DEP5 format to get rid of some dependencies, and replace it with our own YAML file (see REUSE mailing list if you're interested).

So while the tool might know the tricks now, it can be different in a few months already. So I think a separate, lightweight tool might be more handy, e.g. to convert a SPDX bill of materials (`reuse spdx`) to a DEP5 file. What do you think?

**Comment by stephanlachnit** [comment]
> > So since I have to write a converter tool anyway, maybe we can combine our efforts? I.e. a tool that can convert DEP5->REUSE.yaml, SPDX->DEP5, and DEP5->SPDX (by interfacing with the reuse tool). This tool could be optionally loaded by the reuse tool so that there is no hard dependency on python-debian anymore.
> 
> Sure, that sounds feasible. Ideally this could be a light library that multiple projects could use, e.g. REUSE as well as specific tools for Debian.

Yes, I would design it as a Python library with an additional cli tool. I'll let you know when I get started.

**Comment by stephanlachnit** [comment]
@mxmehl FYI I will upload the code here: https://github.com/stephanlachnit/dep5convert (no real code has landed yet, it's just a Python template)

**Comment by stephanlachnit** [comment]
Alright I see, it's probably better to write it from scratch then. I'll happily look at @floriansnow's code. I'm working on parsing and writing DEP5 files right now (the code is [here](https://github.com/stephanlachnit/dep5convert/tree/main/src/dep5convert/dep5_tools), but can't do anything yet).
