### ISSUE TITLE
What is the minimal required Python version?

### ISSUE THREAD

**Issue by dominiksalvet** [fsfe/reuse-tool#25]
The question is clear. What is the minimal required Python version? [README.rst](https://github.com/fsfe/reuse-tool/blob/master/README.rst) states 3.6 whereas [pypi](https://pypi.org/project/fsfe-reuse/) as well as its badge states 3.5.

From [my experience](https://github.com/dominiksalvet/gim/blob/master/.travis.yml), it seems that REUSE works under Python 3.5.2 (Travis CI using Xenial image).

**Comment by carmenbianca** [comment]
Apologies for late response. The minimal version of Python is 3.6 for the master branch, 3.5 for the version on PyPI. The master branch should very soon be on PyPI.
