### ISSUE TITLE
reuse lint encounters parse error when parsing a template

### ISSUE THREAD

**Issue by mdolling-gfz** [fsfe/reuse-tool#250]
I have a project, where I use the following code block

```python
{% for copyright_line in copyright_lines %}
{{ copyright_line }}
{% endfor %}

{% for expression in spdx_expressions %}
SPDX-License-Identifier: {{ expression }}
{% endfor %}
```

in a markdown file.

the linter fails with the following message:
```
reuse._util - ERROR - Could not parse '{{ expression'
reuse.report - ERROR - Unexpected error occurred while parsing '/repo/docs/pages/templates.md'
```

Proposed solution:
Escape documentation files (md, rst, txt) like the jinja2 templates itself.

**Comment by mxmehl** [comment]
>  Escape documentation files (md, rst, txt) like the jinja2 templates itself.

I am afraid we cannot do that. The idea is that all files have somehow copyright and licensing declared, and these files can definitely contain relevant content.

I think a better solution would again be to have an option to "overwrite" license/copyright with a .license file to avoid that the tool chokes on seemingly malformed tags, so basically #246.

And intermediary solution could be to somehow split `SPDX-License-Identifier`, e.g. by concatenating two strings.
