### ISSUE TITLE
Order of matching in dep5 file

### ISSUE THREAD

**Issue by oddhack** [fsfe/reuse-tool#252]
I'm trying to express the case where most images are licensed under one regime and there are some exceptions, but confused by the way in which the reuse tool seems to be processing the dep5 file. If I have something like this:

```
Files: tests/srcimages/kodim17.png
Copyright: Eastman Kodak Company
License: LicenseRef-Kodak

Files: */*.png
Copyright: 2015-2020 The Khronos Group Inc.
License: Apache-2.0
```

then 'reuse spdx' identifies the kodim17.png file as having the Khronos information, rather than the Kodak information specific to that file. Is the order in which dep5 is processed well-defined, and/or is there another way to express this exception to the general rule? N.b. we're not eager to use .license files as that would create immense clutter.

**Comment by oddhack** [comment]
So I've been experimenting with dep5. It appears what's going on is that whatever the *last* match in dep5 to a file is, that's what will be used to determine the license. Is that correct, and intentional? It seems nonintuitive to match an entry in dep5, but keep reading dep5 and also match a later entry, which is the one chosen.

**Comment by robinkrahl** [comment]
This is correct according to the [dep5 specification](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#files-field) (section 6.9: Files):

> Multiple Files paragraphs are allowed. The last paragraph that matches a particular file applies to it. More general paragraphs should therefore be given first, followed by more specific overrides.

**Comment by mxmehl** [comment]
Since we follow DEP5 here, that's indeed the expected behaviour, albeit perhaps not the most intuitive.

We plan to soft-deprecate DEP5 anyway soon, and will discuss the sorting then again.
