### ISSUE TITLE
Create an example how to include REUSE in CI

### ISSUE THREAD

**Issue by dominiksalvet** [fsfe/reuse-tool#26]
It would be great to create an example demonstrating how to use REUSE in a custom Git repository as a part of its continuous integration practice (e.g., Travis CI).

Recently I have spent a lot of time on including REUSE into CI used in [gim](https://github.com/dominiksalvet/gim) repository. The main problem was with setting up required Python version together with `language: shell` in *.travis.yml*, which seems impossible.

Well, I have ended up with Python version 3.5.2 (see also #25) and it looks like it is working but I am still afraid of that older Python version. Don't you know how to change Python version in Travis CI while using `language: shell` and not `language: python` by any chance? `python: <version>` doesn't work in that case.

**Comment by mxmehl** [comment]
Absolutely, that's on our to-do list! Thanks for highlighting it here.

We have created a very simple Docker container which runs the latest released reuse version (0.3.4): [fsfe/reuse](https://hub.docker.com/r/fsfe/reuse). It's not well documented as this as been a test case for ourselves so far. The Dockerfile is [here](https://github.com/fsfe/reuse-tool/blob/feature/dockerfile/Dockerfile).

There is also a case where we included it into a Drone CI/CD process: [reuse/simple-hello](https://git.fsfe.org/reuse/simple-hello/src/branch/master/.drone.yml). The research and documentation on how to realise this with other systems is yet to be done.

I hope this helps you until we finished our tests and polished documentation.

**Comment by dominiksalvet** [comment]
@mxmehl Ok, I am fine with the answer, you can close this issue if you want. I will be waiting for official CI guides... x))

**Comment by arcturus140** [comment]
How does the continues integration test work? From what I can see it only calls `reuse lint`. Is a simple evaluation possible based on exit code?

I tried the following:
```
if reuse lint ; then
	echo "REUSE compliant"
else
	echo "not REUSE compliant"
fi
```

I am not sure about exit codes or return values from the application.

**Comment by mxmehl** [comment]
Yes, exactly. The error code with the latest stable release (0.3.4) is the number of uncompliant files. @carmenbianca may tell us whether this is also the case with current master.

Exit code 0 means that everything is fine (but perhaps with some warnings or information, not sure how they influence the exit code), so you should be able to make such a simple condition as you suggested.

**Comment by carmenbianca** [comment]
0.3.4 returns 0 if everything is good, and ≥1 if there are errors (specifically, the number of erroneous files). This wasn't very human-friendly, though, so the master branch prints out a more verbose, human-friendly summary. The return code is 0 if everything is good, and 1 if something isn't right.

```
if reuse lint ; then
	echo "REUSE compliant"
else
	echo "not REUSE compliant"
fi
```

You don't typically need to do this. You just tell your CI to run `reuse lint`, and it will detect by itself whether the command succeeded (return code 0) or failed (non-zero).

That's how GitLab CI works, anyway:

https://github.com/fsfe/reuse-tool/blob/master/.gitlab-ci.yml
https://gitlab.com/carmenbianca/reuse-tool/pipelines

**Comment by mxmehl** [comment]
https://reuse.software/dev/ now contains guides for Travis, GitLab and Drone. Spoiler: it's amazingly simple!
