### ISSUE TITLE
sub command to display copyright and license info for files

### ISSUE THREAD

**Issue by misappi** [fsfe/reuse-tool#263]
For repos with a lot of 3rd-party stuff and a complex dep5 file (for example, you might have defined copyright and license info for an entire folder tree, but defined exceptions for sub folders/files etc etc.), it is often not that easy to check which copyright and license really was assigned to a specific file and if this assignment is correct. OK, you could generate the SPDX file and have a look into that, but for complex projects the file can become quite large and thus it's cumbersome to get the desired info out of it. 
Therefore, it would be great if there could be a sub command that displays copyright and license information for a single file (or a list of files) - something like `reuse show <file>`.

**Comment by mxmehl** [comment]
Good idea indeed! We had a very similar discussion in #256, and a PR already started in #258. I'd close as duplicate and would love to hear your feedback on these two issues/pulls, but please feel free to reopen if I misunderstood your point.
