### ISSUE TITLE
Add hint to the installation PATH to REUSE tool for MS Windows installations

### ISSUE THREAD

**Issue by BG-dC** [fsfe/reuse-tool#265]
Hi, 
I'd suggest to change the phrase in the readme.md:
  After this, make sure that ~/.local/bin is in your $PATH.
should be replaced by
  After this, make sure that ~/.local/bin is in your $PATH (Linux), for Windows make sure the environment variable contains %USERPROFILE%\AppData\Roaming\Python\Python39\Scripts

I had installed phython at C:\programs\python_3.9 and spent quite some time to search for the reuse tool. 

Best Regards,
Bernd

**Comment by mxmehl** [comment]
Since I cannot reproduce this, I worded it a bit vague, but it should provide the necessary hint for Windows users anyway.

Thanks for the report!
