### ISSUE TITLE
Read error with foreign copyright holder

### ISSUE THREAD

**Issue by marcoXbresciani** [fsfe/reuse-tool#269]
If I add

Files: html/fonts/Lato*
Copyright: 2010 Łukasz Dziedzic (<dziedzic@typoland.com>)
License: OFL-1.1

to my project dep5 file, reuse crashes for each file of the project saying

Could not read 'FILENAME_HERE'
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1139: character maps to <undefined>

and writes this error for each file.
Character in position 1139 is the Ł of Łukasz in the dep5 file.

Reuse crashes even with these lines commented.

Removing the lines, reuse works, but the project can't be compliant due to missing licenses for those font Lato* files.

**Comment by rscohn2** [comment]
Can you attach the dep5 file to this issue?

**Comment by marcoXbresciani** [comment]
It has just stopped doing it... simply having lunch has solved the bug.

(Really, I'm just astonished: I've copy-pasted again that lines... but now it work.)

**Comment by marcoXbresciani** [comment]
No, actually I also restarted IntelliJ (I was using its terminal to launch `reuse lint`... And all other strange issues that I saw just disappeared.
Sorry for the bother.
