### ISSUE TITLE
Lint does not recognize rep5 content when files can't be parsed

### ISSUE THREAD

**Issue by marcoXbresciani** [fsfe/reuse-tool#270]
See the current head of my project at [http://hg.savannah.nongnu.org/hgweb/wwwjdic/file/tip](http://hg.savannah.nongnu.org/hgweb/wwwjdic/file/tip).

Running `reuse lint` seems that even if those "unparseable" files (that are automatically generated, I can't solve the parsing issue) are specifically listed in the `dep5` file, the project is no REUSE compliant.

```
Could not parse 'GPL-3.0-or-later #++</p>'
Could not parse 'FSFAP</p>'
Could not parse 'FSFAP</pre>'
reuse.report - ERROR - Unexpected error occurred while parsing 'html\Gemfile.html'
KeyError: 'path'
reuse.report - ERROR - Unexpected error occurred while parsing 'html\Rakefile.html'
KeyError: 'path'
reuse.report - ERROR - Unexpected error occurred while parsing 'html\WWWJDic.html'
KeyError: 'path'
# READ ERRORS

Could not read:
* html\WWWJDic.html
* html\Rakefile.html
* html\Gemfile.html


# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: BSD-3-Clause, CC-BY-2.5, FSFAP, GFDL-1.3-or-later, GPL-3.0-or-later, OFL-1.1
* Read errors: 3
* Files with copyright information: 132 / 132
* Files with license information: 132 / 132

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

Might be associated to #246 .

**Comment by mxmehl** [comment]
Yes, that's the case. In these files, it seemingly finds license/copyright info, but cannot parse the format. See [here](http://hg.savannah.nongnu.org/hgweb/wwwjdic/file/b9e5168f1929/html/Rakefile.html#l86( for example.

Indeed, #246 and the question of overriding certain files (fsfe/reuse-docs#70) is a key to that, so I'd like to close this as a duplicate. Please reopen if you think that's not the case.

Sorry for this bug, I hope we can fix it soon.

**Comment by mxmehl** [comment]
Ah, as a temporary solution: you can try to split these strings. E.g. it could work in HTML to do this:

`SPDX-<span></span>License-Identifier: GPL-3.0-or-later`

Ugly, but we use a similar technique for this very project.

**Comment by marcoXbresciani** [comment]
> Ah, as a temporary solution: you can try to split these strings. E.g. it could work in HTML to do this:
> 
> `SPDX-<span></span>License-Identifier: GPL-3.0-or-later`
> 
> Ugly, but we use a similar technique for this very project.

Thanks. Unfortunately I can't, because the HTML files are automagically generated via `ruby rdoc` command.
Anyway I've found that all ruby files having this header below, failed.
  I'ved simply removed the SPDX license from them and added to dep5.

```ruby
#--
# wwwjdic
# © 2014 Marco Bresciani
#
# This file is part of wwwjdic.
#
# wwwjdic is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# wwwjdic is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with wwwjdic. If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-FileCopyrightText: 2014 Marco Bresciani
#
# SPDX-<span></span>License-Identifier: GPL-3.0-or-later
#++
```
