### ISSUE TITLE
Feature: Support PlantUML comments

### ISSUE THREAD

**Issue by wtraylor** [fsfe/reuse-tool#271]
[PlantUML](https://plantuml.com) is a language for describing UML diagrams in text files. Typical file extensions are `.plantuml`, `.iuml`, `.puml`, and `.uml`. The [documentation](https://plantuml.com/de/commons#8413c683b4b27cc3) explains a rather special commenting syntax:

> Everything that starts with simple quote `'` is a comment.
>
> You can also put comments on several lines using `/'` to start and `'/` to end.

This comment style is not yet supported by the reuse-tool. It would be great to have it included.

**Comment by rscohn2** [comment]
Here is a sample PR for adding support for fortran and bat files: https://github.com/fsfe/reuse-tool/pull/255/files

If you make the changes, you can test it with applications that read the files.

**Comment by wtraylor** [comment]
Thanks. I will create a pull request.
