### ISSUE TITLE
reuse lint does not recognize previously used, but now unused licenses

### ISSUE THREAD

**Issue by DerMolly** [fsfe/reuse-tool#277]
We applied reuse to our software just two weeks ago and while making everything work, one colleague noticed that we bundle some font files (and provided .license files for each of them) that we could also just get from the package manager. So they wrote a PR to remove those files, but forgot to remove the corresponding license file from LICENSE.

But `reuse lint` does not recognize that this license is no longer needed and still list it under `Used licenses`. I used several tools to find the license identifier in any of our files, but I did not succeed.

The problematic license was `OFL-1.1-RFN`. The only explanation I could come up with is that we also use `OFL-1.1` for different files and maybe this makes reuse think we still use `OFL-1.1-RFN`?

**Comment by mxmehl** [comment]
That's strange indeed. Could you please share the repo URL so I/we can try to reproduce and debug?

**Comment by DerMolly** [comment]
Of couse.
The repo: https://github.com/hedgedoc/react-client
The PR: https://github.com/hedgedoc/react-client/pull/793

**Comment by mxmehl** [comment]
I just tried to reproduce (sorry for the wait), but cannot find a mention of `OFL-1.1-RFN` at commit f3c4a06b05fd7fa94264fc4a1b82a572904d9253:

```
# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: AGPL-3.0-only, CC-BY-4.0, CC-BY-SA-4.0, CC0-1.0, LicenseRef-DCO, LicenseRef-HedgeDoc-Icon-Usgae-Guidelines, MIT, OFL-1.1
* Read errors: 0
* Files with copyright information: 494 / 494
* Files with license information: 494 / 494
```

Have you issued another commit to fix this? Or perhaps it was in some git-ignored file?

**Comment by mxmehl** [comment]
By the way, we also have a service that regularly lints your repo and provides the lint output in a clean environment. Feel free to register your repo with this API: https://api.reuse.software

**Comment by DerMolly** [comment]
As you can see here the CI Runner tells me there is the OFL-1.1-RFN license there https://github.com/hedgedoc/react-client/runs/1468170657

**Comment by mxmehl** [comment]
I cannot reproduce this, as this branch does not seem to exist any more.

Looking at the action output from the last build on the main branch, this license does not appear any more there: https://github.com/hedgedoc/react-client/runs/1513277408

**Comment by DerMolly** [comment]
Maybe it was a caching problem in the CI runner. Anyway I'll close this now. Thanks for the the link to the api…

**Comment by mxmehl** [comment]
Glad that it worked out. Feel free to open an issue if this happens again :)
