### ISSUE TITLE
Easy way to ignore certain files/folders?

### ISSUE THREAD

**Issue by Potherca** [fsfe/reuse-tool#278]
I am new to using `reuse`, so maybe I missed something, but is it possible to make `reuse` ignore certain files or folders that are _not_ in a project's `.gitignore` file?

For instance, I have entries added to my global git ignore settings, but these are not ignores by `reuse`.

As I couldn't find an `--ignore` setting in the documentation, I felt best to ask...

**Comment by rscohn2** [comment]
Please see this: https://reuse.software/faq/#exclude-file

**Comment by mxmehl** [comment]
Thank you @rscohn2.

Does this link help you sufficiently, @Potherca? If so, please close the issue :)

**Comment by Potherca** [comment]
Ah, yes, that helps a lot!

For future reference (in case anyone else encounters this issue and ends up here):

> Other than the `.gitignore` file you cannot exclude files from REUSE compliance testing.
>
> If you really want to exclude a file, consider using the **CC0** license for this file.
>
> If you have an entire directory that you want to “exclude” from REUSE compliance testing, you can use a DEP5 file
>  `.reuse/dep5` in the root of your project to bulk-license a directory:
>
>```
>Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
>Upstream-Name: my-project
>Upstream-Contact: Jane Doe <jane@example.com>
>Source: https://git.example.com/jane/my-project
>
>Files: directory/to/exclude/*
>Copyright: 2020 Jane Doe <jane@example.com>
>License: CC0
>```
