### ISSUE TITLE
Crash in `chroot` environment

### ISSUE THREAD

**Issue by vanrein** [fsfe/reuse-tool#280]
I usually build software in a chroot environment.  This does not work well with REUSE:

```
Traceback (most recent call last):
  File "/usr/local/bin/reuse", line 11, in <module>
    load_entry_point('reuse==0.11.1', 'console_scripts', 'reuse')()
  File "/usr/local/lib/python3.7/dist-packages/reuse-0.11.1-py3.7.egg/reuse/_main.py", line 256, in main
    return parsed_args.func(parsed_args, project, out)
  File "/usr/local/lib/python3.7/dist-packages/reuse-0.11.1-py3.7.egg/reuse/lint.py", line 333, in run
    project, do_checksum=False, multiprocessing=not args.no_multiprocessing
  File "/usr/local/lib/python3.7/dist-packages/reuse-0.11.1-py3.7.egg/reuse/report.py", line 193, in generate
    pool = mp.Pool()
  File "/usr/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 158, in __init__
    self._setup_queues()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 251, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/usr/lib/python3.7/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 332, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.7/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 38] Function not implemented
```

The workaround is to `--no-multiprocessing` but it nevertheless is a bug in 0.11.1.

**Comment by mxmehl** [comment]
Do you have `/dev/shm` mounted in your chroot? I found a few resources where this is said to solve the issue with multiprocessing:

https://github.com/celery/celery/issues/185

https://falstaff.agner.ch/2013/10/29/setting-up-schroot-for-python-multiprocessing/

**Comment by vanrein** [comment]
Hi Max,

You're the one from the NGI Pointer discussion, if I recall correctly :)

> Do you have `/dev/shm` mounted in your chroot? I found a few resources where this is said to solve the issue with multiprocessing:

I have no idea what /dev/shm is and it is not mounted.  To me that sounds like a pretty wild requirement for document processing :) and not one that I think matches the kind of tool.  Reasonably however, this sounds like it might be due to an oversight in either (1) the multiprocessing library or (2) the assumptions under which it was used.

It looks like this tool is pretty young, but it's also a promising idea.

-Rick

**Comment by mxmehl** [comment]
Hi Rick,

Excactly, that was me ;)

/dev/shm is shared memory, similar to /tmp. It seems the path is quite standard for Python applications using multiprocessing, at least I remember a similar issue with Ansible if this path is not present.

So I am not sure whether it's up for the REUSE tool to circumvent this, or rather for the multiprocessing lib we use.

**Comment by vanrein** [comment]
Hi,

> So I am not sure whether it's up for the REUSE tool to circumvent this, or rather for the multiprocessing lib we use.

Nor am I.  What I do understand is that it is unfriendly towards the user.  After having seen REUSE in action I can see its use, but I believe the work does take some convincing... this doesn't help in that area (which is why I filed it).

-Rick

**Comment by mxmehl** [comment]
I see your point.

So it seems mounting `/dev/shm` is a solution to this immediate problem, so I'd close here.

**Comment by vanrein** [comment]
I have reached a point where I am dropping reuse tests.  Please let me know when this is fixed, it is not workable I'm afraid.

**Comment by vanrein** [comment]
Specifically, I could not even download licenses which I believed worked in the past.

Please understand my emphasis: If you want to convince people of using this tool than it MUST NOT cause spurious errors.  Ever.  It does not matter if your code is the cause or a library that you choose to import.  It does not matter if people use another context than you are expecting.  Just do not believe that people will adopt a fragile tool.

That being said, I'm looking forward to this being resolved.

**Comment by rscohn2** [comment]
Please try --no-multiprocessing

**Comment by vanrein** [comment]
I tried that too, of course, but that failed too.

It's understandable; you are before 1.0 and probably not reaady for variations in use cases.  Closing this issue was perhaps not the best of choices.

Fragile code in CI is terrible because of the delay / overhead, and not being able to run the tests locally is not workable, as indicated.  Plus, we intend to build on a variety of platforms using our chroot-based approach and it is likely that your software would bring up even more exceptions then.  Exceptions in CI are, once more, terrible to have to handle.

I support the idea, just not (the current version of) your software.  I thought it polite to nudge you that a mere work-around kludge is in the end a liability and insufficient if you are trying to get people to adopt extra build-time tests; it did not work out for us.

Good luck with your project.

**Comment by rscohn2** [comment]
I am just a user like you. I thought I could resolve the problem by adding a switch to disable multiprocessing, then I saw that there already was a switch and posted a suggestion, then I noticed that you already know about the switch so I posted again with the 'never mind'. If you provide directions on how to reproduce I could look at why the switch did not work. If you don't want to spend any more time on it, then no need.

**Comment by vanrein** [comment]
Thanks Robert.  No, I will be patient and wait for a 1.0 version.

**Comment by mxmehl** [comment]
Thanks for your offer to debug this @rscohn2!

@vanrein, just us shifting the version number to 1.x does not magically solve all issues, and probably also not yours. As stated, you use a non-standard environment. You have two options: mounting `/dev/shm` or using `--no-multiprocessing`. I personally am not aware of any tricks we can pull to make things work in your env by default.

Robert kindly offered to look into this, so I suggest you provide more details so we can see how it can be improved.
