### ISSUE TITLE
Directory mismatch between `download` and `lint`

### ISSUE THREAD

**Issue by vanrein** [fsfe/reuse-tool#281]
When running `reuse download` from a project subdirectory it stores under the current directory as `LICENSES/xxx`.  When running `lint` it prefers to start at the (Git) project root, and does not find a license that ended up under the subdirectory.

**Comment by mxmehl** [comment]
Confirmed, that's a bug indeed. As written in [our spec](https://reuse.software/spec/#license-files), the LICENSES directory MUST be at the root of the project.

Therefore, `reuse download` should create the folder at the git root.

**Comment by mxmehl** [comment]
This has been fixed with #430 already as it seems. At least I cannot reproduce this error any more with the recent version :tada:
