### ISSUE TITLE
"reuse lint" tries parsing backslashes in dep5 as escape sequences

### ISSUE THREAD

**Issue by rpavlik** [fsfe/reuse-tool#283]
I was working on a project on Windows, so I had accidentally copied some backslashes into my `.reuse/dep5` file. Apparently it's interpreting that as an escape sequence, and failing, since I get the below error repeated for every file in my repo, if there's a single backslash in the dep5 file in a filename:

```
reuse lint
reuse.report - ERROR - Unexpected error occurred while parsing '.appveyor.yml'
debian.copyright.MachineReadableFormatError: invalid escape sequence: \s
```

Not sure if that's a bug in the python debian.copyright, or if it's expected that you'd escape things going in - I suspect I'd have a hard time convincing them to accept a patch to allow backslashes as path separators.

**Comment by carmenbianca** [comment]
Closing notabug. This is inherent to DEP5 (and its library), and is a feature instead of a bug.

Thanks for reporting the issue. Sorry for the long delay.
