### ISSUE TITLE
Lint does not report unused license

### ISSUE THREAD

**Issue by paddy-hack** [fsfe/reuse-tool#285]
While documenting the allowed licenses for a project I just started on I added `LICENSES/CC0-1.0.txt`.  However, the project still has no files that actually use this license.  That notwithstanding, running `reuse lint` did not report it as unused and neither did the REUSE API service as illustrated below
``` json
{
  "badge": "https://api.reuse.software/badge/gitlab.com/numismate/numismate",
  "hash": "a045ae100eb4d6e0385d67ccedc80f7ff3f53b8a",
  "last_access": "2020-12-13T04:42:06.853529",
  "lint_code": 0,
  "lint_output": "# SUMMARY\n\n* Bad licenses:\n* Deprecated licenses:\n* Licenses without file extension:\n* Missing licenses:\n* Unused licenses:\n* Used licenses: AGPL-3.0-or-later, CC-BY-SA-4.0, CC0-1.0\n* Read errors: 0\n* Files with copyright information: 16 / 16\n* Files with license information: 16 / 16\n\nCongratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)\n",
  "status": "compliant",
  "url": "gitlab.com/numismate/numismate"
}
```
I removed all references to CC0 from my code base, as in `git grep CC0` does not report any hits, to see if that made a difference but it did not.

**Comment by mxmehl** [comment]
Confirmed, thanks for the report! This clearly is a bug, and a regression. I tested with v0.7.0, and it worked as expected, but from v0.8.0 onwards this shows the current, wrong behaviour.

We clearly have to fix this, and create a test that catches such issues in the future.

**Comment by carmenbianca** [comment]
This is an incredibly weird issue, because it should've been tested against. Created #313 as a note-to-self that this shouldn't happen again.

#312 fixes this. Thanks a lot for reporting.
