### ISSUE TITLE
Git submodules should be handled

### ISSUE THREAD

**Issue by arcturus140** [fsfe/reuse-tool#29]
When I look into https://git.fsfe.org/reuse/website,

this repository has a single license file and a git submodule. The submodule contains a `LICENSES` folder (in master branch).

The first thing I notice is that some files have no SPDX license identifier, for example `README.md`, though the rendered output as 'content of the website' _is_ licensed. 

Files like `.gitmodules` and `Dockerfile` do not have a license. I was hoping to use `reuse lint` in a build step to check whether the project is `REUSE compliant` or not, but this doesn't work since there is no distinction between exceptions and missing license identifier. 

When using submodules I receive the following git error: `fatal: Pathspec 'reuse-docs/.git' is in submodule 'reuse-docs'`

Finally, licenses from submodules cannot be found: `reuse - WARNING - reuse-docs/practices/2.0.md is licensed under CC-BY-SA-4.0, but its license file could not be found`

The reason for this is that the license only exist in the folder of the submodule and is missing in the root folder of the repository. 

In this case, should I copy all licenses from submodules into the root `LICENSES` folder, according to `practice 1` or should I make a reference in the header:

```
/*
* This file is part of project X. It’s copyrighted by the contributors
* recorded in the version control history of the file, available from
* its original location http://git.example.com/X/filename.c
*
* SPDX-License-Identifier: GPL-3.0
*/
```

**Comment by carmenbianca** [comment]
> When I look into https://git.fsfe.org/reuse/website,

This repo is not currently itself REUSE-compliant, which I suppose is kind of ironic.

> Finally, licenses from submodules cannot be found: reuse - WARNING - reuse-docs/practices/2.0.md is licensed under CC-BY-SA-4.0, but its license file could not be found

I thought I fixed this bug...

Git submodules should basically ideally be ignored.

**Comment by arcturus140** [comment]
well, the repo proudly wears the REUSE-compliant batch :sweat_smile: 

So submodules should be ignored? Even without submodules, imagine I have a carbon copy of some (reuse-compliant) project in my own project. The problem would be the same. Also with every recursive submodule fetch, Evil Corp could potentially stop being compliant at some point and I'd have to recursively detect that.

**Comment by carmenbianca** [comment]
> well, the repo proudly wears the REUSE-compliant batch sweat_smile

Great shame :x

> Even without submodules, imagine I have a carbon copy of some (reuse-compliant) project in my own project

I wouldn't really know how to fix this short of further complicating the REUSE spec. Opened an issue [here](https://github.com/fsfe/reuse-docs/issues/36).

> Also with every recursive submodule fetch, Evil Corp could potentially stop being compliant at some point and I'd have to recursively detect that.

I suppose I could perhaps recursively call `reuse lint` if a git submodule is detected. Maybe as an option? I'm not sure how important and/or common this use-case is.

**Comment by silverhook** [comment]
> I suppose I could perhaps recursively call `reuse lint` if a git submodule is detected. Maybe as an option? I'm not sure how important and/or common this use-case is.

I think a `--recursive` flag might be useful, but it should not be on by default.

**Comment by arcturus140** [comment]
The way it currently behaves is that it throws an error message if no git repository exists, otherwise it always lints from repository root, regardless of the current working directory, e.g.

```
cd ~/repo && reuse lint
```
yields the same result as
```
cd ~/repo/submodule && reuse lint
```

```
repo
├── LICENSES/
└── submodule
    ├── LICENSES/
    ├── LICENSE.spdx
    ├── README.md
    └── test.c
```

meaning that it always searches on `repo/LICENSES/`. Using it recursively is not a difficult exercise for the user but the option would be convenient.

**Comment by carmenbianca** [comment]
> The way it currently behaves is that it throws an error message if no git repository exists, otherwise it always lints from repository root, regardless of the current working directory, e.g.
> 
> ```
> cd ~/repo && reuse lint
> ```
> 
> yields the same result as
> 
> ```
> cd ~/repo/submodule && reuse lint
> ```

I can't reproduce this. Are you on the master branch? When I `reuse lint` in `repo/submodule/`, it only lints the submodule. When I `reuse lint` in `repo/`, it searches everything, thereby ignoring `repo/submodule/LICENSES`, which is a bit annoying.

**Comment by arcturus140** [comment]
no, I am on the latest release (0.3.4) which is different from master. I'll start using master, then.

**Comment by arcturus140** [comment]
With `REUSE 0.4.0a1` I don't have these issues anymore, except that licenses from submodules are missing in the repository.

**Comment by carmenbianca** [comment]
These still need to be handled with options as discussed in https://github.com/fsfe/reuse-docs/issues/36, so reopening

**Comment by arcturus140** [comment]
> I can't reproduce this. Are you on the master branch?

I am using `reuse 0.4.0a1`.

REUSE working directory is always git root directory, not bash current working directory. The following script creates two folder structures, reuse_test1 and reuse_test2. both are structurally the same, only reuse_test2 is a git repository. 

reuse is executed from a subdirectory `subdir`. 

## test case 1

reuse downloads and lints within the subdirectory. 1 file is found: 
```
Files with copyright information: 1 / 1
Files with license information: 1 / 1
```
1 license is downloaded:
```
1 directory, 2 files
```

## test case 2

reuse downloads and lints within the parent directory. 2 files are found: 
```
Files with copyright information: 2 / 2
Files with license information: 2 / 2
```
the license is not downloaded in subdirectory (it is in parent)
```
0 directories, 1 file
```

Please follow the following instructions using bash:

WARNING: THIS SCRIPT CONTAINS A DESTRUCTIVE INSTRUCTION. 
The script modifies and deletes the following folders:
- `/tmp/reuse_test1`
- `/tmp/reuse_test2`

## Dependencies

- git
- tree
- reuse

## test case


<details>
<summary>MWE used to illustrates the issue: </summary>

    rm -rf /tmp/reuse_test1 /tmp/reuse_test2
    mkdir -p /tmp/reuse_test1/subdir /tmp/reuse_test2/subdir

    cd /tmp/reuse_test1

        echo "SPDX-Copyright: 2019 Your Name
        
    SPDX-License-Identifier: Aladdin
        " > test.txt
        echo "SPDX-Copyright: 2019 Your Name
        
    SPDX-License-Identifier: Aladdin
        " > subdir/test.txt

        cd subdir

            reuse --version
            reuse download Aladdin
            reuse lint

            tree

        cd ..

    cd ..

    cd /tmp/reuse_test2

        git init

        echo "SPDX-Copyright: 2019 Your Name
        
    SPDX-License-Identifier: Aladdin
        " > test.txt
        echo "SPDX-Copyright: 2019 Your Name
        
    SPDX-License-Identifier: Aladdin
        " > subdir/test.txt

        cd subdir

            reuse --version
            reuse download Aladdin
            reuse lint

            tree

        cd ..

    cd ..

</details>

## test result


<details>
<summary>Script output: </summary>

    reuse 0.4.0a1
    Successfully downloaded Aladdin.SUMMARY

    Bad licenses: 0
    Missing licenses: 0
    Unused licenses: 0
    Used licenses: Aladdin
    Read errors: 0
    Files with copyright information: 1 / 1
    Files with license information: 1 / 1

    Congratulations! Your project is REUSE compliant :-)
    .
    ├── LICENSES
    │   └── Aladdin.txt
    └── test.txt

    1 directory, 2 files
    Initialized empty Git repository in /tmp/reuse_test2/.git/
    reuse 0.4.0a1
    Successfully downloaded Aladdin.SUMMARY

    Bad licenses: 0
    Missing licenses: 0
    Unused licenses: 0
    Used licenses: Aladdin
    Read errors: 0
    Files with copyright information: 2 / 2
    Files with license information: 2 / 2

    Congratulations! Your project is REUSE compliant :-)
    .
    └── test.txt

    0 directories, 1 file

</details>

**Comment by carmenbianca** [comment]
It is a little difficult to follow the instructions you've provided, but I don't see what is wrong. Your output is different from mine, though. In the second test case I get this output from `tree`:

```
.
├── LICENSES
│   └── Aladdin.txt
└── test.txt
```

which is expected, because:

```
$ reuse download --help
usage: reuse download [-h] [--output OUTPUT] license

Download a license and place it in the LICENSES/ directory.

The LICENSES/ directory is automatically found in the following order:

- The LICENSES/ directory in the root of the VCS repository.

- The current directory if its name is LICENSES.

- The LICENSES/ directory in the current directory.

If the LICENSES/ directory cannot be found, one is simply created.

positional arguments:
  license               SPDX Identifier of license

optional arguments:
  -h, --help            show this help message and exit
  --output OUTPUT, -o OUTPUT
```

What is the issue?

**Comment by arcturus140** [comment]
> I get this output from tree:
>
> ```
> .
> ├── LICENSES
> │   └── Aladdin.txt
> └── test.txt
> ```

This is the desired behaviour (I think). It behaves different on my system. 

Are you working on a linux maschine? You only need to copy & execute my test script. 

Steps to replicate:

1. create git repo: `mkdir repo && cd repo && git init`
2. navigate to subfolder: `mkdir sub && cd sub`
3. download license: `reuse download Aladdin`

the license is then downloaded into `repo/LICENSES` instead of `repo/sub/LICENSES`.

**Comment by carmenbianca** [comment]
> the license is then downloaded into `repo/LICENSES` instead of `repo/sub/LICENSES`.

That is intended behaviour. The REUSE spec doesn't support keeping licenses outside of `root/LICENSES`, so I'm not sure why the tool should place licenses elsewhere.

**Comment by arcturus140** [comment]
1. it behaves differently being a repository or not
2. achieving REUSE compliance can be a tedious task. Due to an overwhelming number of unlicensed files I'd like to lint subdirectories only
3. for the usecase to apply REUSE compliance ONLY for a source tar ball we need the tool to place licenses _there_. Is the .tar ball not part of the repo? I am not sure on this haven't used that yet.

**Comment by carmenbianca** [comment]
> it behaves differently being a repository or not

Because there's currently no way to figure out the root of a project outside of a git repo. I might change that and detect the first directory upwards that has a `.reuse` directory, but currently it is as-is.

> achieving REUSE compliance can be a tedious task. Due to an overwhelming number of unlicensed files I'd like to lint subdirectories only

`reuse lint subdir`

> for the usecase to apply REUSE compliance ONLY for a source tar ball we need the tool to place licenses there. Is the .tar ball not part of the repo? I am not sure on this haven't used that yet.

Tarball isn't part of the repo, it's generated by a build script. For an esoteric use-case, you can just `mv root/LICENSES root/somewhere/else/LICENSES`.

**Comment by arcturus140** [comment]
> I might change that and detect the first directory upwards

I think we can leave this to the user. A build system is smart enough to handle it.

> `reuse lint subdir`

this solves my problem. I didn't know this is supported, thanks :)

**Comment by carmenbianca** [comment]
It's half-supported at the moment and needs some fixing. But it kinda works!
