### ISSUE TITLE
MANIFEST.in support

### ISSUE THREAD

**Issue by nicorikken** [fsfe/reuse-tool#306]
I encountered a project where a `MANIFEST.in` file was located. This is a file that is typically present for compiling Python source distributions: https://packaging.python.org/guides/using-manifest-in/

The current `_comment.py` already contains support for `Manifest.in`. It seems this was intended to be `MANIFEST.in`, but I'm not sure. Here is the actual line: https://github.com/fsfe/reuse-tool/blob/af5467130298e483db28624c05edbe5ebaeeae48/src/reuse/_comment.py#L593
Should I add a duplicate entry for `MANIFEST.in` in capital letters, or should I replace the existing entry?

**Comment by nicorikken** [comment]
A search through GitHub code only found me one example of `Manifest.in` in hunderds of hits. Most importantly the file was empty and not being used.
Also I did a test locally and found that `MANIFEST.in` is picked up automatically, and `Manifest.in` is ignored by `python setup.py sdist`.

So I conclude that it should actually be `MANIFEST.in` and I will create a pull request to match that change.

Perhaps original authors of that change @carmenbianca or @KAction can correct me if I'm wrong.

**Comment by carmenbianca** [comment]
Closed by #307 

Thanks!
