### ISSUE TITLE
Unintended change of line-ending style to Unix

### ISSUE THREAD

**Issue by nicorikken** [fsfe/reuse-tool#308]
When running REUSE on a Linux machine I notice that files with Windows-style line-endings get changed to files with Unix-style line-endings.
Although personally I like my files with Unix-style line-endings :+1: :smile: I think it is a bug that REUSE secretly changes this. There might be cases where a specific line-ending style was chosen.

**Comment by carmenbianca** [comment]
Oh wow… I'm not sure how to fix that. I'm fairly certain that Python automagically converts to Unix-style line endings upon reading a file. We would need to detect the line endings of a file, remember it, and convert back just before writing to disk.

Given that header.py is already a bit of a soup of cutting and pasting newlines, that might require a refactor.
