### ISSUE TITLE
User defined license reference should be recognized

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [fsfe/reuse-tool#325]
the `License: LicenseRef-Proprietary` entries triggered:

```
# BAD LICENSES

'LicenseRef-Proprietary' found in: ...
```

Which should be acceptable according to [Appendix IV: SPDX License Expressions - specification v2.2.0](https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/)

**Comment by mxmehl** [comment]
Hm, actually that's supported by REUSE: https://reuse.software/faq/#custom-license

Could you please share which version you use, and check whether you followed the recommendations on this FAQ item?

**Comment by Lin-Buo-Ren** [comment]
> Hm, actually that's supported by REUSE: https://reuse.software/faq/#custom-license
> 
> Could you please share which version you use, and check whether you followed the recommendations on this FAQ item?

I'm currently using 0.12.1.  After adding the license file the lint successfully passed, thanks for your help!
