### ISSUE TITLE
Add copyright header style for spdx-symbol

### ISSUE THREAD

**Issue by silverhook** [fsfe/reuse-tool#329]
The tool already supports many styles, but lacks `SPDX-FileCopyrightText: ©`.

I suggest this gets added as `reuse addheader --copyright-style spdx-symbol`

**Comment by jonburdo** [comment]
I just recently discovered this tool and wanted this precisely too. I think like the copyright symbol adds clarity to anyone who might not already be familiar with spdx and seems to be the most universally recognized symbol. I just added a PR [here](https://github.com/fsfe/reuse-tool/pull/350).
