### ISSUE TITLE
man page missing

### ISSUE THREAD

**Issue by ole-tange** [fsfe/reuse-tool#334]
~~~
$ man reuse
No manual entry for reuse
~~~

**Comment by mxmehl** [comment]
Ideally this would be generated automatically from the existing docu in some sort.

**Comment by stephanlachnit** [comment]
`help2man reuse --no-info > reuse.1` is probably enough here and easy to implement. And it can be done at build time.

Note: For reproducibility, you might need to set [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=787444), but reproducible build servers should do that automatically.

**Comment by ole-tange** [comment]
To me just converting the help text would not be enough: The man page should contain all information that is needed to run this version, and not just refer to online documentation.

There are several problems with online documentation:

* They often only refer to the newest version and not the version you have installed.
* They do not work if the hosting provider no longer wants to host them (you will be surprised how common this is after just 10 years).

But I agree with @mxmehl that it ought to be possible to generate it from the existing documentation.

**Comment by stephanlachnit** [comment]
A full documentation should be installed sperately, at least that's what Debian does everywhere. Man pages usually for cli programs, offline html for full docs.

**Comment by stephanlachnit** [comment]
Maybe useful: https://pypi.org/project/click-man/

**Comment by jonasstein** [comment]
We generate man from .rst and included a git workflow and makefiles https://github.com/scsitape/stenc
and it works very well. Perhaps you can reuse some ideas here.
