### ISSUE TITLE
Only look at files that are in GIT

### ISSUE THREAD

**Issue by ole-tange** [fsfe/reuse-tool#335]
`reuse` looks at all files in the current dir tree. I have *tons* of files that are not part of the repository.

When run in a dir with a .git dir, I think the default should be only to look at the files added to the repository.

**Comment by mxmehl** [comment]
The REUSE tool ignores `.git` and also all files mentioned in `.gitignore`.

If this is not the case, that seems to be a strange bug. Could you please check it with a freshly clones Git repo? You can take this reuse-tool repo as a test, it should be compliant.

**Comment by ole-tange** [comment]
To reproduce:

~~~
mkdir foo
cd foo
git init
echo foo > bar
reuse lint
~~~

It should look at what is in the repository and will be pushed, not what just happens to be in the dir.

If you want to include the file that are never pushed, please explain why you find it important to include these.

**Comment by mxmehl** [comment]
Well, but since you added `bar`, and since you did not ignore it, REUSE should respect it.

That's for instance necessary if you added reuse lint as a [pre-commit command](https://reuse.software/dev/#pre-commit-hook). Or imagine modifying and adding files – REUSE should always be able to give the actual current status, and not require a commit beforehand.

Or did I completely misunderstand you?

**Comment by ole-tange** [comment]
> Well, but since you added bar, and since you did not ignore it, REUSE should respect it.

I disagree. I have tons of these files, they are named randomly and I cannot add these to .gitignore.

When I push, the pushed repository will be compliant but my dir will not. That does not respect the Principle of Least Surprise.

If you want add an option to include all files, that would work for me. But the current behaviour I find non-intuitive.

**Comment by mxmehl** [comment]
Well, I am afraid we agree to disagree then :)

REUSE is supposed to check the as-is status (excluding the mentioned files), not the last commit. That would be counter-intuitive IMHO. After running `reuse addheader` or other tools multiple times, you'd always have to commit to check whether compliance is reached.

If we did it your way, this issue tracker would certainly be full of "lint says uncompliant, but the API say compliant" or the other way round.

**Comment by ole-tange** [comment]
> If we did it your way, this issue tracker would certainly be full of "lint says uncompliant, but the API say compliant" 

This is *exactly* what I am talking about. The API would find the `foo` example above compliant, but `lint` says uncompliant.

**Comment by mxmehl** [comment]
I admit my API example was odd. But the API case is a completely different one: it checks whether a *publicly available* source tree is REUSE compliant.

If you clone it, it still is compliant. If you remove all files in `LICENSES/`, it is not compliant, even if that's not checked into Git.

Any other linter I know also checks the as-is status, not what's checked into Git.

**Comment by ole-tange** [comment]
I found a work-around:
~~~
        rm -rf /tmp/reuse
        mkdir /tmp/reuse
        (wd=`pwd`; \
        cd /tmp/reuse; \
        git clone "$wd"; \
        reuse lint )
~~~
