### ISSUE TITLE
.pod is unknown: Look at the first line

### ISSUE THREAD

**Issue by ole-tange** [fsfe/reuse-tool#336]
.pod is Perl's plain-old-documentation and should be treated as .pl.

This could be added, but I think it would be even better, if you looked at the first line: If the first line is a "#!" use that to determine which comment style is needed.

**Comment by nicorikken** [comment]
@ole-tange I looked into the POD syntax. But I don't see what you mean by:
> I think it would be even better, if you looked at the first line: If the first line is a "#!" use that to determine which comment style is needed.
Do you mean that it then would determine the Perl interpreter, like a bash script? I guess that wouldn't change the comment syntax, but it needs to take into account handing the first syntax. The Python comment syntax is already used for shell files, so it might just work.

Can you perhaps link some interesting example files with edge cases to consider?

**Comment by ole-tange** [comment]
> I think it would be even better, if you looked at the first line: If the first line is a "#!" use that to determine which comment style is needed.

By looking at the shebang line you can determine with interpreter is used for the file. For .pod-files this will be perl, but instead of treating .pod special, I think it will be better to look at the interpreter, and given the interpreter determine which comment style to use.

**Comment by mxmehl** [comment]
I'll add .pod.

Regarding adding some heuristic to determine the comment style, I'd prefer a separate issue.
