### ISSUE TITLE
.txt does not have a recognised file extension

### ISSUE THREAD

**Issue by ole-tange** [fsfe/reuse-tool#337]
That should not be hard to add.

~~~
reuse addheader: error: 'foo.txt' does not have a recognised file extension, please use --style, --explicit-license or --skip-unrecognised
~~~

**Comment by mxmehl** [comment]
I am not sure whether we want to pre-define the comment style of `.txt` files. It could be anything: python, c, html...

**Comment by ole-tange** [comment]
I think it is fair to assume `.txt` is not source code, but text documentation.

**Comment by mxmehl** [comment]
But text might be parsed differently, perhaps even as markdown (so HTML). So I am hesitant towards making an assumption that does not match the fair expectation of users.

With --style, it is quite simple to choose your desired style.

**Comment by ole-tange** [comment]
I tried --style.

It was not simple for me: I have no idea how to use --style, there is no man page and --help does not show examples.

I would much rather it had inserted a few lines, that I could change before I commit.

**Comment by mxmehl** [comment]
Here you will find the documentatiopn about supported styles: https://reuse.readthedocs.io/en/stable/usage.html#comment-styles

**Comment by ole-tange** [comment]
Great. But there are three problems with that:

* Documentation should be available even if you are offline
* None of these tells me which style to use for README.txt (which is not written in any computer language)
* There are no examples
