### ISSUE TITLE
.fodt does not have a recognised file extension

### ISSUE THREAD

**Issue by ole-tange** [fsfe/reuse-tool#339]
~~~
reuse addheader: error: 'src/parallel_cheat_bw.fodt' does not have a recognised file extension, please use --style, --explicit-license or --skip-unrecognised
~~~

It should be possible to set the license in a LibreOffice document.

I tested if you could just use the .xml. But that does not work. It destroys the file.

**Comment by mxmehl** [comment]
Should be added to the file extensions that require an explicit license file (same for ods, odt, ott etc).

**Comment by nicorikken** [comment]
To be even more explicit than @mxmehl these file extensions need to be added to the `EXTENSION_COMMENT_STYLE_MAP` dictionary  with the `UncommentableCommentStyle`: https://github.com/fsfe/reuse-tool/blob/fa8595fbfc3d8cdb094f75be9aff462c8a2e7dad/src/reuse/_comment.py#L438-L581

This really is a _good first issue_ : something you can even do from the GitHub online editor, thus without having to locally check out and run the code.

**Comment by hoijui** [comment]
if you put the comment after the first line in the .fodt file (XML syntax), LibeOffice can still read it fine, but after saving (just like with Inkscape and SVG) the comments are gone, so.. yes, needs an extra *.license file. :/
