### ISSUE TITLE
Can’t write `.license` file for write-protected file

### ISSUE THREAD

**Issue by wtraylor** [fsfe/reuse-tool#346]
# Issue
`reuse` doesn’t create a separate `.license` file if the original file is write-protected/read-only.

# Steps to Reproduce

```bash
touch test.txt
chmod a-w test.txt
reuse addheader -l 'CC-BY-4.0' -c 'Jane Doe' --explicit-license test.txt
```

Error:

    reuse addheader: error: argument path: can't write to 'test.txt'

Environment:
- Reuse version: 0.12.1
- Operating system: ArchLinux
- Python version: 3.9.2

# Expected Behavior
`reuse` crates a `test.txt.license` file without error.

As long as the directory is writeable and a `.license` can be created, there should be no error.

**Comment by nicorikken** [comment]
I tested it and it works. Previously it would trigger an error:
