### ISSUE TITLE
[question] apply suffix to license file names

### ISSUE THREAD

**Issue by arcturus140** [fsfe/reuse-tool#35]
this is a repost from [the forum](https://community.fsfe.org/t/reuse-license-file-not-found-with-suffix-in-filename/291): 

From [the documentation](https://github.com/fsfe/reuse-docs/blob/master/practices/2.0.md#1-provide-the-exact-text-of-each-license-used) we read that it is allowed to add a suffix to the file name containing the License Text:

> (you may attach some suffix to the filename as well, such as LICENSE.txt ).

I tested this and am having problems. I created a file with SPDX License Identifier

```
SPDX-Copyright: 2019 Alice

SPDX-License-Identifier: BSD-2-Clause
```

then created a License file with the name `LICENSES/BSD-2-Clause-Alice.txt`

The tool couldn’t find it. When I change the name to `LICENSES/BSD-2-Clause.txt` it works.

Can the prefix only be applied to file extensions?

**Comment by carmenbianca** [comment]
This seems like a misinterpretation of multiple things.

First, the information on https://reuse.software and the master branch of https://github.com/fsfe/reuse-docs is **NOT UP-TO-DATE**. We are doing a rework of the spec soon. You can find the rework in these PRs:

https://github.com/fsfe/reuse-docs/pull/23

https://github.com/fsfe/reuse-docs/pull/19

https://github.com/fsfe/reuse-docs/pull/18

Any other information is *probably* inaccurate at this stage. Or at least, it is inaccurate as it pertains to the master branch of this tool. It *is* accurate as the current set of recommendations, but it is due for replacement soon.

Which leads to a few more observations:

1. You can't do `SPDX-License-Identifier: BSD-2-Clause` and expect it to refer to `LICENSES/BSD-2-Clause-Alice.txt`. You have to explicitly state the license.

2. You do not need to do `BSD-2-Clause-Alice` anymore under the updated recommendations. See the FAQ PR.

3. The correct syntax for custom licenses is `LicenseRef-NAME`, e.g. `LicenseRef-BSD-2-Clause-Alice`. The "suffix" in the quoted text refers exclusively to the file extension.

4. The files `LICENSE`, `LICENCE`, `COPYING`, and `COPYRIGHT` are no longer valid locations to keep license files. All license files must be kept in `LICENSES/`.
