### ISSUE TITLE
Deal with capitalization

### ISSUE THREAD

**Issue by nicorikken** [fsfe/reuse-tool#355]
Sometimes you encounter filenames with an extension that is in a different capitalization. This was already the case for issues #353  and #306.

Some filetypes or filenames are only considered if they have an exact capitalization, so in that regard there is still value in having different handling if files have a different capitalization. Examples can be `Dockerfile`, `.gitignore` and `MANIFEST.in`.

Does the comment handling need to be expanded to have some capitalization parameters per file, or can we suffice with a broader policy?

**Comment by mxmehl** [comment]
> Does the comment handling need to be expanded to have some capitalization parameters per file, or can we suffice with a broader policy?

I think we should be on the safe side when just removing case-sensitivity for all files and extensions. I couldn't think of a file that – depending on its capitalisation – has a different comment format. And if there was, I would consider that a very specific edge case that we could handle specifically.

**Comment by nicorikken** [comment]
Alight, so then the lookup in `_get_comment_style_path` has to be modified to be case-insensitive: https://github.com/fsfe/reuse-tool/blob/60c0986bb24a3b482ee0527e9195f7c23cadb003/src/reuse/header.py#L296-L301
I'm not sure if can achieve this with a parameter in the `.get()` but otherwhise we can convert the `path.name` and `path.suffix` to lowercase before doing the lookup. Then the `_COMMENT_STYLE_MAP`'s have to be in lowercase.

**Comment by mxmehl** [comment]
Sorry, I am a bit too little into Python to make a substantiated evaluation here. But what you say sounds good to me :)
