### ISSUE TITLE
MATLAB/Octave comments

### ISSUE THREAD

**Issue by demsarjure** [fsfe/reuse-tool#357]
Hi!

I just used the reuse-tool to license our code properly. The tool is great and I had no major issues when sorting things out. Thanks for preparing and maintaining the tool!

I would only recommend that you add the option of adding headers in MATLAB/Octave files (.m files). MATLAB/Octave are quite popular amongst the scientific community. I had to add headers in our code manually. I saw later from your source code that I could also use the option of adding headers to Tex files (LaTeX and MATLAB/Octave have same style of single line comments). In MATLAB/Octave single line comments start with "%", while block comments are encapsulated in 

%{ 
...
comments block
...
%}

I think this simple addition would make your tool even better and useful for a wider audience.

Cheers, Jure

**Comment by nicorikken** [comment]
I started work in this, only to found out this is a bit more complicated. Both the `#` and `%` (and thus `#{` `#}` and `%{` `%}` are used for comments. From my history with Matlab and Octave I remember mainly using the `%`, but I did find the `#` syntax on GitHub as well. Some Octave documentation on the available comment syntax: https://octave.org/doc/v5.2.0/Comments.html

I'm not sure how to deal with 2 valid comment syntax in Reuse at the moment. There is a similar thing going on for the `BatchFileCommentStyle` for which multiple comment styles are valid. Thinking about how I would like to specify it, I would define multiple comment styles, and add them as a list to the `EXTENSION_COMMENT_STYLE_MAP` dictionary for a particular file extension. And the parser should then be able to select the applicable format and chose that over the others.

**Comment by mxmehl** [comment]
@nicorikken Good question! Please feel free to make a suggestions. For *adding* a comment, I think we could stick to one syntax. Of course, one could try to find out an already used comment syntax but that seems to be a bit overload IMHO.

For *detecting* used comment styles, we may only have to add `%` if no comment style already uses that for single-line comments. `#` is already used by PythonCommentStyle so the linter should find it, right?

**Comment by JoKeyser** [comment]
In Matlab, `#` is not recognized as a comment, so `%` should be used to generate headers.
For generation, I would also prefer single-line comments over multi-line comments.

For detection, it would of course be nice if all valid styles are recognized.

**Comment by nicorikken** [comment]
Thanks @JoKeyser for sharing your insight. Then it should be easy to add support.

**Comment by carmenbianca** [comment]
Closed by #1015
