### ISSUE TITLE
List all SPDX license identifiers (compatible with REUSE)

### ISSUE THREAD

**Issue by hoijui** [fsfe/reuse-tool#363]
It would be great to run `reuse --list-licenses` or similar, and get an easily `grep`able list of SPDX license identifiers with links. That would make choosing one easier, if I already know which license I want, but don't know the SPDX identifier by heart.

**Comment by mxmehl** [comment]
Shouldn't be hard to implement as we have them [here](https://github.com/fsfe/reuse-tool/tree/master/src/reuse/resources).
