### ISSUE TITLE
reuse lint should not complain about files that are in `.gitignore`

### ISSUE THREAD

**Issue by deviant** [fsfe/reuse-tool#368]
What it says in the title. Things in `.gitignore` are not intended for inclusion into the repository, and thus should not be validated. I don't want to have to clear my compiler cache just to get a valid lint.

**Comment by deviant** [comment]
No longer seeing this, possible user error?

**Comment by mxmehl** [comment]
That is exactly how it works as of today: https://reuse.software/faq/#exclude-file

If not, then it's a fatal bug.
