### ISSUE TITLE
[QUESTION] Should custom parsers be supported/maintained for non-trivially commentable files?

### ISSUE THREAD

**Issue by hoijui** [fsfe/reuse-tool#372]
## The Problem

As a simple example, take XML, more specifically SVG (see #180).
We can use HTML comments there,
but many XML files (and definitely SVG) will not be edited in text editors,
but through GUIs, and these GUIs will often strip comments -
Inkscape does so with SVG, for example.

SVG/Inkscape has a special tag for defining the license:

```xml
<cc:license rdf:resource="SPDX-License-Identifier: GPL-3.0-or-later" />
```
(see also <https://developer.mozilla.org/en-US/docs/Web/SVG/Element/metadata>)

LibreOffice uses this:

```xml
<office:meta>
  <dc:license>SPDX-License-Identifier: GPL-3.0-or-later</dc:license>
</office:meta>
```

Should the reuse tool add custom support for such files, recognizing them, and writing/reading those special tags, instead of using HTML comments or `*.license` files?

## Pros

* No duplicated licensing info within a single file
* GUI editors and reuse tool can work together, and thus also coders and content creators
* not possible to accidentally or purposefully separate the license info from the regular file
* aesthetically more pleasing/looking more "cleaned up", when looking at the projects files

## Cons

* a LOT more complexity on the code of reuse-tool, resulting in:
  * much more maintenance work

## Preliminary, personal conclusion

My gut feeling would be, to say no to this.
Even if it makes a lot of sense... I see this rather as a whole new project of its own, probably better implemented in a native language (e.g. Rust), with clearly and well defined interfaces, covering only reading and writing of meta-data of different file types.

The real reason for asking this, is more to have an idea of the desired scope of this tool, or say, to get an answer to the question:

> How deep into the rabbit hole are you willing to go?

**Comment by nicorikken** [comment]
Thanks for making this explicit. I had the same thought when I encountered my first SVG file with Reuse.

I think it is a nice-to-have. If reuse-tool could read these parameters, the information could be use in linting or autofill for setting parameters. If reuse-tool could write, the licensing information can be better embedded in the files. Say somebody copies the single file, the `.license` file would be omitted and the information would be lost. Not if the information is embedded in the file itself.

 As you suggest this could result in a lot of additional code to parse different file formats. As dependencies or self-written code. Either way it is a burden to maintain. And I see a parallel with parsing information from version control systems or project files, which also requires a vast amount of code. So I think it is a nice to have, but `.license` files are sufficient for the time being. It has a low priority for me, improvements on usability and additional file formats are more important to me.

I'm curious what others think.

**Comment by hoijui** [comment]
ahh that is an othe rargument indeed, that two files (the regular and the `*.license` one) might get separated.

Yet and other thing that is pro integration into the file:
If we look at Open Source *Hardware*, we are dealing a lot with binary files (CAD, drawings and photos in PNG or JPEG format, ...). These files can easily make up 80% of the files in the repo, for some projects. If each one of them needs an additional file next to it, I can tell you, 90% of the repo maintainers will be against it. And be it just for esthetic reasons.
One thing I learned the last 3 years, while dealing with hardware people (talking about machines in general, not electronics per se), is that they are somehow... half way between coders and artists. Many of them have problems understanding how git works, for example, even after years of using it. To a coder, you can say: yes it is an extra file, next to each regular file, but it contains only a few hundred bytes of data, and you only deal wit hit fully automated through the reuse-tool; and that will often convince them. With hardware people, this will not fly: "An additional file per each file in my repo!?!?! I will be confused, ..."

**Comment by mxmehl** [comment]
As the both of you, I would prefer not digging into this very deep rabbit hole. ODF and SVG may be doable, but there surely are files and attributes that would be much harder to parse. `.license` is a working solution, and we want to keep the tool maintainable and slim.

Regarding the refusal of too many extra files, we allow [DEP5](https://reuse.software/faq/#bulk-license) which would only require one additional directory and one file. We plan to offer a more flexible and user-oriented format (like `REUSE.yaml`) for this.

I'll close here because we won't "fix" that, but please feel free to continue the discussion if you like.
