### ISSUE TITLE
What do I do with lockfiles like Cargo.lock or flake.lock ?

### ISSUE THREAD

**Issue by 06kellyjac** [fsfe/reuse-tool#390]
What do I do with generated lockfiles? I know .gitignore-d stuff is ignored but I need them committed

**Comment by mxmehl** [comment]
You can just mark them with a separate `.license` file. In [this example](https://git.fsfe.org/reuse/api/src/branch/master/Pipfile.lock.license) we've just chosen CC0-1.0 as the most lax license as this is [not copyrightable probably](https://reuse.software/faq/#uncopyrightable).

**Comment by 06kellyjac** [comment]
Sure but when someone is marking down the licenses (e.g. when packaging for nixpkgs, or setting up licenses they allow with `cargo-deny`) they now have to put Apache 2.0 (and maybe MIT)  and CC0-1.0 which is a bit of  faff just for a lockfile

**Comment by mxmehl** [comment]
You could license this file under any license you want. It's probably not copyrightable at all. But for REUSE it's close to impossible to know what's copyrightable and what not. That is why we go the pragmatic way of requiring information for all files, no matter how small (except for 0-size files like symlinks).

If you would like to avoid .license files, you could also use dep5: https://reuse.software/faq/#bulk-license

**Comment by chrysn** [comment]
Note that comments in Cargo.lock are retained, so if SPDX comments are added below the top two comment lines, they just work and survive `cargo update`s.
