### ISSUE TITLE
Change of registration email address?

### ISSUE THREAD

**Issue by je-hal** [fsfe/reuse-tool#391]
We used https://api.reuse.software/register for our repo that is reuse compliant.

Maybe a stupid question, but I couldn't find the answer in the provided documentation/FAQ: 
Is there a way to change the email we provided for the registration, for example, if responsibilities change?

Thanks!

**Comment by mxmehl** [comment]
That is not possible unfortunately. Since there is no authentication, there currently is not defined way to update information.

However, you are free to [contact us](https://fsfe.org/contact/) and ask us to make this change if necessary.

Thanks for making your repos REUSE compliant!
