### ISSUE TITLE
vue file support for addheader

### ISSUE THREAD

**Issue by weeman1337** [fsfe/reuse-tool#395]
`.vue` files should be supported.

[The format is kind of similar to HTML](https://v3.vuejs.org/guide/single-file-component.html#what-about-separation-of-concerns)

**Comment by mxmehl** [comment]
Thanks for the suggestion. Seems to be pure HTML comments, so we can just connect the file extension with the existing HTML comment style.

**Comment by weeman1337** [comment]
I will have a look at this later.
