### ISSUE TITLE
Project status falsely shows as not compliant (github.com/SAP/openui5-sample-app)

### ISSUE THREAD

**Issue by matz3** [fsfe/reuse-tool#396]
The project status on the website shows as not compliant without any further information:
https://api.reuse.software/info/github.com/SAP/openui5-sample-app

When checking the project locally or via GitHub Actions, the projects is reported as compliant:
```
# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: Apache-2.0
* Read errors: 0
* Files with copyright information: 39 / 39
* Files with license information: 39 / 39

Congratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)
```

GitHub Actions check run: https://github.com/SAP/openui5-sample-app/runs/3217993847
Also see: https://github.com/SAP/openui5-sample-app/issues/113

**Comment by mxmehl** [comment]
Thanks for reporting this! It has been a spurious error with our [API server](https://git.fsfe.org/reuse/api-worker), more specifically Docker:

```
docker: Error response from daemon: endpoint with name SAP__openui5-sample-app__bd65ec5d already exists in network bridge.
```

A restart of the Docker daemon made the left-over artifact in the network bridge disappear. No idea how this could happen, but I will think about checks that will report this error shall it ever appear again.
