### ISSUE TITLE
Regression for files without permissions

### ISSUE THREAD

**Issue by nicorikken** [fsfe/reuse-tool#398]
I noticed an error when testing #347 but didn't think much of it. Turns out the behavior was fine in an earlier version of Reuse, so it is a regression.

### Test setup
Create a script file using super user privileges so it will be owned by root with only read permissions for reuse.
```
$ sudo touch test.sh
$ ls -la
-rw-r--r--  1 root root    0 aug  6 08:13 test.sh
```

### Old behavior
```
$ reuse --version
reuse 0.12.1
```
```
$ reuse addheader -c "mycorp" -l Apache-2.0 -y 2021  test.sh
usage: reuse addheader [-h] [--copyright COPYRIGHT] [--license LICENSE] [--year YEAR] [--style {applescript,aspx,bat,bibtex,c,css,f,haskell,html,jinja,jsx,lisp,m4,ml,plantuml,python,rst,tex}]
                       [--copyright-style {spdx,string,string-c,string-symbol,symbol}] [--template TEMPLATE] [--exclude-year] [--single-line] [--multi-line] [--explicit-license] [--skip-unrecognised]
                       path [path ...]
reuse addheader: error: argument path: can't write to 'test.sh'
```
```
$ reuse addheader -c "mycorp" -l Apache-2.0 -y 2021 --explicit-license test.sh
usage: reuse addheader [-h] [--copyright COPYRIGHT] [--license LICENSE] [--year YEAR] [--style {applescript,aspx,bat,bibtex,c,css,f,haskell,html,jinja,jsx,lisp,m4,ml,plantuml,python,rst,tex}]
                       [--copyright-style {spdx,string,string-c,string-symbol,symbol}] [--template TEMPLATE] [--exclude-year] [--single-line] [--multi-line] [--explicit-license] [--skip-unrecognised]
                       path [path ...]
reuse addheader: error: argument path: can't write to 'test.sh'
```

### New behavior
```
$ git log -n 1
commit d546b1449aea93ac1bffe677e430e1bc004c8435 (HEAD -> master, origin/master, origin/HEAD)
Author: Chris Wesseling <chris.wesseling@cwi.nl>
Date:   Wed Aug 4 18:01:15 2021 +0200

    Allow creating .license file for write-protected files (#347)
```
```
$ reuse --version
reuse 0.13.1.dev19+gd546b14
```
**Here** a regression is introduced as a stacktrace is presented rather than a neat error as shown previously.
```
$ reuse addheader -c "mycorp" -l Apache-2.0 -y 2021  test.sh
Traceback (most recent call last):
  File "/home/nico/Software/fsfe/reuse-tool/venv/bin/reuse", line 33, in <module>
    sys.exit(load_entry_point('reuse==0.13.1.dev19+gd546b14', 'console_scripts', 'reuse')())
  File "/home/nico/Software/fsfe/reuse-tool/venv/lib/python3.8/site-packages/reuse/_main.py", line 256, in main
    return parsed_args.func(parsed_args, project, out)
  File "/home/nico/Software/fsfe/reuse-tool/venv/lib/python3.8/site-packages/reuse/header.py", line 605, in run
    result += _add_header_to_file(
  File "/home/nico/Software/fsfe/reuse-tool/venv/lib/python3.8/site-packages/reuse/header.py", line 436, in _add_header_to_file
    with path.open("w", encoding="utf-8", newline=line_ending) as fp:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'test.sh'
```
It doesn't occur when using the `--explicit-license` flag.
```
$ reuse addheader -c "mycorp" -l Apache-2.0 -y 2021 --explicit-license test.sh
Successfully changed header of test.sh.license
```
```
$ ls -la
...
-rw-r--r--  1 root root    0 aug  6 08:13 test.sh
-rw-rw-r--  1 nico nico   72 aug  6 08:19 test.sh.license
```

I'm not sure if this is caused by #347 From the code this didn't seem likely. I'll have to take another look at this. Perhaps @CharString you noticed this too?

**Comment by nicorikken** [comment]
I tried rolling back #347 and that didn't solve it, so this was introduced previously. Rather than trying to pinpoint the error I might just look into solving it.

**Comment by mxmehl** [comment]
I can confirm that this is a regression introduced by #347.

The previous commit ece4db2 works well in this test case (while it of course fails with `--explicit-license` which is what the PR tried to solve).

**Comment by nicorikken** [comment]
Hmm, somehow I came to a different conclusion earlier. I again tried it and now indeed @mxmehl I get the same conclusion.

**Comment by nicorikken** [comment]
It seems the relaxed argument `type=PathType("r")` instead of `type=PathType("r+")` is causing issues with other functions. Therefore a check would have to be implemented to ensure correct permissions for uses other than `--explicit-license`, probably just when trying to write to the file.

**Comment by CharString** [comment]
I haven't noticed, as these cases weren't represented in the tests. But I was afraid untested cases like this on could exist. That's why I tried to generate all imaginable combinations of file permission using hypothesis. But I got stuck trying to use the pytest fixtures with those tests.

**Comment by nicorikken** [comment]
@CharString No hard feelings here. I also overlooked this when reviewing. I'd say let's see if we can fix this soon, before we need to revert.

**Comment by nicorikken** [comment]
Something like `if os.access(path, os.W_OK):` would probably work as a test before modifying the file.

**Comment by nicorikken** [comment]
We could extend `_determine_license_path(path)` function to check if the original file can be written and otherwise an explicit `.license` file will be used.
https://github.com/fsfe/reuse-tool/blob/4af8dd2afd1b0cad33fa58ededad26a9b9506dbd/src/reuse/_util.py#L145-L152
Called in https://github.com/fsfe/reuse-tool/blob/4af8dd2afd1b0cad33fa58ededad26a9b9506dbd/src/reuse/header.py#L541

**Comment by nicorikken** [comment]
Turns out there are already some check functions in place:
https://github.com/fsfe/reuse-tool/blob/4af8dd2afd1b0cad33fa58ededad26a9b9506dbd/src/reuse/_util.py#L249-L299

**Comment by CharString** [comment]
@mxmehl I overlooked @nicorikken's pr #400 as it didn't reference this issue (#398), just the pr that caused the regression (#347). I [reviewed](https://github.com/fsfe/reuse-tool/pull/400#pullrequestreview-768977372) the differences and adopted what was better into #418.

**Comment by mxmehl** [comment]
Thank you! #418 looks good to me and a bit better than #400. If @nicorikken agrees, I'd merge the former.
