### ISSUE TITLE
In python files reuse tool should accept the info in `__copyright__` and `__license__` variables.

### ISSUE THREAD

**Issue by KOLANICH** [fsfe/reuse-tool#403]
Evaling must not be used. Use `ast.parse` and `ast.literal_eval`.

https://www.python.org/dev/peps/pep-0639/#in-python-code-files for more info

**Comment by mxmehl** [comment]
Thanks for the suggestion. We decided to not support this to not complicate things too much.

Please see https://github.com/fsfe/reuse-tool/issues/68#issuecomment-1019229607
