### ISSUE TITLE
Can’t specify license for files in the LICENSES/ folder

### ISSUE THREAD

**Issue by Jayman2000** [fsfe/reuse-tool#410]
# Context
Parts of CC0-1.0’s text are available under CC0-1.0. The rest of its text is licensed under CC-BY-4.0. See:

- https://github.com/creativecommons/creativecommons.org/issues/1212
- https://github.com/creativecommons/creativecommons.org/issues/1218

The spec says,
> A Project MUST include a License File for every license under which files in the Project are licensed.

(“[REUSE Specification – Version 3.0](https://reuse.software/spec/)” by [the Free Software Foundation Europe](https://fsfe.org/) is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/))

This means that if I want to use CC0-1.0 for any of the files in my project, then I have to also include CC-BY-4.0.

# Problem
When I run `reuse lint`, it tells me that CC-BY-4.0 is unused, even though I’m using it for `LICENSES/CC0-1.0.txt`.

[Minimum reproduction project.zip](https://github.com/fsfe/reuse-tool/files/7123725/Minimum.reproduction.project.zip)

**Comment by mxmehl** [comment]
Ah, you don't need to license your license files according to the [REUSE spec](https://reuse.software/spec/#copyright-and-licensing-information):

> Each file in the Project MUST have Copyright and Licensing Information associated with it, except the following files:
> 
> * The License Files.
> ...

I hope that clears things up :)

**Comment by Jayman2000** [comment]
> Ah, you don't need to license your license files according to the [REUSE spec](https://reuse.software/spec/#copyright-and-licensing-information):

I’m not sure that I agree. What do you mean by “to license”?

The way I read the spec, Copyright and Licensing Information isn’t required for all files. The sentence you quoted explicitly excludes some files from that requirement. The License File requirement, however, is separate. The sentence I quoted doesn’t exclude any files. There probably should be an exclusion for both (I’ll open an issue on the docs repo).

--------

While I agree that the spec doesn’t require me to include Copyright and Licensing Information for License Files, the spec doesn’t say that I can’t. The question here is: should reuse-tool allow me to do this, even though the spec doesn’t require it?

**Comment by mxmehl** [comment]
Well, I understand your general point, but I'd find it extremely hard to distinguish between the licenses for the actual code files and potential licenses for license texts. Also see this line of the spec:

> A Project MUST NOT include License Files for licenses under which none of the files in the Project are licensed.

The benefit of just having license texts for licenses which normal files (ex `LICENSES/`) are licensed under has the large benefit that a human or tool can see at first glance what licenses are effectively used.
