### ISSUE TITLE
Evaluating "main" license

### ISSUE THREAD

**Issue by hoijui** [fsfe/reuse-tool#417]
Given a project in a local git repository, I would like to know the "main" license of that project.
Before knowing REUSE, I would just have shoved the LICENSE file into a tool that recognizes many of the known licenses, and be done with it. Now, I do not eve know anymore, if a concept like "main license" makes sense.
In an example project of mine, do this:

```bash
reuse spdx | grep LicenseInfoInFile | sed -e 's|.*: ||g' | sort | uniq -c | sort -n
      2 CC0-1.0
     10 Unlicense
     26 GPL-3.0-or-later
```

It is a software project with 26 source files.
For a human, it is clear: this is a `GPL-3.0-or-later` project.
The other two licenses are used for "README.md", ".gitignore", CI related and build files.

Technically, or for a machine, I would consider this a quite hard thing to figure out. How do the licenses compare to each other, and which files in the project are more important then others, and so on. Is there a solution for this, or would you say... the concept of "main license" should be abolished all-together?

**Comment by mxmehl** [comment]
> Is there a solution for this, or would you say... the concept of "main license" should be abolished all-together?

That's more or less the conclusion we came to, for the reasons you've stated. Communicating a "main license" may lead to the wrong impression that perhaps all files (or except one or two) is under this license. But your example shows that the ratio can also be different. Just from the numbers, I cannot say that GPL-3.0-or-later is your "main license". What if these 26 files were just one folder full of small icons under this license, and giant creative code is in the 10 files under "Unlicense"?

Such a term is very hard to define: number of files? lines of code?

With this very repo, we chose to give an overview for humans in the README file:

```
## License

This work is licensed under multiple licences. Because keeping this section
up-to-date is challenging, here is a brief summary as of April 2020:

- All original source code is licensed under GPL-3.0-or-later.
- All documentation is licensed under CC-BY-SA-4.0.
- Some configuration and data files are licensed under CC0-1.0.
- Some code borrowed from
  [spdx/tool-python](https://github.com/spdx/tools-python) is licensed under
  Apache-2.0.

For more accurate information, check the individual files.
```

So I'd take the liberty to close this issue, unless someone has
1. An actual use case where a main license is important for the re-usability and simplicity of licensing and copyright of software.
2. A good idea how to put that in a spec (which is understandable by average humans) and in the tool.

Anyway, thanks for the suggestion, @hoijui!
