### ISSUE TITLE
Not only comments are scanned

### ISSUE THREAD

**Issue by hoijui** [fsfe/reuse-tool#429]
The reuse tool fails to scan the following BASH file because of the `echo "SPDX-...` lines,
no matter whether the file is called `tst`, `tst.sh` or `tst.bash`.

```bash
#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 John Doe
#
# SPDX-License-Identifier: CC0-1.0

AUTHOR="John Doe"
LICENSE="CC0-1.0"

{
	echo "<!--"
	echo "SPDX-FileCopyrightText: $(date +'%Y') $AUTHOR"
	echo
	echo "SPDX-License-Identifier: $LICENSE"
	echo "-->"
	echo
	echo "# My Project"
} > /dev/null # In reality there would be a file-name here,
              # but we are not interested in the output of this script,
              # only in the effect of scanning this script with the reuse tool
```

As the prefix to the trouble-some lines is `	echo "`,
which is not a valid comment line in any format,
I imagine it should be technically possible to make this work,
at least in theory.

**Comment by Potherca** [comment]
Regarding PHP, I'd say: start supporting the most common use-cases first and incrementally add more if/when people start complaining. 

I think HTML based PHP templates should probably be mostly left alone, as the developer will have to decide for themselves if they want HTML or PHP comment regarding their copyright...

The most common use-case of modern PHP would be class files. I'd suggest a file-level doc-block should suffice:

```php
<?php 
/**
 * SPDX-FileCopyrightText: <year> <author>
 * SPDX-License-Identifier: <license>
 */
```

That would also make it possible to re-use/extend such a doc-block with other PhpDocumentor tags.

**Comment by mxmehl** [comment]
Would be solved by #463

**Comment by linozen** [comment]
> Would be solved by #463

@mxmehl Now, that #463 is merged, can this be closed here as well?

**Comment by mxmehl** [comment]
Absolutely, that is the next best solution for these kinds of issues.

**Comment by hoijui** [comment]
Users running into the problem like I do here,
will not know about this solution,
except they stumble upon this issue or other docu.
That is not very likely, so... how can we change that?

**Comment by floriansnow** [comment]
@hoijui It's in the official documentation: https://reuse.readthedocs.io/en/stable/usage.html#ignoring-parts-of-a-file
