### ISSUE TITLE
lint not working properly

### ISSUE THREAD

**Issue by cncoulter** [fsfe/reuse-tool#435]
I just started making a new Jekyll website, and I believe I've made the project REUSE-compliant. `reuse lint` disagrees.

Jekyll builds the site to `_site/`. My `.gitignore` file looks like this:

```
# SPDX-FileCopyrightText: 2021 Cam Coulter <git@camcoulter.com>
# SPDX-License-Identifier: CC0-1.0

_site/
.sass-cache/
.jekyll-cache/
.jekyll-metadata
```

Here's what I get when I run `reuse lint`:

```
reuse._util - ERROR - Could not parse 'AGPL-3.0-or-later\r\n */\r\n\r\nbody {\r\n  background: white;\r\n  color: black;\r\n  font-family: sans-serif;\r\n}\r\n\r\na:focus {\r\n\toutline: 2px solid;\r\n\toutline-offset: 1px;\r\n}\r\na:hover {\r\n\ttext-decoration: none;\r\n}\r\n"'
reuse.project - ERROR - '_site/assets/css/main.css.map' holds an SPDX expression that cannot be parsed, skipping the file
# UNUSED LICENSES

The following licenses are not used:
* CC-BY-SA-4.0


# MISSING COPYRIGHT AND LICENSING INFORMATION

The following files have no copyright and licensing information:
* _site/404.html
* _site/About-This-Site/ReadMe/index.html
* _site/About-This-Site/index.html
* _site/assets/css/main.css.map
* _site/index.html
* _site/redirects.json
* _site/robots.txt
* _site/sitemap.xml


# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses: CC-BY-SA-4.0
* Used licenses: AGPL-3.0-or-later, CC0-1.0
* Read errors: 0
* Files with copyright information: 13 / 21
* Files with license information: 13 / 21

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

1. I don't understand the error at the top of that. Any thoughts?
2. `_site/` is in my `.gitignore` file, so why am I getting these no copyright errors?

For reference, here's the project that I'm working on: <https://github.com/cncoulter/camcoulter.com>. I am running Fedora 34. The command `python3 --version` yields `Python 3.9.7`, and I installed reuse with this command: `pip3 install --user reuse`

Guidance or help would be appreciated. Is this an issue with my code, my installation, or the project itself? Please let me know if I should provide additional info.

**Comment by seabass-labrax** [comment]
This is a really top-quality bug report; thank you for all the extra information @cncoulter :)

I'd say this is a bug in the REUSE tool - the Git command which the tool runs to see if files are ignored includes the `--others` flag, which means that files that aren't tracked in Git are still checked with REUSE, even if they are in `.gitignore`. I may be missing a reason why this flag is important; @carmenbianca would know better than I do!

https://github.com/fsfe/reuse-tool/blob/60c0986bb24a3b482ee0527e9195f7c23cadb003/src/reuse/vcs.py#L82-L95

To bypass the problem, just run `jekyll clean` in your repository before running the REUSE tool. This will delete the `_site/` files, which are automatically generated by Jekyll when building the site and so can be regenerated when you need them :)

**Comment by carmenbianca** [comment]
> I may be missing a reason why this flag is important; @carmenbianca would know better than I do!

I believe the intention of adding that flag was to have somewhat consistent behaviour between repository directories and non-repository directories. That, and being able to run `reuse lint` before `git commit` (maybe using pre-commit?), but I'm not sure if `git add`ed files would count as 'tracked by git' for the purpose of `git ls-files`.

Having to do `jekyll clean` before every lint run would be fairly annoying, though, so there's a use case for removing `--others`. Maybe we could do something like `reuse --only-tracked-files lint`? Argument name WIP.

**Comment by mxmehl** [comment]
Thanks for the report. I cloned your repo, but although `_site/` is ignored, there are files in there. So it seems you checked in and commited them once, and only afterwards ignored them. So a solution would be is to delete (and commit) the containing files again, and make sure they disappear from the public repo.

The error on the top is because the SPDX expression has been minified and therefore is not fully comprehensible for the tool (because of the `\r\n at the end probably`). In this case, I recommend to add a `.license` file. But since it's in `_site`, it should be solved by the step above anyway I think.

Then, last but not least, you should delete `LICENSES/CC-BY-SA-4.0.txt`. No file in your repo uses this license which breaks the [specification](https://reuse.software/spec/#license-files).

Does that solve it?

**Comment by cncoulter** [comment]
Oh, okay, that makes sense. Yes, I had previously committed files in `_site/`.

I just removed those files and committed that, and that did solve the issue. The reuse tool now tells me the project is compliant. Thank you all!

I had thought updating the `.gitignore` file would be enough to make the reuse tool ignore those files. I didn't realize the tool would notice and test files I had previously committed and then ignored. That makes sense though I guess. Good to know! Thanks again!

**Comment by mxmehl** [comment]
Great! Actually, the "error" is not on the REUSE side but git's logic. Anyway, happy that it's resolved :)

**Comment by seabass-labrax** [comment]
@mxmehl, ah, you're right: I didn't think to check whether `_site/` was tracked - my bad! Glad to hear it's all resolved for @cncoulter. Is there any action needed then, either on REUSE or Git's side? It probably does make sense for REUSE to check tracked files as they will be distributed with the Git repository, but if there's something that could be improved with Git I can take it upstream :)

**Comment by cncoulter** [comment]
Now that I better understand how it works, I'm not sure any code changes need to be made. That said, perhaps we could update REUSE's tutorial or FAQ to state that REUSE will check files that are tracked by git? For example, adding this line to the FAQ would have helped me out:

The REUSE tool will also check tracked files, so if you commit a file and later update `.gitignore` to ignore it, you will also need to remove that file from git and commit that change.
