### ISSUE TITLE
`reuse addHeader` broken for PHP

### ISSUE THREAD

**Issue by Potherca** [fsfe/reuse-tool#436]
When calling `reuse addheader` on PHP files the comment header is placed _outside_ the `<?php` tag, which is incorrect.

To demonstrate, assume we have an example file with this content:
```php
<?php

// some code here
```

Then this happens:

## Multiline Comment

<table>
<tr><td>Command</d><td>

`reuse addheader --license="MIT" ./example.php --multi-line`

</d></tr>
<tr><td>Expected</d><td>

  ```php
  <?php

  /*
   * SPDX-License-Identifier: MIT
   */
  ```

</d></tr>
<tr><td>Actual</d><td>

  ```php
   /*
    * SPDX-License-Identifier: MIT
    */

   <?php
   ```

</d></tr>
</table>

## Single line Comment

<table>
<tr><td>Command</d><td>

`reuse addheader --license="MIT" ./example.php`

</d></tr>
<tr><td>Expected</d><td>

 ```php
 <?php

// SPDX-License-Identifier: MIT
 ```

</d></tr>
<tr><td>Actual</d><td>

```php
// SPDX-License-Identifier: MIT

 <?php
 ```

</d></tr>
</table>

**Comment by pfefferle** [comment]
There might be an other case, where the PHP file does not start with an opening PHP tag, like for example template files: https://github.com/pfefferle/wordpress-activitypub/pull/148/files#diff-b3a77875bda59f2c2629f9c70326b1a6388d38c2685c7b34180217dc5bae4c56

**Comment by Potherca** [comment]
@pfefferle For files that do not start with a `<?php` opening tag, the current rendering may indeed be incorrect... 

The "comment" would not actually be a comment, but appear in the HTML page text. This is because the "comment" would not be commented out by PHP as it is not inside any PHP tags.

I don't know how this should be resolved, as adding a HTML comment might not be what the user wants, but cramming the comment into the first `<?php` tag in the file also seems a bad choice. (Not even getting into `<?=` shorttags here...)

However, is this bug were fixed, is would be trivial to resolve for cases where  PHP is used as HTML template... One could simply make sure there always is a `<?php ?>` at the top of each template file to contain the comment...

**Comment by carmenbianca** [comment]
The solution should be to simply add `<?php` to the same list that currently contains the `#!` hashbang.

I can do this thursday if someone else hasn't done it yet.

**Comment by pfefferle** [comment]
@carmenbianca that will fix the problem with classes, that starts with `<?php` but not for templates that have inline PHP code.

@Potherca I think I would check if the file starts with `<?php` otherwise I would add a the `<?php ?>` including the meta-infos.

**Comment by Potherca** [comment]
> I think I would check if the file starts with `<?php` otherwise I would add a the `<?php ?>` including the meta-infos.

That seems like a fair solution to me :+1:
