### ISSUE TITLE
can't detect license in pom.xml 

### ISSUE THREAD

**Issue by bjk7119** [fsfe/reuse-tool#437]
I used reuse-tool to check to find license in pom.xml

But even if there is license in pom.xml, there is no license in SUMMARY at the end of running.

Is this normal?

I tested with 'javamail' source code
(https://github.com/javaee/javamail) 

< Run >
`jaekwonbang-desktop:~/javamail$ reuse lint`

< Result >
` # SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses:
* Read errors: 0
* Files with copyright information: 598 / 657
* Files with license information: 0 / 657

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-( `

**Comment by mxmehl** [comment]
Just to be clear, do you mean [this file](https://github.com/javaee/javamail/blob/8106b9dd15e917da63e96c33f8c6aea1cad40045/pom.xml)?

Within the file, I cannot find `SPDX-License-Identifier`. That is what the REUSE tool is looking for. See the corresponding [specification section](https://reuse.software/spec/#comment-headers).

**Comment by bjk7119** [comment]
I understood your words.
Thank you.
