### ISSUE TITLE
Licenses retrieved via `reuse download` lack word wrap

### ISSUE THREAD

**Issue by mara004** [fsfe/reuse-tool#438]
It is common to use word wrap at 80 characters for license files, to ensure that the text also displays correctly on smaller screens or in editors that do not use dynamic wrap by default. Many projects insist on this, since it's legal information that should be shown in an obvious form.

This is not the case for licenses from [`spdx/license-list-data`](https://github.com/spdx/license-list-data). It would be nice if these could use word wrap, and possibly adapted indentation.

**Comment by mxmehl** [comment]
I am not sure what's SPDX's rationale behind this, but @goneall may.

In any case, we currently see no other provider for SPDX license texts that would also match this criterion, so I'll have to refer you to upstream, sorry.

If you want to fix it yourself, you are free to wrap the downloaded text files yourself, or even download them from the original source (e.g. gnu.org), as long as the name is retained. REUSE does not mandate a specific format.

**Comment by mara004** [comment]
> so I'll have to refer you to upstream

Upstream does not have an issues panel, that's why I reported it here...

> If you want to fix it yourself, you are free to wrap the downloaded text files yourself, or even download them from the
> original source (e.g. gnu.org), as long as the name is retained. REUSE does not mandate a specific format.

Yeah, I'll do this. Thank you.

**Comment by mxmehl** [comment]
> > so I'll have to refer you to upstream
> 
> Upstream does not have an issues panel, that's why I reported it here...

Ah, right. Perhaps this would be the best place then? https://github.com/spdx/license-list-XML/

Otherwise, SPDX folks are rather responsive via their mailing lists, so that may be another place to ask. Thank you for your understanding!

**Comment by goneall** [comment]
> Upstream does not have an issues panel, that's why I reported it here...

@mara004 We don't accept issues at the [license-list-data](https://github.com/spdx/license-list-data) repo since that repo is automatically generated.  As @mxmehl mentioned above, the best place to add issues is in the source data for the generated repo: [license-list-XML](https://github.com/spdx/license-list-XML/issues).  If you think the issue is related to the generation of the data, you can add an issue to the [licenseListPublisher](https://github.com/spdx/licenselistpublisher) - this is the utility that generates the data.

**Comment by goneall** [comment]
> It is common to use word wrap at 80 characters for license files, to ensure that the text also displays correctly on smaller screens or in editors that do not use dynamic wrap by default.

For the upstream data, there is a requirement that we copy the license text exactly as written by the originator of the license text including formatting text.  The original text is stored in the [test/simpleTestForGenerator](https://github.com/spdx/license-list-XML/tree/master/test/simpleTestForGenerator)  directory.  If the original text is HTML, we respect the `<br/>` as the formatting text which may be why you are seeing a lot of unwrapped text.  

If you run across any text where the original text is word wrapped and the license-list-XML text is not, a pull request to fix this would be more than welcome by the SPDX community - just include a URL reference to the original text in the pull request.  If the original text is not word-wrapped, then we would probably leave the text as is.

**Comment by mara004** [comment]
> If you run across any text where the original text is word wrapped and the license-list-XML text is not, a pull request to fix this would be more than welcome by the SPDX community

The [Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0.txt), for example. I plan to make an MR when I have more time.

**Comment by mxmehl** [comment]
Thanks for jumping in @goneall!

This issue remains closed, but please feel free to continue the exchange here.

**Comment by mara004** [comment]
Same for [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode.txt) or any other Creative Commons licenses. The official text versions have the same URLs as the html ones, only the suffix needs to be changed to `.txt`.
