### ISSUE TITLE
Cannot detect copyright

### ISSUE THREAD

**Issue by dd-jy** [fsfe/reuse-tool#440]
I tested lint mode with the below file. 
And it cannot detect the copyright even though the header of the file includes the copyright text.
If 'copyright' and '(c)' are written no leaving space, it is not recognized as copyright.
Please fix it.
```
/*
 * ============================================================================
 * @Project       : test project
 * @Version       : v1.0.0
 *
 * Copyright(c) 2012 TEST All rights reserved
 */

```

**Comment by bjk7119** [comment]
@mxmehl 
Is there any progress on this issue?

**Comment by mxmehl** [comment]
No, but it should be relatively easy to fix. With the bug label it is likely that this gets fixed before the next release.
