### ISSUE TITLE
Add CC-BY-ND-3.0-DE, which is already a SPDX supported license

### ISSUE THREAD

**Issue by Darneas** [fsfe/reuse-tool#441]
Sorry, if I am not following the process correctly, this is my first contribution.

I directly filed #439 without creating an issue, as this is such a simple change, but maybe you want this here for discussing it?

**Comment by mxmehl** [comment]
Oh yes, sorry for not following up.

Usually, we bump the SPDX list of licenses and expressions just before a release. This is done with `make bump-resources`:

https://github.com/fsfe/reuse-tool/blob/4ce4c5fe2976536e9f2911048f1b6b308fa191ee/Makefile#L124-L129

We could create a minor release if it's really urgent.

**Comment by Darneas** [comment]
No worries.

That also means my PR makes no sense, shall I close it?

When do you estimate the next release to happen? I am relying on the reuse Docker hub images, so the release ideally incorporates an update there as well (otherwise I anyhow have to create a custom image and then I could also add the licenses to my fork).

It is not urgent, as I am waiting for this to get resolved first: https://github.com/clearlydefined/service/issues/883#issuecomment-991176388

**Comment by mxmehl** [comment]
Fixed with today's release.
