### ISSUE TITLE
Add --style for ascidoc files (.adoc)

### ISSUE THREAD

**Issue by nirs** [fsfe/reuse-tool#444]
ascidoc uses // like c:
https://docs.asciidoctor.org/asciidoc/latest/comments/

**Comment by mxmehl** [comment]
We already have `.asciidoc` as file extension, so one should just add `.adoc` beneath it.

https://github.com/fsfe/reuse-tool/blob/4ce4c5fe2976536e9f2911048f1b6b308fa191ee/src/reuse/_comment.py#L465

**Comment by nirs** [comment]
@mxmehl I see this was already done in #386:
https://github.com/fsfe/reuse-tool/commit/858580dacb2666935dd652b1e8c996063513f184

But this is not included in the latest release (0.13.0) that was is June. Maybe it is time to 
release a new version?

**Comment by nirs** [comment]
Issue already resolved in #386, waiting for 0.14.0.

**Comment by mxmehl** [comment]
The new version has just been released :)
