### ISSUE TITLE
Provide an aarch64 container with reuse

### ISSUE THREAD

**Issue by zyga** [fsfe/reuse-tool#449]
The `fsfe/reuse` container is only available for amd64. It would be useful to have an aarch64 build as well. 

https://hub.docker.com/r/fsfe/reuse/tags

**Comment by mxmehl** [comment]
Sure, we could do that as GH actions support building those.

In the long run, we'd like to switch the repo to https://git.fsfe.org and our Drone CI. There, we currently only have runner on amd64 machines. If we had access to an arm64 machine, we could surely also build it there.
