### ISSUE TITLE
reuse-tool only allows inclusion of the abbreviated LGPL

### ISSUE THREAD

**Issue by ferdnyc** [fsfe/reuse-tool#452]
The version of the LGPL that `reuse download` retrieves, and the version it accepts in the `LICENSES` directory, is written as an _addendum_ to the GPL-3.0 rather than as a complete license statement.

Quoting from the document itself,
 

> This version of the GNU Lesser General Public License incorporates the terms and conditions of version 3 of the GNU General Public License, supplemented by the additional permissions listed below.
> 
> 0. Additional Definitions.
> 
> As used herein, "this License" refers to version 3 of the GNU Lesser General Public License, and the "GNU GPL" refers to version 3 of the GNU General Public License.

> 
> 1. Exception to Section 3 of the GNU GPL.
> You may convey a covered work under sections 3 and 4 of this License without being bound by section 3 of the GNU GPL.
> 
> 2. Conveying Modified Versions.
> If you modify a copy of the Library, and, in your modifications, a facility refers to a function or data to be supplied by an Application that uses the facility (other than as an argument passed when the facility is invoked), then you may convey a copy of the modified version:
> 
>      a) under this License, provided that you make a good faith effort to ensure that, in the event an Application does not supply the function or data, the facility still operates, and performs whatever part of its purpose remains meaningful, or
> 
>      b) under the GNU GPL, with none of the additional permissions of this License applicable to that copy.
> 
> 3. Object Code Incorporating Material from Library Header Files.
> The object code form of an Application may incorporate material from a header file that is part of the Library.  You may convey such object code under terms of your choice, provided that, if the incorporated material is not limited to numerical parameters, data structure layouts and accessors, or small macros, inline functions and templates (ten or fewer lines in length), you do both of the following:
> 
>      a) Give prominent notice with each copy of the object code that the Library is used in it and that the Library and its use are covered by this License.
> 
>      b) Accompany the object code with a copy of the GNU GPL and this license document.
> 

But if I use `reuse download GPL-3.0-or-later` to include the requisite copy of the GPL itself, `reuse lint` now fails validation:

```sh
$ reuse lint
# UNUSED LICENSES

The following licenses are not used:
* GPL-3.0-or-later


# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses: GPL-3.0-or-later
* Used licenses: BSD-3-Clause, CC-BY-3.0, CC0-1.0, LGPL-3.0-or-later, MIT
* Read errors: 0
* Files with copyright information: 278 / 278
* Files with license information: 278 / 278

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

The FSF publishes a combined copy of the LGPL+GPL here: https://www.gnu.org/licenses/lgpl+gpl-3.0.txt

Perhaps that's what `reuse download LGPL-3.0-or-later` should download and include in the `LICENSES/` directory. Or, alternately, it could just expect a copy of `GPL-3.0-or-later.txt` to accompany `LGPL-3.0-or-later.txt`. Because without a copy of the GPL, the LGPL on its own is worthless.

**Comment by seabass-labrax** [comment]
Welcome @ferdnyc and thank you for opening this issue :) The combined copy (LGPL+GPL) was in fact published for this reason - we had a discussion in issue #86 about this recently and @mxmehl contacted the FSF about adding the combined version.

The plan was for SPDX (I'm a member of the SPDX Working Group, for context) to add the entirety of the GPL as an optional section in the SPDX License List's XML for the LGPL. However, the SPDX Legal Team has had quite a lot on the agenda recently, so that discussion has been delayed. It would be good to have @silverhook and/or @mxmehl on one of the upcoming SPDX Legal Team meetings so that we can move this forward. You are most welcome to join the meetings yourself if you would like, @ferdnyc! :)

Hope this explains things; let me know if I haven't explained something.

**Comment by ferdnyc** [comment]
@seabass-labrax Ah, thanks for letting me know! Apologies for overlooking #86, as this is a duplicate of that issue I'll close it and any discussion can continue over there.

**Comment by seabass-labrax** [comment]
@ferdnyc, right'o! Off-topic comment incoming - I've just noticed that you're an OpenShot developer. Thank you! It's the video editor I use :)

**Comment by silverhook** [comment]
>  It would be good to have @silverhook and/or @mxmehl on one of the upcoming
> SPDX Legal Team meetings so that we can move this forward.

I haven’t been on an SPDX call in a long time, due to them unfortunately 
clashing with a team call at work. If you get it on the agenda and let me know 
when it happens, happy to (try) to make time for it.

**Comment by swinslow** [comment]
Thanks @seabass-labrax for the ping -- yes, I meant to send the note out to the SPDX Legal email list over the weekend but didn't manage to. I'll make it happen today  :)

**Comment by swinslow** [comment]
Okay: https://lists.spdx.org/g/Spdx-legal/message/3068

**Comment by mxmehl** [comment]
Great, thanks for the discussion and summary! Let's discuss this further on the list :)
