### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#459]
More and more projects are making this change, and it's probably a good new default.

I suspect that this has some knock-on effects here and there. Good first issue, not very high priority.

Try this in a repo of a user/group that _isn't_ @fsfe first.

**Comment by Arghya-Banerjee** [comment]
Can I get assigned to this task?

**Comment by carmenbianca** [comment]
@Arghya-Banerjee By all means, feel free :)

How did you happen to come across this repo/issue, as a curiosity?

**Comment by Arghya-Banerjee** [comment]
Thanks. I was just finding dome issues that are beginner friendly in python language.
I am starting to learn to contribute to open source repos thus I got this to try my hands on.
