### ISSUE TITLE
Rename Mary Sue to Jane Doe

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#460]
I'm not super happy with Mary Sue as the example person in a lot of tests. At the time I wrote this, 'Mary Sue' was a bit of a running gag in a subculture I was in, understood as [the Wikipedia definition](https://en.wikipedia.org/wiki/Mary_Sue):

> A Mary Sue is a type of fictional character, usually a young woman, who is portrayed as unrealistically free of weaknesses. Originating in fan fiction, a Mary Sue is often an author's idealized self-insertion.

Since then, or maybe even at the time, people have begun to use the name as almost synonymous to 'any (strong) female character I don't like'. That leaves a sour taste in my mouth, and I'd rather just rename Mary Sue in this code base.

**Comment by GemedetAdept** [comment]
Hello! I've gone ahead and found all the instances of "Mary Sue," and replaced them with "Jane Doe."

**Comment by GemedetAdept** [comment]
My apologies, I didn't see that a pull request for this issue had already been submitted. I'll keep that in mind going forward, I'm still learning the ropes.

**Comment by carmenbianca** [comment]
No worries @GemedetAdept Thank you for giving it a shot :)

As a curiosity, how did you and @Gri-ffin come across this issue/repository?

**Comment by GemedetAdept** [comment]
I've been looking around for issues that I'd feel confident in resolving, and I happened across this repository. It stuck out to me as being perfect for a first issue, and it is! Going through the process of working on an issue is fantastic practice, so I'm glad either way.

**Comment by carmenbianca** [comment]
@GemedetAdept Ah, awesome! I think you'd quite like #467 as a different first issue, if you have a little knowledge of Python and can replace `requests.get()` with `urllib.request.urlopen()` (probably).

**Comment by GemedetAdept** [comment]
@carmenbianca Duly noted, thank you! I'll give it a look.
