### ISSUE TITLE
Introduce marking a block that lint ignores

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-tool#463]
Users should be able to mark a block that `reuse lint` ignores. This would solve the problem that users experience when they use the word "copyright" or even the strings "SPDX-License-Identifier" or "SPDX-FileCopyrightText" somewhere in the file without actually meaning to provide REUSE-related information.

Simplified example from #70:

```sh
#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2021 John Doe
#
# SPDX-License-Identifier: CC0-1.0

echo "SPDX-FileCopyrightText: $(date +'%Y') Jane Doe" > file.txt
echo "SPDX-License-Identifier: MIT" > file.txt

exit 0
```

This would lead the the following error when running `lint`:

```
$ reuse lint
reuse._util - ERROR - Could not parse 'MIT" > file.txt'
reuse.project - ERROR - 'foobar.sh' holds an SPDX expression that cannot be parsed, skipping the file
# MISSING COPYRIGHT AND LICENSING INFORMATION

The following files have no copyright and licensing information:
* foobar.sh
[...]
```

In a sprint we had the idea to define a begin/end string that marks blocks that are to be ignored by `lint`. E.g.:

```sh
#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2021 John Doe
#
# SPDX-License-Identifier: CC0-1.0

# REUSE-IGNORE-BEGIN
echo "SPDX-FileCopyrightText: $(date +'%Y') Jane Doe" > file.txt
echo "SPDX-License-Identifier: MIT" > file.txt
# REUSE-IGNORE-END

exit 0
```

## To discuss

- [x] Define the exact Begin/End strings. Check whether SPDX provides them
- [x] Does it require a specification change?

**Comment by silverhook** [comment]
I see both reasons for it (as you described) and potential for people to abuse it.

But it’s not our job to make the spec idiot-proof, only reasonable. If someone goes out of the way to mucks it up on how to mark their own (project’s) code, that’s on them.
