### ISSUE TITLE
Better error message for unparsable copyright/license info

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-tool#465]
In the example in #463, people will see the following error, even if the block ignore is implemented:

```
reuse._util - ERROR - Could not parse 'MIT" > file.txt'
reuse.project - ERROR - 'foobar.sh' holds an SPDX expression that cannot be parsed, skipping the file
```

The suggestion is to make this error more understandable and solvable for users:

1. Collect these errors, and only display them near the summary block
2. Combine and explain these errors in a better fashion, e.g. "The files contain text strings that confuse the REUSE tool. It cannot reliably understand what's the actual license and/or copyright. Please see $URL for an explanation and solution."
3. Create the FAQ item ($URL) that explains the source of problem, and that people shall wrap the problematic lines in the block ignores (#463).

**Comment by carmenbianca** [comment]
I think this is semi-distantly related to #4

**Comment by mxmehl** [comment]
True. Will copy my suggestions there, thanks for finding this!
