### ISSUE TITLE
Get rid of dependency on requests

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#467]
The requests library is thusly sparsely used in this project that it's probably nicer to just use the Python standard library here.

**Comment by carmenbianca** [comment]
@GemedetAdept mentioned they'd look at this :)

**Comment by yonMaor** [comment]
Hey, I'd like to help here, can you eleborate further on this issue?

**Comment by GemedetAdept** [comment]
> @GemedetAdept mentioned they'd look at this :)

I'm currently working on this and making steady progress! As I work on this issue, I'll do my best to properly test the changes (using an isolated "sandbox" python file). 

That said, I'm sure there will be edge cases that I miss. But that's a bridge for me to cross later — a bridge that's 10 ft. under the water, but a bridge nonetheless.

**Comment by nicorikken** [comment]
@GemedetAdept I see you pushed some initial work https://github.com/GemedetAdept/reuse-tool/commits/%23467 but it seems activity has stalled. Is there anything you could use help with?
