### ISSUE TITLE
One of those nice badges in the README is broken

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#471]
See image

![Ekrankopio de 2022-01-22 16-41-54](https://user-images.githubusercontent.com/12065945/150645419-11a2db52-b0d6-40cb-999f-e72157c7a24d.png)

**Comment by carmenbianca** [comment]
Reloaded the page and it's no longer an issue. Oh well.

**Comment by mxmehl** [comment]
Yep, that happens sometimes. I have the feeling that the cache of Github doesn't contribute to the problem in a positive way as well...
