### ISSUE TITLE
Release version 1

### ISSUE THREAD

**Issue by floriansnow** [fsfe/reuse-tool#483]
REUSE has been using major version 0 for forever.  I suggest that we determine either a certain feature set or a certain timeframe to release version 1 of the tool.  I also suggest to then use proper semantic versioning.  We can decide (and document) whether we consider the API public or internal when importing REUSE as a module.  This decision will have an impact on versioning.

**Comment by mxmehl** [comment]
True, I also thought about that.

I suggest to combine that with a larger spec update, and would find the support of REUSE.yaml a worthy candidate for this.

Regarding API publication and versioning, I am not very opinionated.

**Comment by nicorikken** [comment]
Happy to conclude this issue is done 🚀 https://github.com/fsfe/reuse-tool/releases/tag/v1.0.0
