### ISSUE TITLE
Should license_list_up_to_date.yaml action fail?

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-tool#487]
We have a daily job checking whether the SPDX license lists are up-to-date. The job seems to be successful even when they aren't, so one would have to look in the logs.

Shall it rather fail if on of them is outdated?

**Comment by seabass-labrax** [comment]
I'd be interested to know how the check fails - is there a bug on the SPDX side that we could fix?

**Comment by mxmehl** [comment]
Sorry, not sure what you mean @seabass-labrax.

We have a regular Github workflow running to check whether the SPDX licenses/exceptions in this repo are up-to-date, e.g. here: https://github.com/fsfe/reuse-tool/actions/runs/1755354108

The action run appears to be successful although the checks itself was unsuccessful (because the files are not up-to-date). My suggestion was to let the action fail to know when we have to act on it. Carmen did that in the linked PR.

**Comment by seabass-labrax** [comment]
Ah, thanks for explaining! I had assumed that you meant that the script was having trouble fetching the data from SPDX; glad to know that's not the case :)
