### ISSUE TITLE
Add vimscript comment syntax (" comment)

### ISSUE THREAD

**Issue by svbaelen** [fsfe/reuse-tool#502]
Comment syntax from vim docs:
```
*:quote* *:comment*
'"' at the start of a line causes the whole line to be ignored.  '"'
after a command causes the rest of the line to be ignored.  This can be used
to add comments.  Example:
    :set ai     "set 'autoindent' option
```

Possibly something like this (in https://github.com/fsfe/reuse-tool/blob/master/src/reuse/_comment.py)
```
class VimCommentStyle(CommentStyle):
    """Vim comment style."""

    _shorthand = "vim"

    SINGLE_LINE = "\""
    INDENT_AFTER_SINGLE = " "
```

and mapping the extension like this:
```
FILENAME_COMMENT_STYLE_MAP = {
     [...]
    ".vim": VimCommentStyle,
}
```

For extensionless files, I suppose the `--style` option can be used :-).

**Comment by mxmehl** [comment]
Your proposal looks good so far. Does the vim syntax know multiline comments, or does every line have to be prepended by `"` then?

**Comment by carmenbianca** [comment]
`.vimrc` and other such config files probably also need to be listed.
