### ISSUE TITLE
feat: .license files should be generated with a trailing empty line

### ISSUE THREAD

**Issue by stexandev** [fsfe/reuse-tool#505]
Description: 
Most linting tools expect a file to end with a trailing empty line but the .license files generated by the tool do not.

Request: 
Generate the files with a trailing empty line.

**Comment by carmenbianca** [comment]
Fixed by #477 :) Will be released soon-ish.

**Comment by stexandev** [comment]
thank you, i couldn't find #187 while browsing/searching the issues.

**Comment by carmenbianca** [comment]
And #279 and #472 :) This is a strangely persistent bug through the ages, but it's fixed! :tada:
