### ISSUE TITLE
No newline at end of file when using addheader

### ISSUE THREAD

**Issue by weeman1337** [fsfe/reuse-tool#507]
The addheader command doesn't add a newline at end of file.  
According to a [comment](https://github.com/fsfe/reuse-tool/issues/279#issuecomment-747810783) it should create POSIX compatible files.

**Steps to reproduce:**

```
touch test.svg
reuse addheader --license=AGPL-3.0-or-later test.svg
cat test.svg.license
```

**Expected:** new line at end of file

**Actually:** no new line at end of file

May be a regression of #187

Environment:
- Ubuntu 20.04.4 LTS
- reuse version 0.14

**Comment by mxmehl** [comment]
Fixed in #505 already, will be available with the next release :)
