### ISSUE TITLE
site translation 

### ISSUE THREAD

**Issue by trendspotter** [fsfe/reuse-tool#508]
Hi, the translation of the site is done for Czech language. Please deploy it and enable  language selector on the site. 
Thanks.

**Comment by mxmehl** [comment]
Thank you! In our configuration, the Czech translation is not shown as 100% complete. Also in Weblate, some strings seem to be missing.

Unfortunately, the pot file is outdated, and I ran into an issue/question when trying to update it (https://github.com/fsfe/reuse-docs/issues/97). Sorry for the confusion, I am rather unknowledgable with Weblate/Gettext and just implemented the translations.

**Comment by trendspotter** [comment]
@mxmehl ok, now the translation is done.
