### ISSUE TITLE
Plus operator

### ISSUE THREAD

**Issue by alyssais** [fsfe/reuse-tool#510]
The SPDX spec [defines](https://spdx.github.io/spdx-spec/SPDX-license-expressions/#d3-simple-license-expressions) a "+" operator, to mean "or later version".

But reuse doesn't seem to support this.  If I try to license mark a file with `SPDX-License-Identifier: EUPL-1.2+`, reuse says:

> Bad licenses: EUPL-1.2+

I assume this means that it is not aware of the plus operator, and considers it to be part of the license name.

**Comment by mxmehl** [comment]
This has been fixed on #314. The next release will ship this.
