### ISSUE TITLE
Poetry version still on 0.14.0

### ISSUE THREAD

**Issue by nicorikken** [fsfe/reuse-tool#527]
As I prefer the consistent dependency handling of Poetry, I redid my dev install with Poetry. But it turns out that Poetry still registers version 0.14.0 as it seems the version number was not updated in the version commit https://github.com/fsfe/reuse-tool/commit/b0fd725328e42d98f6c8e60d2d3587dd728bbcc7

```shell
$ poetry install
$ poetry run reuse --version
reuse 0.14.0
```

One option is to simply update the version in the https://github.com/fsfe/reuse-tool/blob/master/pyproject.toml file, but perhaps there are better ways to prevent so many hardcoded numbers.

**Comment by carmenbianca** [comment]
https://github.com/fsfe/reuse-tool/blob/master/.bumpversion.cfg

needs to be added here. hardcoding version numbers in python is a tricky problem that is effectively solved by just having a tool do the bumping for you.

**Comment by nicorikken** [comment]
Ah, so the line to add is:
```toml
[bumpversion:file:pyproject.toml]
```
Right?

**Comment by carmenbianca** [comment]
I think so, yes. Only one way to find out.
