### ISSUE TITLE
Support globbing in filenames for comment styles

### ISSUE THREAD

**Issue by nicorikken** [fsfe/reuse-tool#528]
Currently the comment style is determined for either extensions or complete filenames. In https://github.com/fsfe/reuse-tool/issues/521 I encountered files that would match a certain globbing pattern (`*telegraf*.conf`) to expand support besides full filenames. So I see a use for using globbing or regexes for filename matches.

In that case the matching of filenames would have to be changed to support some kind of regex syntax:
https://github.com/fsfe/reuse-tool/blob/a2a0c170163c8bb7dfaf79d9c778dc0dff8db113/src/reuse/header.py#L328-L333

If we were to support regexes, we could consider to unify extensions and filenames into a single list. But that might become hard to read quite easily and might slow down processing.

**Comment by floriansnow** [comment]
I'm not sure if globbing for that purpose is a good idea anyway.  A file could reasonably have that name and not be related.
