### ISSUE TITLE
Drop support for Python 3.6

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#530]
Python 3.6 has been end-of-lifed [for 5 months at time of writing](https://endoflife.date/python). Future development should not be beholden to Python 3.6.

**Comment by mxmehl** [comment]
IIRC we said that we drop official support as soon as we run into an issue with a dependency or needed feature that only >=3.7 would provide.

**Comment by carmenbianca** [comment]
Then we keep this issue open as a tiny reminder :)
