### ISSUE TITLE
Support for AppStream's metainfo.xml

### ISSUE THREAD

**Issue by BLumia** [fsfe/reuse-tool#542]
I'm currently trying to add reuse check for my project, while using `reuse lint` for checking existing files, I found it seems `reuse` doesn't recognized the license of an [AppStream metainfo.xml file](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license).

A valid `metainfo.xml` file will have a `<metadata_license/>` tag that declared the license of the metadata file. Something like `<metadata_license>CC0-1.0</metadata_license>`. Supporting such license declaration will make project no longer need to add those files to project's `dep5` file or add a corresponding `some.name.metainfo.xml.license` file.

Sample metainfo.xml file: [net.blumia.pineapple-pictures.metainfo.xml](https://github.com/BLumia/pineapple-pictures/blob/9f2e004951161417ae85bee6840fdb6311cc9b32/dist/appstream/net.blumia.pineapple-pictures.metainfo.xml) from my project.

``` shell
$ pipx run reuse --version
reuse 1.0.0
$ python3 --version
Python 3.10.4
$ lsb_release -ir
Distributor ID:  Ubuntu
Release:         22.04
```

--------

btw, a small question I got while using `reuse` is, will `reuse` works under Windows? Since I saw it complains `ModuleNotFoundError: No module named 'pwd'` when running `reuse lint` under my Windows 11 installation (logs below). Or should I open another issue for the Windows supporting question?

<details>

`$env:PYTHONUTF8="1"` was set or it will complain `UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 105444: illegal multibyte sequence` when running under a non UTF-8 Windows installation (Simplified Chinese for example). The following are the errors while trying to run `reuse lint`:

```
Traceback (most recent call last):
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Gary\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\Scripts\reuse.exe\__main__.py", line 4, in <module>
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\reuse\_main.py", line 15, in <module>
    from . import (
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\reuse\download.py", line 18, in <module>
    from ._util import (
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\reuse\_util.py", line 28, in <module>
    from debian.copyright import Copyright
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\debian\copyright.py", line 59, in <module>
    from debian import deb822
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\debian\deb822.py", line 321, in <module>
    import debian.changelog
  File "C:\Users\Gary\AppData\Roaming\Python\Python38\site-packages\debian\changelog.py", line 93, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

</details>

**Comment by nicorikken** [comment]
It is nice that the `metainfo.xml` supports license information, but similar to code project files containing license information it is not conformant to the SPDX standard and therefore not to REUSE. Dep5 is already undesirable going forward and I don't think adding more supported formats is the way. If you would run `addheader` then REUSE will probably add an HTML style comment `<!--` `-->` to the file with the corresponding license information. At least that is my conclusion based on the current code: https://github.com/fsfe/reuse-tool/blob/fceb67fab8b81d63adbb342c80a05ab6856a4472/src/reuse/_comment.py#L633
I agree it is duplicating the information, but I guess it is the most standard way to do it currently. Adding the `.license` file is the other valid way to deal with this.

Another issue is the extraction of such information so REUSE can understand it when applying headers. That is something that could become part of the [helper scripts section of the documentation](https://reuse.readthedocs.io/en/stable/scripts.html).

I think REUSE should work under Windows. I think the main developers don't use Windows or even have access to a Windows machine, but that should not stop REUSE from running on Windows. So please do create a separate issue for it so it can be addressed.

**Comment by nicorikken** [comment]
Thank for creating the separate Windows issue.

Sorry for my ambiguous comment. Although the license expression is a valid one, there is no preceding `SPDX-License-Identifier` tag to highlight that the subsequent text should be interpreted as the file license. https://reuse.software/tutorial/#step-2

**Comment by BLumia** [comment]
Oh, then I guess it's a won't fix state then. I'll continue to go with the `dep5` workaround solution then. Thanks!
