### ISSUE TITLE
[question] Correct way to clearly identify non-libre code?

### ISSUE THREAD

**Issue by lofidevops** [fsfe/reuse-tool#545]
Reuse is great for generating an [SBOM](https://reuse.software/faq/#bill-of-materials). This makes it very useful in a setting with proprietary, libre and mixed-license codebases. What is the correct way to tag known-proprietary (known-bad 😉) files?

I understand that I can use [SPDX-License-Identifier: LICENSES/LicenseRef-MyLicense.txt](https://reuse.software/faq/#custom-license) to declare any custom license (including a proprietary one). I want to make reuse-tool aware that the license is not merely custom but proprietary, i.e. **not** free/libre, **not** suitable for sharing, etc.

This will help future efforts to liberate a codebase, even if it's one module at a time.

**Comment by nicorikken** [comment]
Any license not being a Free Software or Open Source license is inherently a proprietary one. I don't think the format currently allows you to be more explicit other than choosing a very explicit identifier like `LicenseRef-Proprietary` or `LicenseRef-Restricted`. REUSE doesn't evaluate the license content or compatibility, just if the code is properly annotated.

**Comment by lofidevops** [comment]
Thanks, if there's no established convention I think I'll use `LicenseRef-Restricted`.
