### ISSUE TITLE
Add option to remove blank line in header

### ISSUE THREAD

**Issue by vladh** [fsfe/reuse-tool#562]
The default file headers look like this:

```
// © 2022 Vlad-Stefan Harbuz <my-email>
//
// SPDX-License-Identifier: license-goes-here
```

However, I would prefer to do without the middle line. I understand that its purpose is probably to separate the (potentially long) copyright information from the license, but if I am the only copyright holder in my project, the extra line feels superfluous.

```
// © 2022 Vlad-Stefan Harbuz <my-email>
// SPDX-License-Identifier: license-goes-here
```

Would you be open to a patch adding support for this format to `reuse addheader`, i.e. with a `--long-option`? FWIW, the format without the middle line is recognised as valid by `reuse lint`.

**Comment by nicorikken** [comment]
Personally I recognise the desire to remove the empty line for simple files. I think the current format should remain default but there might be a flag to skip spacing like `--squashed`, `--compact`, `---no-newline` or `--no-separation`. Let's see what others think.

**Comment by carmenbianca** [comment]
Do [templates](https://reuse.readthedocs.io/en/stable/usage.html#templates) satisfy this request?

**Comment by nicorikken** [comment]
Sounds like a one-off solution. Then the ttemplate should be:
```
{% for copyright_line in copyright_lines %}
{{ copyright_line }}
{% endfor %}
{% for expression in spdx_expressions %}
SPDX-License-Identifier: {{ expression }}
{% endfor %}
```
So as the one in the docs but without the newline.

**Comment by vladh** [comment]
@carmenbianca Templates do solve the issue, but they introduce another file that has to be added to the project, and another topic that needs to be researched. I can imagine that most projects have a single copyright line, and so I think removing the middle line is a common enough use case to justify an extra command-line argument. This would mean users don't have to look up how to write the correct jinja2 file and so on. What do you think?

**Comment by nicorikken** [comment]
I see how it makes sense to shorten it if there is one copyright holder. The moment there are two copyright holder it starts making sense for me to add the empty line. Personally I think we should avoid too many options and flags. So I think the Jinja template is good enough of a solution, although it might benefit from some documentation. Maybe if we have named templates built-in with reuse, it would be prevent users from having to add a file, making it even easier.

**Comment by vladh** [comment]
I think a built-in named template would definitely solve the problem!

**Comment by mxmehl** [comment]
Full ack on the options. The additional included templates *could* make sense, but I'd see it as a low priority TBH.

**Comment by vladh** [comment]
If you do decide the template option is good I would be happy to contribute it (or whatever other solution you choose).

**Comment by mxmehl** [comment]
Thanks for the offer! I'd like to ask for some patience as we will discuss this in one of the next maintainer meetings.

**Comment by vladh** [comment]
Any update on whether you would like me to implement this?

**Comment by mxmehl** [comment]
No, due to overlapping summer breaks we didn't have a meeting yet.

**Comment by mxmehl** [comment]
We had a call and concluded that we would not want to include such a template in the tool. We want to avoid feature-creep, and since this is so simple to solve via templates, we'd prefer this.

However, we figure that it might make sense to support loading templates not only from a project but also more globally, so that a user can set templates once and re-use them in multiple projects. I opened #581 for this, and would close this specific issue then as wont-fix.

However, thanks for the report that made us discuss this issue and come up with a solution. Please feel free to contribute to #581 :)
