### ISSUE TITLE
Support SPDX Snippet information

### ISSUE THREAD

**Issue by steffenb7333** [fsfe/reuse-tool#567]
[The reuse FAQ](https://reuse.software/faq/#partial-license) states that "there is no standard way for REUSE to recognize" "a part of a file as being under a different license". Why not support [SPDX Snippet information](https://spdx.github.io/spdx-spec/snippet-information/)?

**Comment by mxmehl** [comment]
With the latest SPDX version, we finally have the counterpart to support snippets in REUSE. Before that, there was no defined tag and procedure we could build upon.

The next version of the REUSE spec will support this (see fsfe/reuse-docs#107), and the tool accordingly. You can already implement these tags in your own code if you want, we don't expect any changes.
