### ISSUE TITLE
.license-file and/or in-file information should take precedence of dep5

### ISSUE THREAD

**Issue by steffenb7333** [fsfe/reuse-tool#572]
I have a binary file `file` with an accompanying `.license` file and a lot of other files in the same directory and subdirectories.
The directory `file` resides in is also specified in `.reuse/dep5` with a wildcard b/c of all the other misc files.
`reuse spdx` mixes both information (from .license and dep5) and the result is plainly wrong and and in my case license-wise a contradiction. The only way out at the moment would be to name each other file except `file` and `file.license` in dep5 explicitly, which quite frankly is really unwieldy b/c of the sheer number of other files.

**Comment by mxmehl** [comment]
I agree, and that's what we intend to do with option 3 in fsfe/reuse-docs#70. The timeline depends on when we can implement REUSE.yaml (blocked by SPDX at the moment). Given that it takes much longer, we may also define this earlier with DEP-5.

I'll close this issue as it's known and has a related issue we're tracking. Thanks for reporting anyway!
