### ISSUE TITLE
reuse should detect .clang-format files

### ISSUE THREAD

**Issue by jonasstein** [fsfe/reuse-tool#575]
reuse should detect .clang-format files

```
$ reuse addheader --copyright="stenc authors" --license=GPL-2.0-or-later .clang-format 
usage: reuse addheader [-h] [--copyright COPYRIGHT] [--license LICENSE] [--year YEAR] [--style {applescript,aspx,bat,bibtex,c,css,f,ftl,handlebars,haskell,html,jinja,lisp,m4,ml,plantuml,python,rst,tex,vim}]
..reuse addheader: error: The following files do not have a recognised file extension. Please use --style, --force-dot-license or --skip-unrecognised:
.clang-format

```

**Comment by nicorikken** [comment]
Do I understand it correctly that this applies to `.clang-format` or `_clang-format` file in the directory as the full name, and so not as an extension like `foo.clang-format`? I read this documentation https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by nicorikken** [comment]
Do I understand it correctly that this applies to `.clang-format` or `_clang-format` file in the directory as the full name, and so not as an extension like `foo.clang-format`? I read this documentation https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by jonasstein** [comment]
@nicorikken yes, it is a very common file see https://github.com/scsitape/stenc/blob/master/.clang-format for example.
