### ISSUE TITLE
GitHub issue templates are impossible with REUSE compliance

### ISSUE THREAD

**Issue by Journeyman-dev** [fsfe/reuse-tool#588]
GitHub issue templates require a yaml list at the very top that sets several options. You can read about what they require here:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

Since this yaml list has to be at the very top of the file, it means that this breaks reuse compliance.

For an example, my repository has issue templates with a license header and they do not show up with you try making a new issue:
https://github.com/Journeyman-dev/FossSweeper/tree/main/.github/ISSUE_TEMPLATE

I suggest that you add an omission for files in the .github/ISSUE_TEMPLATE folder.

Is there a workaround that I don't know about?

**Comment by Journeyman-dev** [comment]
GitHub has a new way of making issue templates with yaml files, which I am using now. This new method works fine with REUSE. Its still in beta though, but problem solved in the long run...

**Comment by mxmehl** [comment]
I'm glad that you were able to circumvent this issue. However, I did not fully understand the problem.

The REUSE comment header does not necessarily have to be at the very top of a file. If it broke the syntax, you would also be able to put it a few lines down. Would that have solved your problem, or did I miss the gist?
