### ISSUE TITLE
`reuse spdx` prints SPDX-FileCopyrightText

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-tool#59]
When running `reuse spdx` over reuse-website, I find the following as an example:
```
FileName: ./site/static/css/template.css
SPDXID: SPDXRef-80751eb67afd7c1010f435798d7feb52
FileChecksum: SHA1: b7b7266ae690116ed56a71f616afd9d2bace073a
LicenseConcluded: NOASSERTION
LicenseInfoInFile: MIT
FileCopyrightText: <text>SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V. <https://fsfe.org>
SPDX-FileCopyrightText: 2015 Omar Abdelhafith <o.arrabi@me.com></text>
```

1. Do we want to print SPDX-FileCopyrightText as a value of FileCopyrightText?
2. Is it correct that two copyright statements are inside one `<text>` tag?

**Comment by carmenbianca** [comment]
Another example from `reuse-tool`:

```
FileName: ./tests/test_util.py
SPDXID: SPDXRef-c184ea425e04f199331a6292a73faab7
FileChecksum: SHA1: 1beef52d7b611afd031f6fd106469bbafa63fdc7
LicenseConcluded: NOASSERTION
LicenseInfoInFile: GPL-3.0-or-later
FileCopyrightText: <text>Copyright (C) 2019 Jane Doe
Copyright 2019 Jane Doe
Copyright © 2019 Jane Doe
SPDX-FileCopyrightText: 2017-2019 Free Software Foundation Europe e.V.
SPDX-FileCopyrightText: 2019 Jane Doe
SPDX-FileCopyrightText: 2019 Jane Doe"
SPDX-FileCopyrightText: © 2019 Jane Doe
© 2019 Jane Doe
© hello"</text>
```

(Most of this is false positives, of course, but it's really really hard to avoid false positives in a project where you try to test your own compliance.)

You'll notice that it preserves the `©`, `SPDX-FileCopyrightText`, and `Copyright` for every line. It'd be fairly trivial (I think to recall) to only take everything AFTER the copyright tag, but it wouldn't be trivial to only do that for `SPDX-FileCopyrightText`. So for the sake of accurately representing what was actually found, I opted to include the entire copyright line verbatim.

It is correct that it is all wrapped in a single `<text>` tag. That's how the SPDX Spec works. I wish it worked differently, but it doesn't.

I'm personally inclined to WONTFIX this.

**Comment by mxmehl** [comment]
OK, fine for me. Wasn't aware of the <text> spec

**Comment by Tachi107** [comment]
Hi, I've just stumbled upon this issue, and I think that closing it as WONTFIX isn't the best choice in my opinion. The REUSE spec states that

> The `SPDX-FileCopyrightText` tag MUST be followed by a copyright notice.
>
> Instead of the `SPDX-FileCopyrightText` tag, the symbol `©`, or the word `Copyright` MAY be used, in which case a colon is not needed.

As `SPDX-FileCopyrightText`, `©`, and `Copyright` are _followed by_ the copyright notice, it means that they are not part of the notice itself, and shouldn't be part of the outputted `FileCopyrightText`.

Probably not that useful to say this, but I'm trying to use the output of `reuse spdx` to produce `dep5` files
