### ISSUE TITLE
Missing/partial copyright info when copyright holder value starts below ©

### ISSUE THREAD

**Issue by tenzap** [fsfe/reuse-tool#590]
Files with such headers:
```
# translation of kdmgreet.po to German
# Übersetzung von kdmgreet.po ins Deutsche
# Copyright (C)
# Thomas Diehl <thd@kde.org>, 2002, 2003, 2004.
# Stephan Johach <hunsum@gmx.de>, 2005.
# Thomas Reitelbach <tr@erdfunkstelle.de>, 2005, 2006, 2007.
```

end up in summary.spdx this way
```
LicenseConcluded: NOASSERTION
FileCopyrightText: <text>Copyright (C)</text>
```

Hence missing the relevant copyright info.

Excepted output
```
FileCopyrightText: <text>Copyright (C) Thomas Diehl <thd@kde.org>, 2002, 2003, 2004.
 Stephan Johach <hunsum@gmx.de>, 2005.
 Thomas Reitelbach <tr@erdfunkstelle.de>, 2005, 2006, 2007.</text>
```
or 
```
FileCopyrightText: <text>Copyright (C) Thomas Diehl <thd@kde.org>, 2002, 2003, 2004.  Stephan Johach <hunsum@gmx.de>, 2005. Thomas Reitelbach <tr@erdfunkstelle.de>, 2005, 2006, 2007.</text>
```

Would it be possible to support such cases where the copyright holder are on the lines below ?

**Comment by mxmehl** [comment]
Phew, I suspect that would stretch the detection logic and make it prone to all kinds of false-positives, so I'd close it as wont-fix unless someone has a really clever idea.

Please consider making each line a complete copyright line, either with `SPDX-FileCopyrightText` or the "traditional" Copyright statements, just like most other projects and best practices do it.

**Comment by carmenbianca** [comment]
I suspect that the annoying thing here is that the above header is generated by a gettext translation tool.

Unfortunately, this request is non-trivial to develop, and is not supported by the current REUSE spec. I propose to maybe take this upstream with the translation tool.
