### ISSUE TITLE
UNLICENSE file requires license header comment

### ISSUE THREAD

**Issue by Journeyman-dev** [fsfe/reuse-tool#592]
By standard convention, repositories that use the Unlicense are supposed to have a license file named "UNLICENSE". This is explained on their official website [here](https://unlicense.org/). If you try naming the (un)license file in this way, the REUSE tool thinks that it is not REUSE compliant unless you add a license header to the top of the file. This problem could easily be fixed by not requiring files named "UNLICENSE" to have a license header, much like how the REUSE tool already lints when it sees files named "CHANGES" and "LICENSE".

**Comment by mxmehl** [comment]
Note that this is not a hard requirement stated by the license, but a recommendation as per the website:

> However, to explicitly distance yourself from the whole concept of copyright licensing, we recommend that you put your unlicensing statement in a file named [UNLICENSE](https://unlicense.org/UNLICENSE).

The thing is that, unlike LICENSE or COPYING, that's a quite license-specific exception. I'm not sure whether we want to open Pandora's box with adding all kinds of specialities. OTOH, in this case probably not much harm would be done. It would have to be added to `_IGNORE_FILE_PATTERNS `.

**Comment by Journeyman-dev** [comment]
Why not allow people to specify custom license file names? If they abuse this to break reuse compliance, would that be a problem?

**Comment by carmenbianca** [comment]
Making minute details like that configurable is not a maintenance burden that seems warranted.

Adding this to `_IGNORE_FILE_PATTERNS` seems fine to me, although I fail to see why someone who is ideologically aligned with Unlicense's philosophy of opposition to copyright and licensing would go through the effort of, well, tidying up all the copyright and licensing using REUSE.

**Comment by linozen** [comment]
> Adding this to _IGNORE_FILE_PATTERNS seems fine to me, although I fail to see why someone who is ideologically aligned with Unlicense's philosophy of opposition to copyright and licensing would go through the effort of, well, tidying up all the copyright and licensing using REUSE.

I totally agree with this. Maybe @Journeyman-dev could explain why an UNLICENSE user might want to use REUSE? If not, I am in favour of closing this.
