### ISSUE TITLE
Templates for addheader

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-tool#60]
We want to support custom templates for headers. Allow default templates per file type and verify integrity.

Some notes that we took:

- [x] Jinja seems like a good templating system for this
- [ ] Add a way to configure default templates per file type
- [x] Verify integrity of template (is a single comment block, contains two tag loops)
- [x] Make sure that the template can replace itself in a header
- [x] [optional] Perhaps allow a method for uncommented templates that can be used for all file types recognised by REUSE? It's fairly trivial to comment such a text block
- [x] Allow a method for commented templates

**Comment by carmenbianca** [comment]
Updated comment with a checklist
