### ISSUE TITLE
reuse 1.1.0 gives error 'Duplicate field "Copyright" in paragraph ...'

### ISSUE THREAD

**Issue by MarkCallow** [fsfe/reuse-tool#631]
I have an entry in my dep5

```
Files: other_include/GL/glew.h other_include/GL/glxew.h other_include/GL/wglew.h other_lib/win/Release-x65/glew32.*
Copyright: 2008-2015, Nigel Stewart <nigels[]users sourceforge net>
Copyright: 2002-2008, Milan Ikits <milan ikits[]ieee org>
Copyright: 2002-2008, Marcelo E. Magallon <mmagallo[]debian org>
Copyright: 2002, Lev Povalahev
License: BSD-3-Clause
```

`reuse lint` 1.1.0 complains about `Duplicate field "Copyright" in paragraph ...`. Previous versions did not complain about this. The list of copyrights comes straight from the files, where it is not placed in a reuse compatible way hence the dep5 entry.

How can I list all these copyrights in a `reuse lint` compatible way? I found nothing on [reuse.software](reuse.software) that helps. It does mention that files often have a list of copyrights without saying such is invalid or giving an alternative.

Is this a bug in `reuse`?

P.S. `reuse lint`'s error handling is horrendous. See #630.

**Comment by MarkCallow** [comment]
From the very brief description of `dep5` given in the reuse spec. I decided I should look at https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/. (It would be a wonderful thing if the reuse spec. explicitly said that the `dep5` format is as described in the debian file instead of just listing it as the value for the `format:` line of the dep5 with not further comment.) In [copyright-format](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) I learned that you can have multiple copyright statements but only a single copyright field. The following passes `reuse lint`

```
Files: other_include/GL/glew.h other_include/GL/glxew.h other_include/GL/wglew.h other_lib/win/Release-x65/glew32.*
Copyright: 2008-2015, Nigel Stewart <nigels[]users sourceforge net>
           2002-2008, Milan Ikits <milan ikits[]ieee org>
           2002-2008, Marcelo E. Magallon <mmagallo[]debian org>
           2002, Lev Povalahev
License: BSD-3-Clause
```

Flagging duplicate copyright is therefore not an error in `reuse` so I'll close this bug.

**Comment by nicorikken** [comment]
@MarkCallow Thanks for reporting nonetheless. I created a PR to add a link in that context as well.
