### ISSUE TITLE
Ignores files which are being tracked in source control

### ISSUE THREAD

**Issue by tristan957** [fsfe/reuse-tool#664]
`reuse` seems to be ignoring files that are ignored in source control.

Reproduce:

1. Clone `https://github.com/hse-project/hse.git`
2. Checkout `tristan957/reuse`
3. Run `reuse spdx | grep -F crc32c`
4. See no output

Something about my gitignore has to be throwing the tool off.

https://github.com/hse-project/hse/blob/tristan957/reuse/.gitignore

**Comment by tristan957** [comment]
You can see a failed run here: https://github.com/hse-project/hse/actions/runs/4107882662/jobs/7087908672.

I am using those licenses within the following directories:

- subprojects/crc32c
- subprojects/hyperloglog
- subprojects/rbtree
- subprojects/xoroshiro

You will either find the license and copyright info in `.reuse/dep5` or the source files themselves.

**Comment by carmenbianca** [comment]
This is fixed by `reuse --include-meson-subprojects spdx | grep crc`.

See #496. Maybe this should be documented better?

**Comment by tristan957** [comment]
I'll give this a go in the morning (UTC -6). Appreciate you getting back to me. I presume that this argument is also available for the lint command.

One thing to keep in mind is that the Meson subprojects directory is configurable. I haven't looked at the code for this project to know if it takes into account subproject directories other than "/subprojects/".

**Comment by carmenbianca** [comment]
> I presume that this argument is also available for the lint command.

Yes, this is correct. The argument goes `reuse --argument-here sub-command`.

> if it takes into account subproject directories other than "/subprojects/".

I don't think it does.

Set of ignored directories (i.e., only `./subprojects`): https://github.com/fsfe/reuse-tool/blob/448dd34a121e7f702bbd4a29351fc11f689710ba/src/reuse/__init__.py#L48

Where the above set is invoked: https://github.com/fsfe/reuse-tool/blob/448dd34a121e7f702bbd4a29351fc11f689710ba/src/reuse/project.py#L199

**Comment by tristan957** [comment]
Well, `--include-meson-subprojects` worked like a charm. I guess I am just confused why `reuse` can't rely on the gitignore I am using to track built-in subprojects vs external subprojects.

**Comment by carmenbianca** [comment]
Gitignore is not really relevant here. Anything tracked by Git is checked. We just treat Meson subprojects as a special case because someone made an issue + made a PR to scratch their own itch.

**Comment by tristan957** [comment]
Meson subprojects aren't checked into Git by default, so I am having trouble understanding why the contributor made the contribution in the first place. I would highly recommend reverting the contribution and/or making `--include-meson-subprojects` a no-op.

Best practice is always to throw `/subprojects/*` into the gitignore.

**Comment by carmenbianca** [comment]
You can see the discussion in #496 and #574.

I'm too ignorant on Meson to make a good call on this. And in any case, there's no pleasing everyone here.

**Comment by tristan957** [comment]
I will read that over. Thanks.

**Comment by eli-schwartz** [comment]
> I haven't looked at the code for this project to know if it takes into account subproject directories other than "/subprojects/".

This would require parsing `meson.build`, but the good news is that changing this directory is rarely done -- the option in Meson really only exists for backwards compatibility with existing project structures such as `third_party/` that are annoying to change. So most projects will be handled correctly by the defaults.

**Comment by marktsuchida** [comment]
It looks like a direct reference to #576 has not come up here. (It sounded like the opposite conclusion had already been reached there.)
