### ISSUE TITLE
Project not compliant with 3.0 version

### ISSUE THREAD

**Issue by Luni-4** [fsfe/reuse-tool#670]
When I run `reuse lint` with this configuration in `.reuse/dep5`:

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: {project_name}
Source: {project_link}

Files: *
Copyright: 2022 {name} <my@mail.com>
License: MIT
```

I get the following errors

```
# MISSING LICENSES

'MIT' found in:
* .github/workflows/deploy.yml
* .github/workflows/libp2p-rust-dht.yml
* .gitignore
* Cargo.toml
* README.md
* cross-compile.sh
* docker/Dockerfile
* docker/build_and_launch.sh
* src/domobroker.rs
* src/domocache.rs
* src/domolibp2p.rs
* src/domopersistentstorage.rs
* src/lib.rs
* src/main.rs
* src/restmessage.rs
* src/utils.rs
* src/webapimanager.rs
* src/websocketmessage.rs


# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses: MIT
* Unused licenses:
* Used licenses: MIT
* Read errors: 0
* Files with copyright information: 18 / 18
* Files with license information: 18 / 18

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

Is that a problem related to the glob in `Files`?

**Comment by Luni-4** [comment]
I fixed the issue creating `LICENSE` directory with a `MIT.txt` inside it. If I instead put a LICENSE file in the root of the project with the same information, it doesn't work

**Comment by Luni-4** [comment]
My bad, I haven't paid not much attention to the specification. I have been deceived by the lack of information in the error message (would it be possible to add a string that explains I should put a LICENSE file inside the LICENSES directory and rename it with the name of the license?). Sorry for the inconvenience.

**Comment by seabass-labrax** [comment]
Maybe error messages could link to the relevant part of the REUSE specification; in this case the `reuse` tool would link to <https://reuse.software/spec/#license-files>.

E.g.:

> Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
> This is due to a missing license file: https://reuse.software/spec/#license-files

**Comment by Luni-4** [comment]
> Maybe error messages could link to the relevant part of the REUSE specification; in this case the `reuse` tool would link to https://reuse.software/spec/#license-files.
> 
> E.g.:
> 
> > Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
> > This is due to a missing license file: https://reuse.software/spec/#license-files

That would be perfect!

**Comment by carmenbianca** [comment]
Opened issue https://github.com/fsfe/reuse-tool/issues/672
