### ISSUE TITLE
Make the text output of `reuse lint` more helpful

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#672]
Maybe provide links to FAQ/spec.

Maybe one recommendation for each bullet point if said bullet point fails?

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses:
* Read errors:
* Files with copyright information:
* Files with license information:

**Comment by mxmehl** [comment]
Good idea. Perhaps a collected list of todo items, if one or multiple of these errors appear?
