### ISSUE TITLE
discuss supporting other `reuse lint` report output formats (exporters)

### ISSUE THREAD

**Issue by kbroch-rivosinc** [fsfe/reuse-tool#676]
Related to #672

Currently  it looks like the report output is in markdown. 

IMO it would be useful to provide other formats. [Bandit](https://bandit.readthedocs.io/en/latest/formatters/index.html#complete-formatter-listing) has a comprehensive list.

Here's a subset I'd be interested in:

* xml (specifically junit test format)
  * why: for existing projects trying to get REUSE compliant may be a journey, this would facilitate eventual compliance by monitoring progress over time (ex: [using in gitlab](https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html))
* html
  * why: then don't have to pipe existing md output into another tool to generate it

I realize xml format might have the same response as here: https://github.com/fsfe/reuse-tool/issues/655#issuecomment-1411834868 but just wanted to pose the use case.

**Comment by carmenbianca** [comment]
See also #654 #183 

XML (junit test) sounds interesting. I'm not sure we're going to take initiative on that, though. JSON has higher priority for us at the moment.

Thanks for the issue!

**Comment by kbroch-rivosinc** [comment]
Thanks for `--json` issue links (I missed those).  I'll check back in after `--json` PR lands.  I bet I can transform that output to my needs.

**Comment by mxmehl** [comment]
See #320 for the junit.xml request.

Could we close this issue as there are already issues/PRs for JSON and junit?

**Comment by kbroch-rivosinc** [comment]
Closing this issue is fine with me.
