### ISSUE TITLE
`init` does not accept LicenseRef

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-tool#677]
When initialising a repo with a custom license (e.g. `LicenseRef-test`), `reuse init` returns the error that the license is not a valid SPDX license identifier:

```
$ reuse init
Initializing project for REUSE.

What license is your project under? Provide the SPDX License Identifier.
To stop adding licenses, hit RETURN.
LicenseRef-test

'LicenseRef-test' is not a valid SPDX License Identifier.
See <https://spdx.org/licenses/> for a list of valid SPDX License Identifiers.

What license is your project under? Provide the SPDX License Identifier.
To stop adding licenses, hit RETURN.
[...]
```

This is obviously not correct as it is a valid identifier, but it cannot be downloaded.

**Comment by nicorikken** [comment]
Good find. Currently the code checks against the list of known licenses.

https://github.com/fsfe/reuse-tool/blob/0b0baefb6c68deeb12bee8e3811695a883c5646c/src/reuse/init.py#L45-L47

An additional check should be added to allow for LicensRef too. It seems that this function of checking licenses supplied by human input is something generic that can be used in multiple places.
