### ISSUE TITLE
removing the donations banner

### ISSUE THREAD

**Issue by jonasstein** [fsfe/reuse-tool#682]
There is a banner in `reuse --help`

```
Support the FSFE's work:

  Donations are critical to our strength and autonomy. They enable us to
  continue working for Free Software wherever necessary. Please consider
  making a donation at <https://fsfe.org/donate/>.
```

I get your point with the donations banner, but it is distracting and rather annoying.
Within thousands of open source tools, reuse and parallel are the only one I know with an advertising banner in the help page.
Please think about moving it to a better place (README, or man page section Donations, ...).
Imagine each of the open source tools you use would start to place banners. Thank you.

**Comment by carmenbianca** [comment]
>  Imagine each of the open source tools you use would start to place banners. Thank you.

Fine by me.

I'm sorry. Closing wontfix.
