### ISSUE TITLE
License text missmatch when downloading `GPL-2.0-only`

### ISSUE THREAD

**Issue by bernhardreiter** [fsfe/reuse-tool#694]
There a section missing in the downloaded license for  `GPL-2.0-only`:

```bash
LANG=C reuse download GPL-2.0-only
Successfully downloaded LICENSES/GPL-2.0-only.txt

grep "does not permit" LICENSES/GPL-2.0-only.txt | wc
      0       0       0

curl --silent https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html | grep "does not permit"
This General Public License does not permit incorporating your program into

 reuse --version
reuse 1.1.2

```

The following section is missing from the download:

> This General Public License does not permit incorporating your program into proprietary programs. If your program is a subroutine library, you may consider it more useful to permit linking proprietary applications with the library. If this is what you want to do, use the GNU Lesser General Public License instead of this License.

**Comment by mxmehl** [comment]
REUSE downloads the license texts from SPDX, specifically [license-list-data](https://github.com/spdx/license-list-data/tree/main/text). There, the paragraph you mention is marked as optional:

https://github.com/spdx/license-list-XML/blob/17632be2fcd4d4c2a9eda1202be2878baceb47b4/src/GPL-2.0-only.xml#L465-L473

Therefore, it does not appear in the final TXT file. If you think this is a mistake, I kindly ask you to send this request to SPDX directly, e.g. their legal mailing list.

We were asked a few times already to download the license texts from the authors directly but for technical, resource and maintenance reasons we rely on SPDX' data which usually is correct.

**Comment by seabass-labrax** [comment]
Hello @bernhardreiter! SPDX Outreach Team co-chair here. SPDX considers that sentence to be 'optional text', so it's still considered to be `GPL-2.0-only` whether or not it includes that part. If you think that this sentence should be included in the text file, I would second @mxmehl's suggestion of writing to the spdx-legal@lists.spdx.org mailing list or the https://github.com/spdx/license-list-XML GitHub repository for consideration by the whole SPDX Legal Team :smiley:

**Comment by bernhardreiter** [comment]
Hello @mxmehl, hello @seabass-labrax 
thanks for your responses!

Maybe there is room to improve the user experience for the reuse-tool and the SPDX licenses list,
as reuse lists the following URL as source for `GPL-2.0-only`:
  https://spdx.org/licenses/GPL-2.0-only.html

On this webpage there is no indication that the missing paragraph is different than the blue sections right above it, which are included after the download. So reuse-tool operates differently to the URL it states and the webpage also is not fully consistent which the other urls for this license, it gives.

As improvement reuse-tool could give the precise URL it is downloading, e.g with the `--debug` flag.

I'll check into the spdx repository as well.

**Comment by nicorikken** [comment]
> As improvement reuse-tool could give the precise URL it is downloading, e.g with the --debug flag.

Sounds like a reasonable feature that would have been helpful in this case.

**Comment by mxmehl** [comment]
> On this webpage there is no indication that the missing paragraph is different than the blue sections right above it, which are included after the download. So reuse-tool operates differently to the URL it states and the webpage also is not fully consistent which the other urls for this license, it gives.

That's true, but it's clearly a question to upstream how the TXT generator decides which optional parts are included and which not. I agree that it doesn't make sense based on the XML data. Perhaps it's even a bug which causes the first optional block to be included but not the second.

**Comment by bernhardreiter** [comment]
>  it's clearly a question to upstream

Yes, I just wanted to explain why it is also a problem of the reuse-tool as the use of the download function will lead to a surprising result in this special case. This is natural of course that upsteam problems will affect downstream, the question is why did you close this issue as this is not reported or fixed in upstream? >:)
