### ISSUE TITLE
Discuss changing badge color on reuse API to something different for "unregistered" versus "noncompliant"

### ISSUE THREAD

**Issue by kbroch-rivosinc** [fsfe/reuse-tool#704]
I imagine the right place to file this issue is here: https://git.fsfe.org/reuse/api/issues
since the github mirror https://github.com/fsfe/reuse-api  doesn't have issues enabled, 
but upon trying I am asked to login and I don't see any way to create an account so I'm just putting it here for now:

At first glance it is hard to distiguish:
![image](https://user-images.githubusercontent.com/86068473/225465733-328db8ff-b2d5-4259-b049-e1426ba5e02e.png)

My thoughts are "unregistered" isn't in the strict sense of compliance a failure so I could imagine the color being grayed out.
This change would help where I'm glancing at many projects at once and want to distiguish noncompliance from unregistered.

**Comment by mxmehl** [comment]
Good point! I created an issue "upstream" and assigned myself to it: https://git.fsfe.org/reuse/api/issues/76

**Comment by mxmehl** [comment]
The badge for unregistered repos is grey now
