### ISSUE TITLE
Automatically annotate SVG & XML

### ISSUE THREAD

**Issue by niccokunzmann** [fsfe/reuse-tool#706]
When I annotate SVG files such as in #705, I would like reuse to add that automatically and manually - inside of the file.

To close this:

- [ ] add xml as a --style, same as HTML
- [ ] add svg to the html/xml to auto detect

**Comment by niccokunzmann** [comment]
I would like to edit my SVG files. Can I force editing? When I used --style=html, the .license file was still created. Hm. That is a bit confusing. If the tool does not obey my choice, I would like to be sure that that is an informed decision and the tool to inform me.

**Comment by mxmehl** [comment]
No, enforcement is currently not possible. Many file types in the uncommentable map really cannot be edited sanely so a general override flag would lead to errors. SVG seems to be quite a special case here.

If you run the `annotate` command, you will be informed about that a .license file has been created:

```
$ reuse annotate -c me -l MIT --style=html test.svg
Successfully changed header of test.svg.license
```

Admittedly, it's not entirely obvious that a separate file has been created. Would it solve your issue if that was clearer?

**Comment by niccokunzmann** [comment]
Yes, I think that would be good: 

> Successfully changed header of test.svg.license because test.svg must not be edited.
