### ISSUE TITLE
Download option case-sensitive

### ISSUE THREAD

**Issue by nicorikken** [fsfe/reuse-tool#710]
Is it necessary that the download-option is case-sensitive? I just used `reuse-download` to download a license text but was confronted with an error due to case-sensitivity:

```
reuse download cc-by-4.0
Error: Failed to download license. 'cc-by-4.0' is not a valid SPDX License Identifier.

Did you mean:
* CC-BY-1.0
* CC-BY-2.0
* CC-BY-2.5
* CC-BY-2.5-AU
* CC-BY-3.0
* CC-BY-3.0-AT
* CC-BY-3.0-DE
* CC-BY-3.0-IGO
* CC-BY-3.0-NL
* CC-BY-3.0-US
* CC-BY-4.0

See <https://spdx.org/licenses/> for a list of valid SPDX License Identifiers.
``` 

Although I see the value in an exact match, I think case-sensitivity is a bit too strict. It would be more friendly to the user to accept a license identifier if it matches completely except for casing.

**Comment by mxmehl** [comment]
Full ack, and we already have an issue for this ;) #46

**Comment by nicorikken** [comment]
Ow, and I totally forgot to even check if it didn't already exist. Sorry for wasting time 😅
