### ISSUE TITLE
Add support for Textile (markup format) files

### ISSUE THREAD

**Issue by hoijui** [fsfe/reuse-tool#712]
Comment style for these files is documented here:
https://textile-lang.com/doc/textile-comments

They have a somewhat non-standard way for how their native comments work:

* `###.` starts a multi-line comment that ends with an empty line
* `###..` starts a multi-line comment that ends with a for a new paragraph
* ... but they also support normal HTML comments: `<!-- BLA -->`

Would it be fine if I'd add the `.textile` suffix simply with `HtmlCommentStyle`?
or should I rather implement a comment style that supports all three?
I can't say when I'd find the time for that.

**Comment by mxmehl** [comment]
If we can reuse an existing comment style, I'd personally prefer that. It only requires two new lines then:
1. Adding the file extension to the list
2. Adding a changelog entry ;)

**Comment by hoijui** [comment]
will do then!
