### ISSUE TITLE
pre-commit hook doesn't allow excluding files from check

### ISSUE THREAD

**Issue by arthurep** [fsfe/reuse-tool#744]
Version 1.1.2

I tried using pre-commit's `exclude` pattern on my `.pre-commit-config.yaml` to exclude a certain file from the reuse check but it seems that this field is not taken into account as reuse runs in all files. As control, I tried using the same exclude in other pre-commit hooks and it worked just fine.

My project has quite a few third party sources which does not comply to the REUSE license check which I would like to avoid touching.

**Comment by mxmehl** [comment]
REUSE does not support excluding files in the sense you seem to aim for, and we don't plan to add it as it would completely negate REUSE's goal. Please find the rationale and possible solutions here: https://reuse.software/faq/#exclude-file
