### ISSUE TITLE
Please rename the python package to just `reuse`

### ISSUE THREAD

**Issue by terceiro** [fsfe/reuse-tool#75]
A package called `fsfe-reuse` that provides a program called `reuse` is a little confusing. Looking through the history, it was originally called `reuse`, then renamed to `fsfs-reuse` in a8c2890d8a30555772967a17bd2ad4f8ce203482 without any rationale.

Is there a reason why the package cannot be called just `reuse`?

**Comment by carmenbianca** [comment]
Hey @terceiro Thanks for the issue. In 2017 I tried uploading the package under the name of `reuse`, but it gave an error along the lines of "name already in use". Clearly it wasn't already in use, but I suppose that someone had reserved it. I had opened an issue to the pypi bug tracker (which I can no longer find), but it went unanswered. I'll try one more time to see if I can get `reuse` instead of `fsfe-reuse`.

**Comment by carmenbianca** [comment]
Same error, I'm afraid:

```
twine upload --sign -r pypi dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Signing reuse-0.4.2a1-py3-none-any.whl
gpg: using "0xCD0A90F1C5CA0C92" as default secret key for signing
Uploading reuse-0.4.2a1-py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 82.5k/82.5k [00:00<00:00, 19.8kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Client Error: The credential associated with user 'carmenbianca' isn't allowed to upload to project 'reuse'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/
make: *** [Makefile:105: release] Error 1
```

I'll leave the issue open because this is something I would like to fix, but don't see how.

**Comment by mxmehl** [comment]
Interesting. I don't see a conflict with the Python Standard Library, so it could only be that `reuse` is in use by another person without any releases, or that it has been prohibited.

@pypa, could anyone please help us to narrow this down?

**Comment by rohieb** [comment]
https://pypi.org/help/#project-name-claim might also be related.

**Comment by carmenbianca** [comment]
@rohieb Thanks. Made an issue thingamajig to see if that goes anywhere.

**Comment by carmenbianca** [comment]
Done :)
