### ISSUE TITLE
How does reuse-tool add comment(license or copyright) to .txt file?

### ISSUE THREAD

**Issue by bjk7119** [fsfe/reuse-tool#765]
[Question] 
I tried to find source code about adding comment to .txt(text) file. but I can't.
If I want to add comment to .txt file, is it possible by using reuse-tool?

**Comment by mxmehl** [comment]
We haven't defined a comment style for `.txt` files as there is no established syntax for adding comments for this file type. For instance, if REUSE used `# ` as a marker to start a comment, some applications that ingest this file might not understand it properly; unlike Markdown for example for which the comment style is somewhat defined.

If you would like to add the necessary information to your .txt file, you can do so of course. The REUSE tool will most likely understand it, e.g. if you use `# SPDX...`. But you will have to do it either manually or use the flag `--style=python` for `reuse annotate` to force this comment style.

If you are uncertain whether or which comment works for *your* .txt file, you can always create an accompanying `.license` file. With `reuse annotate`, the flag would be `--force-dot-license`.
