### ISSUE TITLE
Partial SPDX detection lead to failing lint in 2.0

### ISSUE THREAD

**Issue by mrdrogdrog** [fsfe/reuse-tool#771]
Hello,

we tried to update reuse to 2.0 but it fails when linting our files and we assume that the snippet detection is the culprit.

Following situation:
Our repository contains a file for JetBrains IDEs so it can automatically renew/add a copyright to source files.
```xml
<component name="CopyrightManager">
  <copyright>
    <option name="notice" value="SPDX-FileCopyrightText: $today.year The HedgeDoc developers (see AUTHORS file)&#10;&#10;&#83;PDX-License-Identifier: AGPL-3.0-only" />
    <option name="myName" value="hedgedoc" />
  </copyright>
</component>
```

To make the linter happy we have a rule in our dep5 file that applies to this file:

```
Files: .idea/**
Copyright: 2021 The HedgeDoc developers (see AUTHORS file)
License: CC0-1.0
```

Now here comes the problem:

Reuse 2 scans this file, finds the SPDX snippet and assues another license.

```
reuse.project - WARNING - Copyright and licensing information for '.idea/copyright/hedgedoc.xml' have been found in '.idea/copyright/hedgedoc.xml' and the DEP5 file located at '.reuse/dep5'. The information in the DEP5 file has been overridden. Please ensure that this is correct.
```

Which results in a failure:

```
The following files have no licensing information:
* .idea/copyright/hedgedoc.xml
```

Is there any way to deactivate the snippet detection? Or to exclude files?

**Comment by mrdrogdrog** [comment]
Using a `.license` file also doesn't help

```
reuse.project - WARNING - Copyright and licensing information for '.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs' have been found in '.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs.license' and the DEP5 file located at '.reuse/dep5'. The information in the DEP5 file has been overridden. Please ensure that this is correct.
```

**Comment by mrdrogdrog** [comment]
Creating .license files worked.

So it seems like the hierarchy is
- .license files
- header
- snippet detection
- dep5 file

It would be nice if you would add a mention to the README about this. :)

**Comment by mxmehl** [comment]
May I ask what you mean by "snippet detection"? A snippet should be treated the same way as a comment on the file header AFAIK.

**Comment by mrdrogdrog** [comment]
Oh sure. I'm not sure if it's the right term. I mean the partial detection of license information.
I stumbled over this term when reading the changelog of the reuse 2 release and it got stuck in my head.
Please correct me if i'm wrong.

**Comment by carmenbianca** [comment]
This change is documented in two places, but may need to be documented in more.

Currently:

- https://reuse.software/spec
- The change log

Future:

- Somewhere else in this repository, probably. README? The Sphinx docs?

**Comment by sebix** [comment]
I honor the effort which went into the new features, but I also thinkt that the new behaviour is not intuitive.
As of now, files which are excluded via dep5 (e.g. `debian/*`), are checked by snippet detection and give an error (e.g. `debian/changelog`). It even detects Copyright and licensing information in binary data like PNG-images.

I suggest that files which are *explicitly excluded* in dep5 are treated as *excluded* and should not raise errors.
Here you can find such a run: https://github.com/certtools/intelmq/actions/runs/5333484167/jobs/9664008913
```
reuse.project - WARNING - Copyright and licensing information for 'docs/_static/n6/data-flow.png' have been found in 'docs/_static/n6/data-flow.png.license' and the DEP5 file located at '.reuse/dep5'. The information in the DEP5 file has been overridden. Please ensure that this is correct.
reuse.project - WARNING - Copyright and licensing information for 'contrib/logcheck/README.md' have been found in 'contrib/logcheck/README.md' and the DEP5 file located at '.reuse/dep5'. The information in the DEP5 file has been overridden. Please ensure that this is correct.
reuse.project - WARNING - Copyright and licensing information for 'debian/copyright' have been found in 'debian/copyright' and the DEP5 file located at '.reuse/dep5'. The information in the DEP5 file has been overridden. Please ensure that this is correct.
# MISSING COPYRIGHT AND LICENSING INFORMATION

The following files have no licensing information:
* debian/copyright
```

**Comment by carmenbianca** [comment]
I will close this issue and refer to #779. The above use-case mentioned by @sebix is covered in the linked issue, and we will have a solution for that while also defining a clear order of precedence.

Thanks for the swift responses, and apologies for the few hours of broken workflow.

**Comment by mrdrogdrog** [comment]
Thanks for taking care so quickly :heart:
