### ISSUE TITLE
Make a quick v2.1.0 release

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#780]
Fixes #776 and adds an up-to-date version to the RTD documentation.

Depends on #778

**Comment by stephanlachnit** [comment]
@mxmehl @carmenbianca

FYI I just came accross this and https://github.com/fsfe/reuse-tool/issues/776, I think those can be closed :)

**Comment by carmenbianca** [comment]
Thanks @stephanlachnit !
