### ISSUE TITLE
How to annodate all files in a directory

### ISSUE THREAD

**Issue by fhg-isi** [fsfe/reuse-tool#817]
I tried to use the annotate option with the current directory:

`reuse annotate --copyright="Foo" --copyright-style=string-symbol --license=AGPL-3.0-or-later .`

However, it only seems to support single files. 

=> How can I apply it recursively for a whole directory?

**Comment by fhg-isi** [comment]
As a workaround, something like 

`find . -type f -exec reuse annotate --copyright="Foo" --copyright-style=string-symbol --license=AGPL-3.0-or-later {} \;`

might do the trick. However, that won't work with the GitHub action

https://github.com/fsfe/reuse-action

**Comment by fhg-isi** [comment]
The --recursive option did the trick

`reuse annotate --copyright="Foo" --copyright-style=string-symbol --license=AGPL-3.0-or-later --recursive --force-dot-license .`

**Comment by johann-wurz** [comment]
> The --recursive and --skip-unrecognised options help with that:
> 
> `reuse annotate --copyright="Foo" --copyright-style=string-symbol --license=AGPL-3.0-or-later --recursive --skip-unrecognised .`

Unfortunately, this does not work. The `--recursive`` passphrase didn't do anything in my case. Using the above workaround applying `find` works properly.
