### ISSUE TITLE
How to use a different badge color?

### ISSUE THREAD

**Issue by fhg-isi** [fsfe/reuse-tool#818]
(Don't know if this is the right location to ask.)

Reuse seems to use a different color for a passing badge:

![image](https://github.com/fsfe/reuse-tool/assets/76424482/807944d5-30d0-44bb-90dd-ccbd08f24395)

=> Can you please change the color or allow me to use a custom color?

**Comment by mxmehl** [comment]
Yes, it seems the default color for OK (green) seems to be #4c1.

Here's the PR for the API: https://git.fsfe.org/reuse/api/pulls/83
