### ISSUE TITLE
Support Zig programming language

### ISSUE THREAD

**Issue by sorairolake** [fsfe/reuse-tool#837]
Zig's line comments are the same as C's line comments (`//`). This language is still unstable, so this syntax may change.

> [!IMPORTANT]
> There are no block comments in Zig[^1].

[^1]: <https://ziglang.org/documentation/0.11.0/#Comments>

**Comment by BratishkaErik** [comment]
> Zig's line comments are the same as C's line comments (`//`). This language is still unstable, so this syntax may change.
> 
> Important There are no block comments in Zig[1](#user-content-fn-1-e6bbaaf485dedb05b0c47e2d21bbc6cc).
> ## Footnotes
> 
>     1. https://ziglang.org/documentation/0.11.0/#Comments [↩](#user-content-fnref-1-e6bbaaf485dedb05b0c47e2d21bbc6cc)

IMHO it's better to use top-level doc comments instead. https://ziglang.org/documentation/0.11.0/#Top-Level-Doc-Comments , since it's more likely to be prioritized by various Ziglang-related tooling (f.i. Autodoc).

**Comment by perillo** [comment]
> IMHO it's better to use top-level doc comments instead. https://ziglang.org/documentation/0.11.0/#Top-Level-Doc-Comments , since it's more likely to be prioritized by various Ziglang-related tooling (f.i. Autodoc).

For the Python language the SPDX tags are introduced using `#`, not a docstring.  For Zig it should be the same.

**Comment by BratishkaErik** [comment]
> > IMHO it's better to use top-level doc comments instead. https://ziglang.org/documentation/0.11.0/#Top-Level-Doc-Comments , since it's more likely to be prioritized by various Ziglang-related tooling (f.i. Autodoc).
> 
> For the Python language the SPDX tags are introduced using `#`, not a docstring. For Zig it should be the same.

On the other hand, ZON supports only `//` comments, so I agree with you.
