### ISSUE TITLE
Delete `dev` and `latest-extra` tags on Docker Hub

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#850]
After #849 is merged and/or v2.2.0 is released.

I don't think I have access to the account. Assigned to @mxmehl

**Comment by mxmehl** [comment]
You should have access to it. Would you please send me you Docker Hub account name so I can add you?

**Comment by mxmehl** [comment]
@carmenbianca, just found this issue. Do you already have access to DockerHub?

**Comment by mxmehl** [comment]
Concerned tags have been deleted.
