### ISSUE TITLE
Update readthedocs config

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#855]
I just read this section: https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

We can do away with our `docs/requirements.txt` generation in the Makefile and just use that.

**Comment by kbroch-rivosinc** [comment]
I think this might be finished via 5c287b768108ceb5600fe7fb09fa0fb08f863f19 ?

**Comment by carmenbianca** [comment]
Yes! Thanks @kbroch-rivosinc
