### ISSUE TITLE
Lint error: Multiple licenses resolve to LGPL-2

### ISSUE THREAD

**Issue by mxmehl** [fsfe/reuse-tool#87]
I tried to lint the Linux kernel today and received a fatal error, see below:

Git: `git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`
Branch: `master`
Commit: `089cf7f6ecb266b6a4164919a2e69bd2f938374a`

This error is rather new, with 0.4.0, linting Linux didn't throw an error.

```
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/dual/Apache-2.0, resolving to Apache-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/dual/CDDL-1.0, resolving to CDDL-1. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/dual/MPL-1.1, resolving to MPL-1. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/exceptions/GCC-exception-2.0, resolving to GCC-exception-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/GPL-2.0, resolving to GPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/LGPL-2.0, resolving to LGPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/preferred/LGPL-2.1, resolving to LGPL-2. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
reuse.project - CRITICAL - LGPL-2 is the SPDX License Identifier of both LICENSES/preferred/LGPL-2.1 and LICENSES/preferred/LGPL-2.0
Traceback (most recent call last):
  File "/usr/bin/reuse", line 11, in <module>
    load_entry_point('fsfe-reuse==0.5.0', 'console_scripts', 'reuse')()
  File "/usr/lib/python3.7/site-packages/reuse/_main.py", line 225, in main
    return parsed_args.func(parsed_args, out)
  File "/usr/lib/python3.7/site-packages/reuse/lint.py", line 255, in run
    project = create_project()
  File "/usr/lib/python3.7/site-packages/reuse/project.py", line 297, in create_project
    return Project(root)
  File "/usr/lib/python3.7/site-packages/reuse/project.py", line 63, in __init__
    self.licenses = self._licenses()
  File "/usr/lib/python3.7/site-packages/reuse/project.py", line 277, in _licenses
    "Multiple licenses resolve to {}".format(identifier)
RuntimeError: Multiple licenses resolve to LGPL-2
```

**Comment by carmenbianca** [comment]
This is because the spec now assumes that a license *always* has a file extension. The Linux kernel doesn't use file extensions for their licenses.

In and of itself, this wouldn't really be a problem, other than `LGPL-2.0` being detected as `LGPL-2` with the `.0` file extension. But the real problem here is that there is both an `LGPL-2.0` and an `LGPL-2.1` file, both resolving to `LGPL-2`.

I would like to fix this in the tool, somehow, but I'm not sure what an elegant solution is. It might be possible to do the following steps:

- If a license file has a name (e.g., `LICENSES/GPL-3.0-or-later`, without `.txt`) that matches a license on the SPDX License List, simply accept that license file. This used to be the case in 0.3.x, and is trivially easy to implement.

- Warn the user about this happening. Trivially easy.

- Somehow make the linter aware that this error occured, and make the linter fail. A little more difficult to implement, but certainly not impossible.

**Comment by mxmehl** [comment]
As an intermediate solution, your options 1 and 2 seem to be sufficient and don't contradict our principles generally. AFAIK we already have a few undocumented exceptions for Linux

**Comment by carmenbianca** [comment]
They weren't separate options. They were steps that belong together :)

The main question is: Should the lint fail if the licenses have no file extensions? The specification mentions they should, so I'm thinking the linter should fail. But this is such a trivial thing that I'm not sure…

**Comment by carmenbianca** [comment]
Ah, to be sure, the linter should (almost) never crash: The current behaviour is not very desireable and should be fixed regardless. When I say that the linter fails or not, I mean the report at the end.

**Comment by mxmehl** [comment]
Ah ok! Well then, that sounds like a good plan.

I agree that the linter should not crash. That also makes debugging the API harder (that's where I found out about this error, and since we do not parse stderr it wasn't that trivial to debug ;) )
