### ISSUE TITLE
[Feature request] Download licenses with a maximum line length of 80 characters

### ISSUE THREAD

**Issue by walpox** [fsfe/reuse-tool#877]
In typography, line length is a factor to consider to ease legibility of text.

The `reuse download` tool currently provides the license texts with full-length lines. This makes it so lines can span over 80-90 characters, making them possibly harder to read.

There are websites such as [choosealicense.com](https://choosealicense.com/) that provide the license texts with lines wrapped the way suggested in this feature request. After copying any licenses from there, I couldn't find any lines exceeding the recommended 80 character limit and the formatting looked nice as well.

Thus, it would be handy if the `reuse download` tool was capable of providing the license texts with lines wrapped at 80 character length. The same way presented by that website.

**Comment by mxmehl** [comment]
Thanks for the suggestion. Please have a look at #438 where we discussed why it is the way it is, and where to fix this. Hint: REUSE is not the correct place.
