### ISSUE TITLE
Use original text version for downloaded licenses

### ISSUE THREAD

**Issue by tyrion** [fsfe/reuse-tool#88]
Downloaded licenses are formatted differently than originals (in text form). I believe this is because licenses may be downloaded from https://github.com/spdx/license-list-data/ which apparently generates them from HTML.

You can see what I mean, here:
- original: https://github.com/spdx/license-list-data/blob/master/text/Apache-2.0.txt
- weird formatting: https://github.com/spdx/license-list-data/blob/master/text/Apache-2.0.txt

I am not sure if this issue should be opened also in the spdx repository, but I think it would be nice if REUSE did not alter licenses.

Is it ok to modify licenses such as GPL (even just to reformat them) that explicitly forbids changes to the license itself?

>  Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
>  Everyone is permitted to copy and distribute verbatim copies
>  of this license document, but changing it is not allowed.

**Comment by carmenbianca** [comment]
This is a known issue that was flagged with SPDX. I just can't find the issue for it at the moment…

@mxmehl ?

**Comment by tyrion** [comment]
Ok, thanks for the quick reply :)
For now I am including the original license text instead of the one downloaded by REUSE. Is this ok? Is the tool checking the content of the license files?

**Comment by carmenbianca** [comment]
> Is this ok? 

Yes! There is nothing wrong with this.

> Is the tool checking the content of the license files?

It isn't. There are countless variations of all the licenses floating around out there. This is kind of frustrating, so that's why we recommend taking the license from SPDX's repository, because that is almost certainly the correct, canonical license text.

**Comment by mxmehl** [comment]
> This is a known issue that was flagged with SPDX. I just can't find the issue for it at the moment…

Yeah, something rings a bell, but I have no idea where this came up... As Carmen wrote, REUSE taking our licenses from there is probably the safest option because in many cases there is no such thing as the "original license" any more.

**Comment by sschuberth** [comment]
> > This is a known issue that was flagged with SPDX. I just can't find the issue for it at the moment…
> 
> Yeah, something rings a bell, but I have no idea where this came up...

See https://github.com/spdx/license-list-data/issues/44.

**Comment by mxmehl** [comment]
Thanks for helping, @sschuberth! 

I will close this issue since it is up to SPDX to fix it.

**Comment by kirelagin** [comment]
This has been fixes upstream: spdx/LicenseListPublisher#83. Can this be reopened?

**Comment by mxmehl** [comment]
Since REUSE downloads from master, the improved format should be respected for future downloads.

E.g. compare Apache-2.0.txt in [current master](https://github.com/spdx/license-list-data/blob/master/text/Apache-2.0.txt) with the status from [2018](https://github.com/spdx/license-list-data/blob/22e29e1ed68308809ca3b81d06c63edb35202d13/text/Apache-2.0.txt).

Does this match your expectations?

**Comment by sschuberth** [comment]
> E.g. compare Apache-2.0.txt in [current master](https://github.com/spdx/license-list-data/blob/master/text/Apache-2.0.txt) with the status from [2018](https://github.com/spdx/license-list-data/blob/22e29e1ed68308809ca3b81d06c63edb35202d13/text/Apache-2.0.txt).
> 
> Does this match your expectations?

Thanks for this example. So far I did not look at the outcome of the changed code in the SPDX, but this actually proves that at least [my expectations are not met](https://github.com/spdx/LicenseListPublisher/pull/83#issuecomment-748108806) as the text still looks different from https://www.apache.org/licenses/LICENSE-2.0.txt.

**Comment by mxmehl** [comment]
Yes, I saw that as well. But still, I think REUSE is the wrong place to change this. It wouldn't make sense IMHO if we provided the license texts, SPDX is the best entity to deal with this.

**Comment by sschuberth** [comment]
> It wouldn't make sense IMHO if we provided the license texts, SPDX is the best entity to deal with this.

I totally agree. I just wanted to point out that unfortunately SPDX isn't yet ready for this.
