### ISSUE TITLE
Support for `.cabal` files

### ISSUE THREAD

**Issue by raboof** [fsfe/reuse-tool#882]
Haskell cabal files already have fields for license and copyright files, would be cool if `reuse` could pick those up:

https://cabal.readthedocs.io/en/stable/cabal-package.html#pkg-field-license

**Comment by carmenbianca** [comment]
This is WONTFIX. REUSE doesn't handle package-level copyright and licensing, only file-level. Supporting many different packaging standards is also rather out-of-scope.

**Comment by raboof** [comment]
> REUSE doesn't handle package-level copyright and licensing, only file-level.

That makes sense - at the file level it would be nice to use the copyright/licensing information in the cabal file for the cabal file itself, though - avoiding having to duplicate that information elsewhere (e.g. https://github.com/Nix-Security-WG/nix-security-tracker/pull/141/files#diff-1c645862be9de205dccc305cde10248abfe5b5a2297fc0502cbdd22cae5c9305R11)

> Supporting many different packaging standards is also rather out-of-scope.

Ofc if the cabal file format is too obscure to support that's fair.
