### ISSUE TITLE
Forcing a comment style seems broken, support for Cargo.lock

### ISSUE THREAD

**Issue by bbastin** [fsfe/reuse-tool#902]
Forcing a style with ```--style [style]``` seems to be broken in version 3.0.1. The error message informing me that a file type does not have a recognised file extension is the same whether this option is specified or not.

On another note, Cargo.lock files are currently not recognised (which is how I discovered the bug above). There was issue #390 that dealt with the topic, recommending either dot licenses or python-style comments. I would be open to implementing that, but there probably should be a discussion which of these styles should be used. Personally, I would prefer the in-file python style.

**Comment by carmenbianca** [comment]
Wrote a fix for this issue. I think this is a regression. I think I'll publish a patch release for this.

**Comment by carmenbianca** [comment]
I created #945 to discuss the Cargo.lock file support.
