### ISSUE TITLE
Using `reuse annotate --recursive` and `*.js` (or similar)

### ISSUE THREAD

**Issue by BigBlueHat** [fsfe/reuse-tool#912]
Right now, it does not seem possible to annotate all `.js` files in a project.

Using `--recursive .` will attempt to apply the header to _everything_ (and throw many unavoidable errors).
Using `--recursive *.js` will only apply things to the current directory (`--recursive` seems to have no effect).
Likewise `**/*.js` will only do the second tier.
Doing `**/**/*.js` will destroy your `node_modules/` contents...

Consequently, I'm still in search of somewhat surgically applying licenses with a project.

**Comment by carmenbianca** [comment]
Does `--recursive **.js` work? This seems like a shell thing to me.

**Comment by BigBlueHat** [comment]
`--recursive *.js` is the same as `*.js` (or `**.js` for both). Adding one or more `/` into the mix simply navigates down one folder deeper--with or without `--recursive`.

So, essentially `--recursive` seems to not be doing anything additional to what bash (in my case) is doing.

**Comment by BigBlueHat** [comment]
Ah...it _does_ do something with just `*`, so that's a win.

**Comment by carmenbianca** [comment]
A touch late, but I think you could also do some `find . -type f -name '*.js' | xargs -I {} reuse annotate --copyright BigBlueHat {}`-type magic here. Unix is pretty powerful. I don't think that reuse-tool needs any kind of change here that Unix can't do better.

Closing the issue, and thank you for reporting it.
