### ISSUE TITLE
`reuse download` looses license formatting 

### ISSUE THREAD

**Issue by BigBlueHat** [fsfe/reuse-tool#923]
I used `reuse download` to populate these files:
https://github.com/digitalbazaar/bedrock/blob/main/LICENSES/

which resulted in a weird version of the license without the typical whitespace--for example:
https://github.com/digitalbazaar/bedrock/blob/main/LICENSES/Apache-2.0.txt

I then found that the licenses here don't have that issue:
https://github.com/fsfe/reuse-tool/blob/main/LICENSES/Apache-2.0.txt

I'm not sure what's causing this difference...but I certainly hope the loss of whitespace is a bug...

**Comment by mxmehl** [comment]
No, it's not a bug per se, although it's not the state we'd wish to have. Everything should have been discussed in #438, also the reason why REUSE is not the place to tackle this.
