### ISSUE TITLE
`reuse-tool` should check the root LICENSE (and COPYING) file

### ISSUE THREAD

**Issue by BigBlueHat** [fsfe/reuse-tool#924]
I realize these files are not technically part of the [REUSE v3.0 spec](https://reuse.software/spec/), but most other robot based analysis tools will check this first...and often only--like GitHub, GitLab, etc.

Amusingly, I went through the effort of aligning a repo to the REUSE spec and tool...only to somehow have that file missed--which means the vast majority of other analysis tools ignored the effort...which was not the desired result.

So, REUSE could win more hearts and minds by also checking that file to make sure it matches the expected results from `reuse lint` and throw an error if it does not.

**Comment by mxmehl** [comment]
Thanks for the suggestion, but that's a deliberate decision by REUSE. Please also check [this FAQ](https://reuse.software/faq/#tradition) and a number of closed issues in this repo and the `reuse-docs` repo.
