### ISSUE TITLE
Potential confusion with  --suppress-deprecation

### ISSUE THREAD

**Issue by monacofj** [fsfe/reuse-tool#932]
When copyright info is found both in the file and in `dep5`, the output `reuse lint` suggests the option `---suppress deprecation`. Since the message results from using `lint` command, one may assume that it's a `lint` option and that the command line should be

```
$ reuse lint --suppress-deprecation
```

which does not work. 

It took me quite some time until I figured out that it's a `reuse` option, and the correct command line should be

```
$ reuse --suppress-deprecation lint
```

Perhaps it should be obvious but other users may get confused like me. 
It might be useful to give more detailed guidance in the output message.

**Comment by carmenbianca** [comment]
Hi @monacofj, thanks for the issue. I opened a PR for this which I will merge soon.
