### ISSUE TITLE
Should "reuse spdx" show the "packageVersion" if specified in the header?

### ISSUE THREAD

**Issue by buhtz** [fsfe/reuse-tool#935]
If a markdown file do specify the [packageVersion](https://spdx.github.io/spdx-spec/v2.3/package-information/#73-package-version-field) field in its header should the command `reuse spdx` report about that?

I tried it but the output of `reuse spdx` don't show the package version for that specific file.

I am asking to be sure if `reuse` is the correct tool to validate that field and if I make something wrong.

Here is the header of the markdown file where copyright and license is correct reported by `reuse spdx`.

```
<!---
# SPDX-FileCopyrightText: © 2023 Christian BUHTZ <c.buhtz@posteo.jp>
# PackageVersion: 1.2.3
# SPDX-PackageVersion: 1.2.3
# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the program "Hyperorg" which is released under GNU
# General Public License v3 (GPLv3).
# See folder LICENSES or go to <https://www.gnu.org/licenses/#GPL>.
-->

```

**Comment by carmenbianca** [comment]
I don't think REUSE is the correct tool for this. The scope of REUSE is fairly narrow:

- Making sure all files have copyright and licensing information.
- Making sure that all licenses live in LICENSES/.

Everything else is effectively out of scope, kind of, more or less. `reuse spdx` is a rudimentary tool that conveys all information found by REUSE in a standard format (SPDX). It's due a little update to support some non-tag-value output formats. But ultimately, if you want an SPDX BOM that contains _more_ than just the copyright and licensing information, REUSE is not the tool with which to produce it.

There exist other tools that generate SPDX files that are probably more fit for purpose. [This page](https://reuse.software/comparison/) documents some of the comparisons.
