### ISSUE TITLE
Copyright styles and merging

### ISSUE THREAD

**Issue by garethsb** [fsfe/reuse-tool#948]
Currently supported styles:

```
    "spdx": "SPDX-FileCopyrightText:",
    "spdx-c": "SPDX-FileCopyrightText: (C)",
    "spdx-symbol": "SPDX-FileCopyrightText: ©",
    "string": "Copyright",
    "string-c": "Copyright (C)",
    "string-symbol": "Copyright ©",
    "symbol": "©",
```

The first issue I encountered is that none of the `_COPYRIGHT_PATTERNS` match the `spdx-c` style, so `--merge-copyrights` is not effective. A small tweak to the first pattern is sufficient - would a PR be accepted?

Secondly, I've been asked to use the (even more redundant) style: "SPDX-FileCopyrightText: Copyright (c) <year>"...
Would a PR to add `sdpx-string-c` (etc.) be accepted?

Thanks!

**Comment by carmenbianca** [comment]
Hi @garethsb , thanks for opening the issue!

The answer is yes to both. Contributions for this would be very welcome.

**Comment by sin-ha** [comment]
Hi @carmenbianca can you PTAL #979 
TIA

**Comment by sin-ha** [comment]
Pinging again @carmenbianca  can you please take a look

**Comment by sin-ha** [comment]
Thanks a lot @carmenbianca any ideas on when this would be released?
