### ISSUE TITLE
Usage steps on Windows environment

### ISSUE THREAD

**Issue by marcoXbresciani** [fsfe/reuse-tool#97]
Hi all,
  being stuck on Windows environment at work, I'm trying to apply REUSE conventions to my projects.

I'm not used to Python at all: how to properly install and use REUSE on Windows?!
I've installed Python and PIP and fsfe-reuse following the guidelines, and everything seemed fine.

But can't run "reuse lint" since there's no /home, no /.local, ... Hints?

I've checked my windows user directory and I've seen that Python packages are installed on AppData/Roaming/python38/.../../... And so on. So I can, at least, get to the installation folder.

But then?

Thank you,

Marco

**Comment by carmenbianca** [comment]
I assume that this is a PATH problem. In Windows (and in Linux), executables can be in any directory on the computer. But when you type `my_executable` and there is no file named `my_executable` in your current working directory, then the computer does not know what to do. For that reason, on Linux, there is the `$PATH` variable. Here is mine for example, represented in two ways:

```python
(reuse) carmenbianca@thinkpad-x395 ~/Projektoj/FSFE $ echo $PATH                                                                                                                              
/home/carmenbianca/.virtualenvs/reuse/bin:/home/carmenbianca/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
(reuse) carmenbianca@thinkpad-x395 ~/Projektoj/FSFE $ $PATH                                                                                                                                   
EnvPath(
['/home/carmenbianca/.virtualenvs/reuse/bin',
 '/home/carmenbianca/.local/bin',
 '/usr/local/bin',
 '/usr/local/sbin',
 '/usr/bin',
 '/usr/sbin']
)
```

It is, effectively, a list of directories that are known to contain executables. So when I type `my_executable`, the computer first checks whether such an executable exists in the first directory, then the second, then the third, and so forth. If it finds the executable, it is executed. If it does not find the executable, nothing happens.

Alternatively, you can type the full path to the file: `/usr/local/bin/my_executable`, for instance, and `$PATH` will be ignored.

So what you *probably* need to do is add the directory that contains `reuse` to Windows' `$PATH`. I haven't used Windows in years, however, and have no idea how to do that. But maybe this helps you along?

**Comment by marcoXbresciani** [comment]
Yes, probably you're right, but where is `reuse`?

When (re)installing via `pip3 install --user fsfe-reuse` I see this
```
C:\Users\mbresciani>pip3 install --user fsfe-reuse
Requirement already satisfied: fsfe-reuse in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (0.5.0)
Requirement already satisfied: requests in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from fsfe-reuse) (2.22.0)
Requirement already satisfied: boolean.py in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from fsfe-reuse) (3.7)
Requirement already satisfied: license-expression in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from fsfe-reuse) (1.0)
Requirement already satisfied: Jinja2 in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from fsfe-reuse) (2.10.3)
Requirement already satisfied: binaryornot in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from fsfe-reuse) (0.4.4)
Requirement already satisfied: python-debian in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from fsfe-reuse) (0.1.36)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from requests->fsfe-reuse) (2019.9.11)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from requests->fsfe-reuse) (1.25.6)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from requests->fsfe-reuse) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from requests->fsfe-reuse) (3.0.4)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from Jinja2->fsfe-reuse) (1.1.1)
Requirement already satisfied: six in c:\users\mbresciani\appdata\roaming\python\python38\site-packages (from python-debian->fsfe-reuse) (1.12.0)
```
and looking at that folder I see
* folder `fsfe_reuse-0.5.0.dist-info` containing "info" files such as `AUTHORS.rst`, `entry_points.txt`, `INSTALLER`, `METADATA`, `RECORD`, `top_level.txt` and `WHEEL`.
* folder `reuse` containing a set of 13 `.py` files (`__init__.py`, `download.py`, `init.py`, ... but using `python` on any of them I see some kind of import errors.

It seems there no actual executable file.
Ideas?

**Comment by carmenbianca** [comment]
I'm not sure :( One solution would be to do `python3 -m reuse`, but that doesn't currently work. I can make it work, though.

**Comment by carmenbianca** [comment]
Pushed version 0.5.1 to PyPI. You can now do `python3 -m reuse`. It's maybe not an ideal solution, but it works. Otherwise, get in contact with some Windows Pythonistas who are much more knowledgeable on this topic :)

**Comment by marcoXbresciani** [comment]
It works! Cool! Thank you!

**Comment by marcoXbresciani** [comment]
It seems latest versions are working using simply `reuse` (from PowerShell, at least) instead of `python3 -m reuse` from Command Prompt...
