### ISSUE TITLE
annotate: Rename `--copyright-style` to `--copyright-prefix`

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#973]
This is less confusing when compared to `--style`.

`--copyright-style` must still be usable. `argparse.SUPPRESS` can be used to hide it from `reuse annotate --help`.

Elsewhere in the code, the word `style` (when related to `--copyright-style`) should be renamed `prefix`.

See also #947 for a bigger improvement to how copyright statements are handled. Not necessarily relevant to this issue, though.

**Comment by kbroch-rivosinc** [comment]
I'll put PR in for this.  Similar to #1014

**Comment by carmenbianca** [comment]
Closed by #1016
