### ISSUE TITLE
annotate: Add `--skip-unrecognized`

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#974]
Currently, `--skip-unrecognised` exists. Note the S instead of the Z.

`--skip-unrecognized` should be added as an alias of `--skip-unrecognised`. It should be hidden in the `--help` text. `argparse.SUPPRESS` may help with this.

**Comment by kbroch-rivosinc** [comment]
I'll put a PR in for this.

**Comment by carmenbianca** [comment]
Closed by #1014
