### ISSUE TITLE
Savannah requirements compatibility

### ISSUE THREAD

**Issue by marcoXbresciani** [fsfe/reuse-tool#98]
Is REUSE compatible why requirements for projects on Savannah?

Specifically: this http://savannah.gnu.org/maintenance/HowToGetYourProjectApprovedQuickly/ writes about the valid copyright notices http://savannah.gnu.org/maintenance/ValidNotices/ and so on.

Thank you,

Marco

**Comment by carmenbianca** [comment]
*Probably*. I don't see anything immediately invalidating. But ultimately that's up to the Savannah people.

Closing this issue because it's upstream. You can still comment if you have more feedback.

**Comment by marcoXbresciani** [comment]
I've opened a similar issue on Savannah side. See https://savannah.nongnu.org/support/?110070
