### ISSUE TITLE
Write test for raw `*` and raw `**` in REUSE.toml

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#981]
See the tests here:  https://github.com/fsfe/reuse-tool/blob/7ab812407cb62b590d0a646546b1cfa7b4661e66/tests/test_global_licensing.py#L228

There should be tests for raw `*` and raw `**`.

**Comment by mxmehl** [comment]
Also, this test fails, but according to the spec if should work:

```py
def test_match_asterisk(self):
    """Match everything in local directory."""
    item = AnnotationsItem(paths=["*"])
    assert item.matches("foo.py")
    assert item.matches(".gitignore")
    assert not item.matches("src/foo.py")
    assert not item.matches(".foo/bar")
```

**Comment by carmenbianca** [comment]
My hypothesis is that `*` is broken when it's the final character. This makes sense when I remember my implementation.
