### ISSUE TITLE
Add support for mercurial version control system

### ISSUE THREAD

**Issue by marcoXbresciani** [fsfe/reuse-tool#99]
Together with git should be easy to add support to mercurial dvcs (instead of .gitignore you just search for .hgignore).

**Comment by carmenbianca** [comment]
That would be nice. Do you know any projects that would like to use REUSE, but are currently not using Git?

**Comment by marcoXbresciani** [comment]
Yup, all mine. :)
  See https://savannah.nongnu.org/users/marcobresciani

I had in mind to start with the AAMfP project, since it's the most recently updated. But then I can update both gravaty and wwwjdic (very similar structures) and then the other two.

**Comment by marcoXbresciani** [comment]
> Yup, all mine. :)
> See https://savannah.nongnu.org/users/marcobresciani
> 
> I had in mind to start with the AAMfP project, since it's the most recently updated. But then I can update both gravaty and wwwjdic (very similar structures) and then the other two.

But first, I need to solve the issue (#97) of using REUSE on Windows... ;)

**Comment by marcoXbresciani** [comment]
> > Yup, all mine. :)
> > See https://savannah.nongnu.org/users/marcobresciani
> > I had in mind to start with the AAMfP project, since it's the most recently updated. But then I can update both gravaty and wwwjdic (very similar structures) and then the other two.
> 
> But first, I need to solve the issue (#97) of using REUSE on Windows... ;)

Solved. :)

**Comment by marcoXbresciani** [comment]
News on this?

Is it somehow possible in dep5 file to specify that `.hg` folder is like `.git`?

**Comment by carmenbianca** [comment]
No update on this. I might take a look at this later this week. I've never used Mercurial, though, so it'll be a bit of a challenge. And the codebase will probably require some refactoring, because it currently makes some Git-as-default assumptions.
