### ISSUE TITLE
Is there a way to remove copyright headers?

### ISSUE THREAD

**Issue by scanossjeronimo** [fsfe/reuse-tool#996]

**Comment by mxmehl** [comment]
Let me copy the mail I've sent you this morning ;)

With the helper tool, such a functionality is not supported. After all, REUSE’s goal is to *add* copyright information, not *remove* it ;)

However, the tool can replace existing headers with new information, e.g. to remove the whole license notice blurbs and just add proper SPDX tags.

**Comment by carmenbianca** [comment]
There might realistically be a way to do this if we fix #947 first.
